const u=(ids,source,en,pt)=>({ids,source,en,pt});
export const biodynamicsDepth=[
u([0,8],'What Is Biodynamics? · Introduction and seven selected lectures',[
'Connect the parts without confusing their authors',
'The anthology’s route has a logic: learn a way of attending to nature, encounter a spiritual account of nature’s activities, and then consider agricultural interventions based on that account. Courtney adds his own interpretation of preparations and their religious significance. Means introduces the selected lectures. These contributions help frame the reading, but they do not turn every sentence in the volume into a statement by Steiner.',
'Use a particular garden as a continuing example. First describe what is present: soil, water, plants, surrounding habitats and human work. Next identify which relationship the book asks you to notice. Finally state the spiritual interpretation or intervention being proposed and who proposes it. A description of a preparation tells you what the practice is; an account of a successful harvest reports an outcome; a theory explains why the outcome is attributed to the practice. Keeping these three steps distinct is essential to both the opening reading and the final project.'
],[
'Relacione as partes sem confundir seus autores',
'A coletânea segue uma lógica: aprender um modo de atenção à natureza, conhecer uma descrição espiritual de suas atividades e considerar intervenções agrícolas baseadas nela. Courtney acrescenta sua interpretação dos preparados e de seu significado religioso. Means apresenta as palestras selecionadas. Essas contribuições enquadram a leitura, sem transformar cada frase do volume numa afirmação de Steiner.',
'Use um jardim como exemplo contínuo. Descreva primeiro solo, água, plantas, habitats vizinhos e trabalho humano. Identifique depois a relação que o livro pede observar. Por fim, explicite a interpretação espiritual ou intervenção proposta e seu autor. Descrever um preparado informa a prática; relatar uma colheita bem-sucedida informa um resultado; uma teoria explica por que se atribui o resultado à prática. Distinguir essas etapas é essencial na leitura inicial e no projeto final.'
]),
u([1],'What Is Biodynamics? · Spiritual Beings I · PDF 35–44',[
'Why attention to a colour is only the beginning of the exercise',
'The lecture does not simply assign a meaning to blue or green. It describes a movement from a sensory impression toward an inward activity. First the person attends to the impression; then the impression recedes while a particular quality of feeling or thought remains. Steiner treats this as education of the perceiver, a change in how experience is received rather than the collection of more labels for natural objects.',
'The distinction is easiest to see with two descriptions. “I saw a blue sky” reports the object of attention. “I noticed how sustained attention changed my inward response” reports a further experience. Neither sentence by itself establishes the spiritual beings the lecture goes on to describe. The proposed training and the claimed perception must therefore remain distinct steps. Explain the sequence and the quality the author associates with it; do not treat any passing mood, imagined image or preferred colour as confirmation of the whole account.'
],[
'Por que a atenção à cor é apenas o começo do exercício',
'A palestra não atribui simplesmente um significado ao azul ou ao verde. Descreve um movimento da impressão sensorial à atividade interior. A pessoa primeiro contempla a impressão; depois ela recua, enquanto permanece uma qualidade de sentimento ou pensamento. Steiner trata isso como educação de quem percebe: muda o modo de receber a experiência, além de acumular rótulos para objetos naturais.',
'Compare duas descrições: “Vi um céu azul” informa o objeto da atenção; “Percebi como a atenção prolongada modificou minha resposta interior” informa outra experiência. Nenhuma frase estabelece, sozinha, os seres espirituais descritos depois. O treinamento proposto e a percepção alegada permanecem etapas distintas. Explique a sequência e a qualidade associada pelo autor, sem tomar um humor passageiro, uma imagem imaginada ou uma preferência de cor por confirmação do relato inteiro.'
]),
u([2],'What Is Biodynamics? · Spiritual Beings II · PDF 45–55',[
'Activity, timing and the relation of the whole',
'The three levels in this lecture answer different questions. Elemental beings explain particular activities in nature. Spirits of the cycles explain how activities recur and are coordinated in time. The planetary spirit concerns Earth as a whole in relation to other heavenly bodies. Moving upward in the account does not mean finding a larger version of the same object; the explanatory question changes.',
'An original orchestral comparison can clarify the relationships: a part has its own activity, the entries have timing, and the performance has an overall unity. This comparison helps distinguish levels but does not prove that Earth is organized by spiritual beings. The human correspondence works similarly: life, inward coordination and individuality are related without becoming identical. The insistence on conscience and memory then has a specific purpose. A claimed widening of awareness must not dissolve the continuity of the person who acts and remains accountable for those actions.'
],[
'Atividade, tempo e relação do conjunto',
'Os três níveis respondem a perguntas diferentes. Seres elementais explicam atividades particulares; espíritos dos ciclos explicam recorrência e coordenação temporal; espírito planetário trata da Terra inteira em relação aos outros astros. Subir nessa descrição não significa encontrar um objeto semelhante e maior: muda a pergunta explicativa.',
'Uma comparação com orquestra esclarece: cada parte tem atividade, as entradas têm tempo e a apresentação tem unidade. A comparação distingue níveis, mas não prova a organização espiritual da Terra. A correspondência humana funciona de modo semelhante: vida, coordenação interior e individualidade relacionam-se sem se tornarem idênticas. A insistência em consciência moral e memória tem então finalidade precisa. Ampliar a percepção não deve dissolver a continuidade da pessoa que age e responde por suas ações.'
]),
u([3],'What Is Biodynamics? · Elementals I · PDF 56–66',[
'Read the plant as a sequence of cooperating activities',
'Listing gnome, undine, sylph and fire spirit leaves the central idea unexplained. The lecture proposes that the plant’s visible development depends on activities with different relationships to mineral, moisture, light and warmth. The root activity prepares something for the rest of the plant; leaf and aerial activity continue the process; flowering and seed formation bring another relationship into play. The beings are presented as participants in a connected process, not decorations attached to four plant parts.',
'Make a diagram in which every arrow has a verb: receives, carries, shapes, preserves or joins, using the actual wording of the assigned passage as your guide. Then explain how one activity depends on another. At the fertilization claim, stop and state the disagreement with botany explicitly. The lecture locates a decisive joining in the Earth, whereas the botanical account linked below describes fertilization in the ovule. Calling the whole account “just symbolic” would conceal a substantive claim the author makes.'
],[
'Leia a planta como sequência de atividades cooperantes',
'Listar gnomo, ondina, silfo e espírito do fogo deixa a ideia central sem explicação. A palestra propõe atividades com relações diferentes com mineral, umidade, luz e calor como condições do desenvolvimento visível. A atividade da raiz prepara algo; folha e atividade aérea continuam o processo; floração e formação da semente introduzem outra relação. Os seres participam de um processo conectado, não decoram quatro partes vegetais.',
'Desenhe setas com verbos: recebe, transporta, forma, preserva ou une, orientando-se pela passagem estudada. Explique a dependência entre as atividades. Ao chegar à fecundação, explicite a divergência com a botânica. A palestra situa uma união decisiva na Terra; a descrição botânica indicada situa a fecundação no óvulo. Chamar tudo de “apenas simbólico” ocultaria uma afirmação substantiva do autor.'
]),
u([4],'What Is Biodynamics? · Elementals II · PDF 67–76',[
'A complement completes a relationship',
'When Steiner calls a spiritual activity a complement to an animal form, he is asking the reader to see the visible form as one part of a larger organization. The account does not mean that a bird is literally missing a human anatomical part. It interprets different animal forms through dominant activities and the spiritual activity that would complete them. First identify the visible form, then the proposed complement, then the relationship that makes them a pair.',
'The later discussion of displaced activity depends on the same logic. Something described as constructive in one setting may be described as destructive when it works outside its appropriate relation to the whole. An original example is a useful task performed at the wrong stage of a project: its effect depends on placement. That example clarifies the relation, not the lecture’s specific claims about parasites, poison or illness. The dream passages likewise explain the author’s theory of awareness, not a method for diagnosing spiritual encounters from ordinary dreams.'
],[
'Um complemento completa uma relação',
'Ao chamar uma atividade espiritual de complemento de uma forma animal, Steiner pede ver a forma visível como parte de organização maior. Não afirma que uma ave careça literalmente de uma parte anatômica humana. Interpreta formas animais por atividades predominantes e pela atividade espiritual que as completaria. Identifique forma visível, complemento proposto e relação que os torna um par.',
'A atividade deslocada segue a mesma lógica. Algo descrito como construtivo numa situação pode ser destrutivo fora de sua relação adequada com o conjunto. Pense numa tarefa útil executada na etapa errada de um projeto: o efeito depende da posição. Isso esclarece a relação, não as afirmações sobre parasitas, veneno ou doença. As passagens sobre sonhos explicam igualmente a teoria da percepção do autor, sem fornecer diagnóstico de encontros espirituais a partir de sonhos comuns.'
]),
u([5],'What Is Biodynamics? · Agriculture I · PDF 77–95',[
'Material, vessel, season and application belong to one proposal',
'The two horn preparations are not explained by memorizing 500 and 501. In the account, manure and silica are different starting materials; the horn has an attributed concentrating or reflecting role; winter and summer provide contrasting conditions; the finished preparation enters a particular agricultural task. Remove any of these relationships and the learner no longer sees why the source specifies the whole procedure.',
'Build a comparison with four headings: material, container, season and intended role. Under each, write what the lecture claims rather than a modern explanation invented to make it sound plausible. Then add a fifth heading, open practical question, for quantities, timing or conditions the discussion leaves to investigation. This preserves the difference between a confident spiritual rationale and unsettled application. The preparations supplement ordinary manuring in the text. Studying them does not mean assuming that they replace soil care or that a small dose has a demonstrated effect merely because its theoretical role is described.'
],[
'Material, recipiente, estação e aplicação formam uma proposta',
'Os preparados de chifre não se explicam memorizando 500 e 501. Esterco e sílica são materiais distintos; ao chifre atribui-se função concentradora ou refletora; inverno e verão oferecem condições contrastantes; o preparado pronto participa de uma tarefa agrícola. Retirar essas relações impede compreender por que a fonte especifica o procedimento inteiro.',
'Compare material, recipiente, estação e função pretendida. Registre o que a palestra afirma, sem inventar uma explicação moderna para torná-la plausível. Acrescente perguntas práticas abertas sobre quantidades, tempo e condições deixadas à investigação. Isso preserva a diferença entre justificativa espiritual confiante e aplicação ainda não resolvida. No texto, os preparados complementam a adubação comum. Estudá-los não exige presumir que substituam o cuidado do solo ou que uma dose pequena tenha efeito demonstrado porque seu papel teórico foi descrito.'
]),
u([6],'What Is Biodynamics? · Agriculture II · PDF 96–113',[
'Why six preparations are not six interchangeable additives',
'Each preparation has a proposed relationship to an organizing process in the manure. Yarrow concerns sulfur and potassium; chamomile brings nitrogen and calcium into the account; nettle is assigned a coordinating sensitivity; oak bark a balancing calcium process; dandelion a silica–potassium relation; valerian a phosphorus relation. To understand the scheme, say what each is supposed to help the whole do. A list of plant names alone cannot explain the differentiation.',
'The sheath and preparation process are also part of the proposal. Making a preparation, preserving it and inserting it into manure are different stages. The discussion’s uncertainty about putting everything into one hole therefore matters: a coordinated set is not automatically a mixture whose members can be combined indiscriminately. Use the table to reconstruct these distinctions on paper. The comparison explains the historical method without claiming that the attributed nutrient relationships have been measured, or requiring the learner to collect animal materials and carry out the procedure.'
],[
'Por que seis preparados não são seis aditivos intercambiáveis',
'Cada preparado recebe uma relação com processos organizadores do esterco. Mil-folhas envolve enxofre e potássio; camomila, nitrogênio e cálcio; urtiga, sensibilidade coordenadora; casca de carvalho, equilíbrio ligado ao cálcio; dente-de-leão, sílica e potássio; valeriana, fósforo. Para compreender, explique o que cada um ajudaria o conjunto a fazer. Apenas listar plantas não explica sua diferenciação.',
'Envoltório e processo também integram a proposta. Produzir, conservar e inserir no esterco são etapas diferentes. A incerteza sobre colocar tudo num único orifício importa: um conjunto coordenado não é automaticamente uma mistura indiscriminada. Reconstrua essas distinções no papel usando a tabela. A comparação explica o método histórico sem afirmar que suas relações nutricionais foram medidas nem exigir coleta de materiais animais e execução do procedimento.'
]),
u([7],'What Is Biodynamics? · Agriculture III · PDF 114–130',[
'From a theory of reproduction to a claim about a field',
'The lecture’s starting distinction is between a plant’s place in nature and its unwanted presence relative to a grower’s aim. It then connects growth and reproduction with different cosmic influences and proposes interventions on that basis. The reasoning has several stages: identify the unwanted process, assign its cause within the spiritual model, and choose a preparation intended to counter it. Understanding the last stage requires the first two.',
'Now separate that explanation from evaluating a result. If fewer unwanted plants appear after an intervention, weather, prior management and differences between plots may also matter. A fair comparison would state the expected outcome in advance and retain comparable untreated conditions. This is an original way to clarify what external testing asks; it does not imply that Steiner presented a modern experimental protocol. His statements of inward certainty and his invitations to investigate practical details both remain part of the reading. Learn the tension rather than resolving it by omitting one side.'
],[
'Da teoria da reprodução à afirmação sobre um campo',
'A palestra distingue o lugar de uma planta na natureza de sua presença indesejada para o objetivo de quem cultiva. Depois liga crescimento e reprodução a influências cósmicas e propõe intervenções. O raciocínio identifica o processo indesejado, atribui uma causa no modelo espiritual e escolhe um preparado que o contrariaria. Compreender a última etapa exige as duas anteriores.',
'Separe explicação e avaliação do resultado. Se surgem menos plantas indesejadas, clima, manejo anterior e diferenças entre parcelas também podem importar. Uma comparação justa declararia antecipadamente o resultado esperado e manteria condições comparáveis sem intervenção. Esse exemplo esclarece o teste externo; não atribui a Steiner um protocolo experimental moderno. Sua certeza interior e seus convites à investigação prática permanecem na leitura. Compreenda a tensão em vez de resolvê-la omitindo um dos lados.'
])
];
