// Original teaching, checked against the supplied Foodwise captures and chapter map.
const u=(ids,source,en,pt)=>({ids,source,en,pt});
export const foodwiseDepth=[
u([0],'Foodwise · Preface and Introduction · PDF 13–23',[
'Read the book as an argument about relationships',
'Cook begins from experience in kitchens, families and communities. This matters because her question is larger than which substances a food contains. She asks how growing, preparing and sharing food connect a person to land and to other people. A meal therefore has several histories: the crop’s cultivation, the cook’s work, the eater’s memories and the social arrangements that make it available.',
'Keep these histories distinct while following their connections. Imagine bread at a community meal: its ingredients can be listed, the work of making it can be described, and its meaning to the group can be interpreted. None of these descriptions replaces the others. Cook adds an anthroposophical account of formative and spiritual activity. Learn what that account proposes before deciding whether the experience of a good meal supports it. A personal story explains why a question mattered to the author; it does not by itself settle the question for everyone.'
],[
'Leia o livro como um argumento sobre relações',
'Cook parte da experiência em cozinhas, famílias e comunidades. Isso importa porque sua pergunta vai além das substâncias presentes num alimento. Ela investiga como cultivar, preparar e compartilhar comida liga a pessoa à terra e aos outros. Uma refeição tem, portanto, várias histórias: o cultivo da planta, o trabalho de quem cozinha, as lembranças de quem come e as relações sociais que a tornam disponível.',
'Distinga essas histórias enquanto acompanha suas conexões. Imagine um pão numa refeição comunitária: podemos listar ingredientes, descrever o trabalho de preparação e interpretar seu significado para o grupo. Nenhuma descrição substitui as demais. Cook acrescenta uma explicação antroposófica da atividade formativa e espiritual. Compreenda o que ela propõe antes de decidir se a experiência de uma boa refeição a sustenta. Um relato pessoal explica por que uma questão importou à autora; sozinho, não resolve a questão para todos.'
]),
u([1],'Foodwise · Chapter 1 · PDF 25–57',[
'How food history becomes a story of consciousness',
'The chapter’s central argument concerns a changing relationship with the world. Cook pictures early humanity as participating in a meaningful cosmos, with food gathering, ritual and social belonging closely connected. She then follows increasing practical control: cultivating land, storing grain, trading foods and eventually organizing industrial production. In her account, people gain independence and self-awareness while risking a loss of felt connection with living processes. That gain-and-loss relationship explains why she tells a history of consciousness alongside a history of food.',
'Follow the agricultural transition through concrete steps. A stored harvest can support life beyond the day’s gathering. Cultivation asks people to attend to a particular place over time; boundaries, ownership and the distribution of surplus become questions. Cook uses Cain and Abel to give an image of the tension between settled cultivation and pastoral life. The myth is doing interpretive work: it gives a human meaning to a transition. It is not a dated record establishing exactly when farming began, and Cook herself warns against forcing such stories into a rigid chronology.',
'Her sequence then considers sacred foods and rituals, the Egyptian connection between grain, fermentation and social order, Greek questions about proportion and ways of living, and later changes in trade and production. Do not reduce these sections to a list of civilizations and menus. Ask in each case: who produces food, who controls its distribution, what preparation changes it, and what meaning people give to eating it? The same grain can participate in worship, everyday nourishment, taxation or commercial exchange. The food’s social role changes even when its name stays the same.',
'Bring the argument into an original example: compare bread made from a household’s stored grain with a packaged loaf bought far from its production. Describe the differences in labour, time, knowledge and dependence on other people before judging either situation. Cook would ask what connection has become less visible and how conscious responsibility might restore it. Her spiritual sequence remains her interpretive framework; her selective historical narrative cannot stand for every culture or rank living peoples by their supposed level of consciousness.'
],[
'Como a história da alimentação se torna uma história da consciência',
'O argumento central do capítulo trata da mudança na relação com o mundo. Cook apresenta a humanidade antiga como participante de um cosmos significativo, no qual coleta, ritual e pertencimento social estavam ligados. Depois acompanha o controle prático crescente: cultivar a terra, armazenar cereais, comerciar alimentos e organizar a produção industrial. Em sua interpretação, as pessoas ganham independência e autoconsciência, mas arriscam perder o vínculo vivido com os processos da vida. Essa relação entre ganho e perda explica por que ela narra a história da consciência junto à da alimentação.',
'Acompanhe a transição agrícola por etapas concretas. Uma colheita armazenada sustenta a vida além da coleta diária. Cultivar exige acompanhar um lugar ao longo do tempo; limites, propriedade e distribuição do excedente tornam-se questões. Cook usa Caim e Abel como imagem da tensão entre agricultura sedentária e vida pastoril. O mito realiza um trabalho interpretativo: atribui sentido humano à transição. Não é um registro datado que estabeleça exatamente quando a agricultura começou, e a própria Cook adverte contra enquadrar essas histórias numa cronologia rígida.',
'Sua sequência aborda alimentos e rituais sagrados, a relação egípcia entre cereais, fermentação e ordem social, questões gregas de proporção e modo de viver e mudanças posteriores no comércio e na produção. Não reduza essas partes a uma lista de civilizações e cardápios. Pergunte em cada caso: quem produz, quem distribui, qual preparação transforma o alimento e que sentido as pessoas atribuem ao comer? O mesmo cereal pode participar de culto, nutrição cotidiana, tributação ou comércio. Sua função social muda mesmo quando o nome permanece.',
'Traga o argumento para um exemplo original: compare pão feito com o cereal armazenado por uma família e pão embalado comprado longe de sua produção. Descreva diferenças de trabalho, tempo, conhecimento e dependência de outras pessoas antes de julgar as situações. Cook perguntaria qual vínculo ficou menos visível e como a responsabilidade consciente poderia recuperá-lo. Sua sequência espiritual permanece um esquema interpretativo; a narrativa histórica seletiva não representa todas as culturas nem permite classificar povos atuais por supostos níveis de consciência.'
]),
u([2],'Foodwise · Chapter 2 · PDF 58–70',[
'What it means to think of a farm as a whole',
'An inventory lists soil, crops, animals, hedges and workers separately. An account of a farm organism asks what passes between them. Crops draw on soil conditions; animals eat farm products; manure and plant residues return to cultivation; boundaries and habitats influence the setting in which crops grow. Cook’s point is to judge an intervention through these relationships, rather than through the immediate yield of one field alone. In biodynamic interpretation, this practical whole also has a spiritual dimension.',
'Her discussion of community-supported agriculture extends the same question beyond the farm gate. If customers promise support before harvest and share losses as well as produce, the relationship differs from buying only when a product is cheap and plentiful. The grower’s uncertainty becomes a shared responsibility. Imagine a poor harvest: a purely transactional customer asks for the usual quantity, while a participating group must discuss smaller shares and the farm’s continuing costs. This example explains the social principle; it does not establish that any particular production method always gives better yields or nutrition.'
],[
'O que significa pensar a fazenda como um todo',
'Um inventário enumera solo, cultivos, animais, cercas vivas e trabalhadores separadamente. A ideia de organismo agrícola pergunta o que circula entre eles. Os cultivos dependem das condições do solo; animais consomem produtos da fazenda; esterco e resíduos vegetais retornam ao cultivo; limites e habitats influenciam o ambiente. Cook propõe avaliar uma intervenção por essas relações, além do rendimento imediato de um único campo. Na interpretação biodinâmica, esse conjunto prático também tem dimensão espiritual.',
'A discussão da agricultura apoiada pela comunidade amplia a pergunta para além da propriedade. Quando consumidores prometem apoio antes da colheita e compartilham perdas e produtos, a relação difere de comprar apenas quando algo está barato e abundante. A incerteza de quem cultiva torna-se responsabilidade compartilhada. Imagine uma colheita ruim: o comprador ocasional exige a quantidade habitual; o grupo participante precisa discutir porções menores e os custos contínuos da fazenda. O exemplo explica o princípio social; não demonstra que um método sempre produza maior rendimento ou melhor nutrição.'
]),
u([3],'Foodwise · Chapter 3 · PDF 71–79',[
'Four questions about one person',
'The fourfold model becomes clearer when each term answers a different question. Physical body concerns material embodiment. Etheric body names the proposed organization that sustains a living form through growth and renewal. Astral body names inward experience, such as appetite, pleasure and aversion. The I concerns the individual who can take a conscious position toward that experience. These are intended as interpenetrating activities of one person, not four objects stacked inside a body.',
'Consider a familiar meal. Its material substances belong to a physical description; the organism’s ongoing living activity is what Cook interprets through the etheric; enjoying a smell or disliking a taste illustrates inward experience; deciding to make space for another person at the table illustrates an individual intention. The example separates the questions but does not prove the proposed spiritual members. This distinction is essential later: saying that a food affects the etheric means attributing an effect within this model, not merely saying that it contains energy or that someone enjoyed it.'
],[
'Quatro perguntas sobre uma pessoa',
'O modelo quádruplo fica mais claro quando cada termo responde a uma pergunta diferente. Corpo físico trata da existência material. Corpo etérico nomeia a organização proposta que sustenta a forma viva no crescimento e na renovação. Corpo astral nomeia a experiência interior, como apetite, prazer e aversão. O Eu diz respeito ao indivíduo que pode assumir uma posição consciente diante da experiência. São atividades que se interpenetram numa pessoa, não quatro objetos empilhados dentro do corpo.',
'Considere uma refeição conhecida. Suas substâncias pertencem à descrição física; a atividade vital contínua é o que Cook interpreta pelo etérico; gostar de um aroma ou rejeitar um sabor exemplifica experiência interior; decidir acolher outra pessoa à mesa exemplifica intenção individual. O exemplo distingue perguntas, mas não prova os membros espirituais propostos. Isso será essencial adiante: dizer que um alimento afeta o etérico é atribuir um efeito dentro desse modelo, não apenas afirmar que contém energia ou que alguém gostou dele.'
]),
u([4],'Foodwise · Chapter 4 · PDF 80–95',[
'Read a cereal through form, cultivation and use',
'Cook’s grain portraits connect three kinds of description. First comes the visible plant: roots, stem, leaves and the arrangement of its seed-bearing parts. Next comes its life with people: where it grows, how it is harvested and how its grain is processed. Finally come myth and planetary correspondence, through which Cook interprets its character. A comparison is incomplete if it records only the planet and forgets the plant and the work.',
'For example, compare a whole grain, its milled flour and a cooked dish. The starting plant is related to all three, but the physical form, preparation time and culinary use differ. Cook’s attention to milling and polishing asks what changes along that journey. Her Sun association for wheat is an interpretive characterization, not an extra ingredient in flour. Keep a two-column notebook: observable or documented properties on one side, the author’s symbolic interpretation on the other. Then explain why she connects them, rather than treating the columns as interchangeable facts.'
],[
'Leia um cereal pela forma, pelo cultivo e pelo uso',
'Os retratos dos cereais ligam três tipos de descrição. Primeiro vem a planta visível: raízes, caule, folhas e disposição das partes que produzem sementes. Depois sua vida com as pessoas: onde cresce, como é colhida e como o grão é processado. Por fim aparecem mito e correspondência planetária, pelos quais Cook interpreta seu caráter. Uma comparação fica incompleta quando anota apenas o planeta e esquece a planta e o trabalho.',
'Compare, por exemplo, um grão integral, sua farinha e um prato cozido. A planta de origem relaciona os três, mas forma física, tempo de preparo e uso culinário diferem. A atenção de Cook à moagem e ao polimento pergunta o que muda nesse percurso. Associar trigo ao Sol é uma caracterização interpretativa, não um ingrediente extra da farinha. Faça duas colunas: propriedades observáveis ou documentadas de um lado e interpretação simbólica da autora do outro. Explique então por que ela as relaciona, sem tratá-las como fatos intercambiáveis.'
]),
u([5],'Foodwise · Chapter 5 · PDF 97–113',[
'Why receiving food is not the same as assimilating it',
'Cook places eating alongside breathing and sense perception as ways of meeting the environment. Her underlying question is how something outside a person becomes part of that person’s life. With food, the stages include encounter through smell and taste, chewing, digestive breakdown and the body’s subsequent use of what it receives. She adds a spiritual interpretation: the organism must transform the food’s own organization rather than simply carry it inward unchanged.',
'Use the distinction between a delivery and its use. Bringing ingredients into a kitchen does not yet make a meal; work must reorganize them. This original analogy helps explain why Cook emphasizes transformation, but a kitchen is not a physiological model of digestion. Similarly, the pleasure of a calm meal describes experience and setting; it cannot establish every claim she makes about breathing, feelings and illness. Follow the actual sequence in the chapter, then mark exactly where the explanation moves from bodily process to formative activity or psychological interpretation.'
],[
'Por que receber alimento não é o mesmo que assimilá-lo',
'Cook coloca alimentação, respiração e percepção sensorial como modos de encontro com o ambiente. A pergunta de fundo é como algo externo passa a integrar a vida da pessoa. Na alimentação, as etapas incluem cheiro e sabor, mastigação, decomposição digestiva e uso posterior do que o organismo recebe. Ela acrescenta uma interpretação espiritual: o organismo precisa transformar a organização própria do alimento, em vez de simplesmente transportá-la intacta para dentro.',
'Distinga entrega e utilização. Levar ingredientes à cozinha ainda não produz uma refeição; o trabalho precisa reorganizá-los. Essa analogia original ajuda a explicar a ênfase na transformação, mas a cozinha não é um modelo fisiológico da digestão. Do mesmo modo, o prazer de uma refeição tranquila descreve experiência e ambiente; não demonstra todas as afirmações sobre respiração, sentimentos e doença. Acompanhe a sequência do capítulo e marque onde a explicação passa do processo corporal à atividade formativa ou à interpretação psicológica.'
]),
u([6],'Foodwise · Chapter 6 · PDF 114–126',[
'Separate the reasons before evaluating a dietary choice',
'Arguments about vegetarianism can answer different questions: how animals are treated, how land is used, how a diet is composed, or how Cook believes food relates to consciousness. Agreement with one argument does not automatically establish the others. Her discussion of farm animals makes this concrete: milk, manure, grazing, breeding and the fate of surplus animals belong to a connected farming arrangement. Removing one product from a menu does not by itself explain how that whole arrangement should change.',
'Imagine two people choosing the same vegetarian dish. One is concerned with animal suffering; the other is following a spiritual interpretation of plant food. Their action looks similar, but the reasons and evidence they would need differ. A careful explanation names the aim, traces the consequences being claimed, and considers practical circumstances. It avoids turning food choices into a scale of spiritual worth. For nutritional adequacy, use the contemporary sources already linked in this lesson rather than assuming that an ethical or spiritual argument supplies a complete diet plan.'
],[
'Separe os motivos antes de avaliar uma escolha alimentar',
'Os argumentos sobre vegetarianismo respondem a perguntas diferentes: como os animais são tratados, como a terra é usada, como uma dieta é composta ou como Cook relaciona alimento e consciência. Concordar com um argumento não comprova os outros. A discussão dos animais de criação torna isso concreto: leite, esterco, pastagem, reprodução e destino dos animais excedentes pertencem a um conjunto agrícola. Retirar um produto do cardápio, sozinho, não explica como transformar esse conjunto.',
'Imagine duas pessoas escolhendo o mesmo prato vegetariano. Uma preocupa-se com sofrimento animal; outra segue uma interpretação espiritual dos vegetais. A ação parece semelhante, mas motivos e evidências necessárias diferem. Uma explicação cuidadosa identifica o objetivo, acompanha as consequências alegadas e considera as circunstâncias práticas. Não transforma escolhas alimentares numa escala de valor espiritual. Para adequação nutricional, consulte as fontes atuais da lição, sem presumir que um argumento ético ou espiritual forneça um plano alimentar completo.'
]),
u([7],'Foodwise · Chapter 7 · PDF 128–135',[
'How the plant–human comparison is constructed',
'Begin with the plant’s differentiated activities: anchoring and taking up materials at the root, the leaf region’s relation to air and light, and flowering and fruiting. Cook connects these regions with the human nerve-sense, rhythmic and metabolic-limb systems. The comparison depends on relationships between activities, not on a claim that a root resembles a human head in outward shape. This is why the image of an inverted plant appears in the discussion.',
'To understand a correspondence, write the intermediate step. “Root → head” is only a label. A fuller account asks which quality Cook sees in the root, how she interprets the human pole, and why she relates them. Then distinguish that proposed relationship from a recommendation to eat a particular vegetable. The recommendation would need additional justification. Comparing a carrot, a cabbage leaf and a fruit can train observation of plant parts without requiring learners to believe that each food treats its corresponding human system.'
],[
'Como se constrói a comparação entre planta e ser humano',
'Comece pelas atividades diferenciadas da planta: fixação e absorção na raiz, relação das folhas com ar e luz, floração e frutificação. Cook relaciona essas regiões aos sistemas humanos neurossensorial, rítmico e metabólico-motor. A comparação depende de relações entre atividades, não da afirmação de que uma raiz tenha a aparência de uma cabeça humana. Por isso surge a imagem da planta invertida.',
'Para compreender uma correspondência, escreva o passo intermediário. “Raiz → cabeça” é apenas um rótulo. Uma explicação desenvolvida pergunta qual qualidade Cook identifica na raiz, como interpreta o polo humano e por que os relaciona. Distinga então essa relação proposta de uma recomendação de consumo: esta exigiria justificativa adicional. Comparar cenoura, folha de repolho e fruto pode treinar a observação das partes vegetais sem exigir a crença de que cada alimento trate seu sistema humano correspondente.'
]),
u([8],'Foodwise · Chapter 8 · PDF 136–141',[
'A substance and the food that carries it',
'Cook moves from the formation of carbohydrates in plants to the different foods and sweeteners in which people encounter them. The distinction to keep is between a class of substances and a complete food. Naming carbohydrate does not yet describe texture, water, other constituents, processing or the way an ingredient is used. Her interest in concentration asks what has been separated from its earlier setting.',
'Compare a piece of fruit with a sweetening ingredient used in a recipe. Ask what work produced each, what quantity the recipe uses, and what else is present in the food. This comparison makes processing visible without collapsing every example into “natural good, manufactured bad.” Cook’s interpretation of vitality is a further question. Explain the preparation and composition first; then identify the additional meaning she assigns to them. A description of origin alone does not settle an ingredient’s nutritional role.'
],[
'Uma substância e o alimento que a contém',
'Cook passa da formação dos carboidratos nas plantas aos alimentos e adoçantes em que as pessoas os encontram. A distinção importante é entre uma classe de substâncias e um alimento completo. Nomear carboidrato ainda não descreve textura, água, outros componentes, processamento ou uso culinário. Seu interesse pela concentração pergunta o que foi separado do contexto anterior.',
'Compare uma fruta e um ingrediente adoçante usado numa receita. Pergunte qual trabalho produziu cada um, que quantidade entra na receita e o que mais está presente no alimento. A comparação torna o processamento visível sem reduzir tudo a “natural bom, industrial ruim”. A interpretação da vitalidade é outra pergunta. Explique primeiro preparo e composição; depois identifique o significado adicional atribuído pela autora. Descrever apenas a origem não resolve o papel nutricional de um ingrediente.'
]),
u([9],'Foodwise · Chapter 9 · PDF 142–149',[
'Why time is an ingredient in the argument about bread',
'Cook follows bread through grain growing, harvesting, milling, fermentation and baking. Her criticism of accelerated production concerns stages that used to take time and can be shortened or replaced. The argument is therefore about a process, not simply a contrast between brown and white loaves. Fermentation is especially important to her account because the dough changes while the baker waits; waiting is part of making, rather than an absence of work.',
'Draw a timeline for the loaf described in the chapter. Put each intervention beside the change it is intended to produce. Then compare two timelines: if one is shorter, which stage has changed and what evidence would show its consequences? This is more informative than assuming that every slow method is automatically superior. Cook also treats sharing bread as a social bond. The material transformation of dough and the human significance of sharing it are connected themes, but one does not prove all the claims made about the other.'
],[
'Por que o tempo participa do argumento sobre o pão',
'Cook acompanha o pão pelo cultivo, colheita, moagem, fermentação e cozimento. Sua crítica à produção acelerada trata de etapas que exigiam tempo e podem ser abreviadas ou substituídas. O argumento é sobre um processo, não apenas sobre pão escuro e branco. A fermentação importa porque a massa se transforma enquanto a pessoa espera; esperar faz parte da produção, não é ausência de trabalho.',
'Desenhe uma linha do tempo para o pão descrito no capítulo. Ao lado de cada intervenção, registre a transformação pretendida. Compare dois percursos: se um é mais curto, qual etapa mudou e que evidência mostraria suas consequências? Isso esclarece mais do que presumir que todo método lento seja superior. Cook também trata o pão compartilhado como vínculo social. A transformação material da massa e o significado humano de partilhá-la são temas relacionados, mas um não comprova todas as afirmações sobre o outro.'
]),
u([10],'Foodwise · Chapter 10 · PDF 150–156',[
'Family resemblance does not erase differences',
'Cook groups potatoes, tomatoes, peppers and other plants within the nightshade family, then interprets their form and chemistry through her spiritual account. A botanical family tells us about relationship; it does not make every member or every part of a plant equivalent. A fruit, a tuber and a leaf have different places in plant development. The chapter becomes easier to follow when these distinctions remain visible.',
'Make a record with four separate entries: named species, part discussed, preparation or use, and the effect the author claims. This prevents a statement about one plant from silently becoming a statement about the entire family. It also reveals when the argument changes from description to a claim about thought or temperament. Those claims require their own support. The educational task is to reconstruct Cook’s reasoning accurately, not to prescribe exclusions or experiment with unfamiliar plant parts.'
],[
'O parentesco não elimina as diferenças',
'Cook reúne batata, tomate, pimentão e outras plantas na família das solanáceas e interpreta forma e química por sua concepção espiritual. Uma família botânica informa parentesco; não torna todos os membros ou todas as partes equivalentes. Fruto, tubérculo e folha ocupam lugares distintos no desenvolvimento vegetal. O capítulo fica mais claro quando essas diferenças permanecem visíveis.',
'Registre quatro informações separadas: espécie, parte discutida, preparo ou uso e efeito alegado pela autora. Isso impede que uma afirmação sobre uma planta passe silenciosamente a valer para toda a família. Também revela quando a descrição se transforma numa afirmação sobre pensamento ou temperamento, que exige sustentação própria. O objetivo é reconstruir o raciocínio de Cook com precisão, não prescrever exclusões alimentares nem experimentar partes vegetais desconhecidas.'
]),
u([11],'Foodwise · Chapter 11 · PDF 157–162',[
'The bean links the field and the kitchen',
'This chapter places legumes in two settings. In cultivation, Cook discusses their relationship with nitrogen and crop rotation. At the table, she considers their use alongside grains and other foods. The connection is that a food plant participates in the conditions of future production as well as in the present meal. Her discussion of soya then adds a third scale: what happens when one crop becomes a major commercial commodity.',
'Distinguish a plant from its products and its production system. Whole beans, a fermented food and a processed ingredient can come from the same crop while involving different transformations. Likewise, describing one crop’s role in a rotation does not describe every large-scale planting of it. Cook adds a spiritual association between nitrogen and sentient life; that association is distinct from the field relationships she describes. A strong explanation can trace farm, processing and meal without treating a symbolic correspondence as a measured agricultural mechanism.'
],[
'O feijão liga o campo à cozinha',
'O capítulo situa as leguminosas em dois contextos. No cultivo, Cook discute nitrogênio e rotação de culturas. À mesa, considera seu uso junto a cereais e outros alimentos. A conexão é que a planta alimentícia participa das condições da produção futura e da refeição presente. A discussão da soja acrescenta outra escala: o que acontece quando um cultivo se torna grande mercadoria comercial.',
'Distinga planta, produtos e sistema de produção. Grãos inteiros, alimento fermentado e ingrediente processado podem vir do mesmo cultivo por transformações diferentes. Da mesma forma, explicar a função de uma planta numa rotação não descreve todo plantio em grande escala. Cook acrescenta a associação espiritual entre nitrogênio e vida sensível; ela é distinta das relações agrícolas descritas. Uma boa explicação acompanha campo, processamento e refeição sem tratar correspondência simbólica como mecanismo agrícola medido.'
]),
u([12],'Foodwise · Chapter 12 · PDF 163–172',[
'Milk as food, relationship and symbol',
'Cook’s discussion moves between milk’s place in animal husbandry, the products made from it and its symbolic relationship with continuity and belonging. These levels explain why the chapter begins with cultural images rather than a nutrient table. Within the anthroposophical account she presents, milk has a particular relationship to earthly life and shared humanity. Understanding that claim requires keeping its spiritual meaning distinct from the composition of a particular dairy product.',
'Trace a product from animal to table: care of the animal, collection, processing, storage and use. At each stage a new practical question arises. The cultural meaning of milk cannot answer every question about individual tolerance or handling. Conversely, a processing description cannot explain why a community associates milk with welcome or continuity. Learn to give both accounts without merging them. The lesson’s contemporary food-safety sources remain the reference for practical safety, rather than the chapter’s symbolic language.'
],[
'Leite como alimento, relação e símbolo',
'Cook passa da criação dos animais aos produtos derivados do leite e à sua relação simbólica com continuidade e pertencimento. Esses níveis explicam a abertura por imagens culturais, em vez de uma tabela nutricional. Na concepção antroposófica apresentada, o leite tem relação específica com a vida terrestre e a humanidade compartilhada. Compreender essa afirmação exige distinguir significado espiritual e composição de um produto concreto.',
'Acompanhe um produto do animal à mesa: cuidado, coleta, processamento, armazenamento e uso. Cada etapa levanta uma pergunta prática. O significado cultural do leite não responde a todas as questões sobre tolerância individual ou manejo. Por outro lado, a descrição do processamento não explica por que uma comunidade associa leite a acolhimento ou continuidade. Aprenda a apresentar as duas descrições sem fundi-las. As fontes atuais da lição orientam a segurança prática; a linguagem simbólica do capítulo não as substitui.'
]),
u([13],'Foodwise · Chapter 13 · PDF 173–180',[
'From an observable quality to an interpretation',
'Cook begins with qualities of fats and oils, such as their relation to water and their different consistencies, and connects them with warmth. She then extends warmth into an account of the soul’s relation to bodily life. Follow the extension carefully: observing an oily droplet is one step, explaining a bodily function is another, and interpreting warmth spiritually is another. The shared word does not make the steps identical.',
'Olive oil also lets her connect food with a landscape and a culinary culture. Imagine an ingredient that appears in many family dishes: its significance includes repeated practices and memories, not just its molecular description. This helps explain her interest in oil as a cultural bond. It does not make familiarity a test of nutritional suitability. Compare the physical property, the culinary use and the attributed spiritual meaning separately before explaining how the author brings them together.'
],[
'Da qualidade observável à interpretação',
'Cook parte de qualidades das gorduras e óleos, como relação com água e consistências diferentes, e as liga ao calor. Depois amplia calor para explicar a relação entre alma e vida corporal. Acompanhe a passagem: observar uma gota oleosa é uma etapa; explicar uma função corporal é outra; interpretar espiritualmente o calor é outra. Usar a mesma palavra não torna as etapas idênticas.',
'O azeite permite ainda relacionar alimento, paisagem e cultura culinária. Imagine um ingrediente presente em muitos pratos familiares: seu significado inclui práticas e lembranças repetidas, além da descrição molecular. Isso esclarece o interesse de Cook pelo óleo como vínculo cultural. Não transforma familiaridade em teste de adequação nutricional. Compare propriedade física, uso culinário e significado espiritual atribuído separadamente antes de explicar como a autora os reúne.'
]),
u([14],'Foodwise · Chapter 14 · PDF 181–186',[
'Why salt carries several meanings',
'The chapter links salt’s use in preservation with images of permanence, covenant and social value. The reasoning is understandable: a substance that helps food endure can become a symbol of an enduring relationship. But the symbol is a cultural development, not an additional chemical property. Cook then relates salt to taste and consciousness, moving again from a practical use toward an interpretation of human experience.',
'Use three questions to keep the account clear. What task does salt perform in the example? What meaning does a community attach to that task? What further claim does the author make about human life? Answering the first does not automatically establish the third. A historical practice of preservation cannot determine an individual’s appropriate intake. Study the source’s proposed connections on paper; the chapter’s deprivation scenario is not a learner experiment.'
],[
'Por que o sal carrega vários sentidos',
'O capítulo relaciona conservação pelo sal a imagens de permanência, aliança e valor social. O raciocínio é compreensível: uma substância que ajuda o alimento a durar pode simbolizar uma relação duradoura. Mas o símbolo é uma construção cultural, não uma propriedade química adicional. Cook relaciona depois sal, paladar e consciência, passando novamente do uso prático à interpretação da experiência humana.',
'Use três perguntas: que função o sal exerce no exemplo? Que significado uma comunidade atribui a essa função? Que afirmação adicional a autora faz sobre a vida humana? Responder à primeira não comprova automaticamente a terceira. Uma prática histórica de conservação não determina o consumo adequado de uma pessoa. Estude no papel as conexões propostas; o cenário de privação descrito no capítulo não é um experimento para estudantes.'
]),
u([15],'Foodwise · Chapter 15 · PDF 187–196',[
'What a comparison of food quality must actually compare',
'Cook asks whether changes in farming and processing have changed the quality of food. To understand the question, separate several meanings of quality: measurable constituents, taste and keeping properties, cultivation conditions, and the vitality she interprets anthroposophically. A finding about one meaning does not automatically measure the others. Her historical tables and reports should be read with their dates and methods in view.',
'Imagine comparing two records labelled “carrot.” Before explaining a difference, ask whether variety, place, maturity, storage and measurement method are comparable. Otherwise a numerical difference may be attributed to farming when several conditions changed. This is a reasoning exercise, not a dismissal of the question. It helps locate what evidence would make Cook’s concern more precise. Adding a supplement is yet another question: identifying a concern about food quality does not by itself establish a deficiency in a particular person.'
],[
'O que uma comparação de qualidade alimentar precisa comparar',
'Cook pergunta se mudanças no cultivo e no processamento alteraram a qualidade alimentar. Distinga os sentidos de qualidade: componentes medidos, sabor e conservação, condições de cultivo e vitalidade interpretada antroposoficamente. Um resultado num sentido não mede automaticamente os demais. Leia tabelas e relatos históricos com atenção às datas e aos métodos.',
'Imagine comparar dois registros chamados “cenoura”. Antes de explicar uma diferença, pergunte se variedade, local, maturação, armazenamento e método de medição são comparáveis. Caso contrário, pode-se atribuir ao cultivo uma diferença numérica ocorrida com várias condições modificadas. Esse exercício não descarta a pergunta: ajuda a precisar a evidência necessária. Acrescentar um suplemento é outra questão; identificar uma preocupação com qualidade alimentar não estabelece, por si só, uma deficiência numa pessoa.'
]),
u([16],'Foodwise · Chapter 16 · PDF 197–207',[
'A small ingredient can have a large cultural history',
'Herbs and spices connect the sensory details of a dish with trade, cultivation and cultural memory. Cook asks the reader to attend to the plant part being used: bark, seed, leaf, root or flower. This makes the ingredient more specific than the general label “spice.” She also interprets aromatic qualities within her account of plant activity, so the chapter moves between botanical description, culinary experience and attributed effects.',
'Consider cinnamon bark and a clove flower bud as a reading comparison. Identify the part, describe the use reported in the chapter, and then name the interpretation Cook adds. A strong aroma can explain why a small amount changes a dish, but sensory intensity is not evidence that an ingredient treats an illness. Likewise, a history of medicinal use records a tradition; it does not establish every modern therapeutic claim. Keep the exercise focused on understanding the ingredient and the author’s reasoning.'
],[
'Um pequeno ingrediente pode ter uma grande história cultural',
'Ervas e especiarias ligam detalhes sensoriais de um prato a comércio, cultivo e memória cultural. Cook pede atenção à parte utilizada: casca, semente, folha, raiz ou flor. Isso especifica o ingrediente além do rótulo geral “especiaria”. Ela interpreta também qualidades aromáticas por sua concepção da atividade vegetal; assim, o capítulo transita entre botânica, experiência culinária e efeitos atribuídos.',
'Compare, na leitura, a casca da canela e o botão floral do cravo. Identifique a parte, descreva o uso relatado e nomeie a interpretação acrescentada por Cook. Um aroma forte esclarece por que uma pequena quantidade modifica um prato, mas intensidade sensorial não comprova tratamento de doença. Do mesmo modo, uma história de uso medicinal registra tradição, sem estabelecer toda alegação terapêutica atual. Concentre o exercício na compreensão do ingrediente e do raciocínio da autora.'
]),
u([17],'Foodwise · Chapter 17 · PDF 208–213',[
'An immediate effect and a cultivated capacity',
'Cook’s discussion of stimulants asks what happens when a person uses a substance to obtain a desired state. In the coffee example she presents an anthroposophical explanation of a changed relation between physical and etheric organization. The philosophical issue underneath is the difference between producing an immediate state and developing a capacity that a person can exercise independently.',
'Imagine a writer who feels more ready to work after a familiar drink. Three questions remain separate: what the writer reports feeling, whether the writing becomes clearer, and whether the spiritual mechanism Cook describes explains the change. One report cannot answer all three. Her concern about a “crutch” should be understood as a question about dependence on conditions, not as proof of the mechanism. Use an ordinary task example to reason about attention; experimenting with substances is not part of the lesson.'
],[
'Um efeito imediato e uma capacidade cultivada',
'Cook pergunta o que acontece quando uma pessoa usa uma substância para alcançar um estado desejado. No exemplo do café, apresenta a explicação antroposófica de uma relação modificada entre organização física e etérica. A questão filosófica é a diferença entre produzir um estado imediato e desenvolver uma capacidade exercida com independência.',
'Imagine alguém que se sente mais preparado para escrever depois de uma bebida habitual. Separe três perguntas: o que relata sentir, se a escrita ficou mais clara e se o mecanismo espiritual de Cook explica a mudança. Um relato não responde às três. Sua preocupação com uma “muleta” é uma pergunta sobre dependência de condições, não prova do mecanismo. Use uma tarefa cotidiana para refletir sobre atenção; experimentar substâncias não faz parte da lição.'
]),
u([18],'Foodwise · Chapter 18 · PDF 214–215',[
'Water as material condition and interpretive image',
'Cook treats water both as part of ordinary nourishment and as a carrier of qualities in her wider account of life. The lesson requires attention to which meaning is active. The movement, source or appearance of water can be described; claims about its vitality or memory add another explanatory level. Attractive language about living water should not obscure what is actually being claimed.',
'Imagine comparing two descriptions of a stream: one records its source and movement, while the other interprets its character. Both can guide attention, but neither appearance nor a feeling of freshness establishes whether water is safe to drink. Separate observation, interpretation and the practical decision. This gives the chapter a usable reading method without making its metaphors into tests of water quality. The contemporary water-safety reference in the lesson addresses that separate practical question.'
],[
'Água como condição material e imagem interpretativa',
'Cook trata a água como parte da nutrição cotidiana e como portadora de qualidades em sua concepção da vida. Observe qual sentido está ativo. Movimento, origem e aparência podem ser descritos; afirmações sobre vitalidade ou memória acrescentam outro nível explicativo. A linguagem atraente da água viva não deve ocultar o que está sendo afirmado.',
'Imagine duas descrições de um riacho: uma registra origem e movimento; outra interpreta seu caráter. Ambas podem orientar a atenção, mas aparência e sensação de frescor não estabelecem potabilidade. Separe observação, interpretação e decisão prática. Esse método permite ler o capítulo sem transformar metáforas em testes de qualidade. A referência atual sobre segurança da água, incluída na lição, responde a essa pergunta prática distinta.'
]),
u([19],'Foodwise · Chapter 19A · PDF 217–228',[
'A menu is a sequence of decisions for particular people',
'Menu planning connects the earlier food portraits to a real situation. Begin with who will eat, what they can use, what resources are available and how the work can be done. Only then choose dishes. Cook adds attention to colour, rhythm and the character of ingredients. These can shape a composition, but they do not remove the need to consider the people at the table.',
'For an original example, plan a shared lunch with one cooker and limited time. A beautiful list of dishes fails if every dish needs the same pan at the same moment. Work backward from serving: identify what can be prepared earlier and who does each task. Then explain how your choices express a principle from the book. A planetary grain scheme can be studied as one interpretive arrangement; Cook’s acknowledgment of differing assignments is a reason to understand its purpose rather than treat it as an unquestionable timetable.'
],[
'Um cardápio é uma sequência de decisões para pessoas concretas',
'Planejar um cardápio liga os retratos anteriores dos alimentos a uma situação real. Comece por quem comerá, o que pode consumir, os recursos disponíveis e a organização do trabalho. Só então escolha os pratos. Cook acrescenta atenção a cor, ritmo e caráter dos ingredientes. Esses aspectos compõem a refeição, mas não dispensam considerar as pessoas à mesa.',
'Planeje, por exemplo, um almoço compartilhado com um fogão e pouco tempo. Uma bela lista fracassa se todos os pratos exigem a mesma panela no mesmo instante. Parta do horário de servir e retroceda: o que pode ser preparado antes e quem faz cada tarefa? Explique como suas escolhas expressam um princípio do livro. O esquema planetário dos cereais pode ser estudado como organização interpretativa; as divergências reconhecidas por Cook pedem compreender sua finalidade, sem tratá-lo como calendário indiscutível.'
]),
u([20],'Foodwise · Chapter 19B · PDF 229–245',[
'Explain what each cooking step changes',
'A recipe becomes teaching when the learner can explain its sequence. Ask what each step changes in the ingredients, why that change is wanted, and why the next step comes afterward. Cook’s discussion of fire places cooking within a larger theme: human work transforms what nature provides. The cultural meaning of transformation becomes concrete in the cook’s decisions about preparation and timing.',
'Take a complete recipe from your own copy and annotate its verbs: cut, mix, heat, rest, cool. Compare the intended result before and after each action. If a step is omitted, explain which part of the result might change rather than merely saying the recipe is wrong. Some captured recipe passages are incomplete, so do not reconstruct missing quantities from guesses. This exercise can be done entirely on paper; it assesses understanding of method rather than possession of a particular kitchen or set of ingredients.'
],[
'Explique o que cada etapa de preparo modifica',
'Uma receita ensina quando a pessoa consegue explicar sua sequência. Pergunte o que cada etapa modifica, por que essa mudança é desejada e por que a etapa seguinte vem depois. A discussão do fogo situa a cozinha num tema maior: o trabalho humano transforma o que a natureza oferece. O significado cultural da transformação concretiza-se nas decisões de preparo e tempo.',
'Escolha uma receita completa em seu exemplar e anote os verbos: cortar, misturar, aquecer, repousar, esfriar. Compare o resultado pretendido antes e depois de cada ação. Se uma etapa for omitida, explique o que pode mudar, em vez de apenas dizer que a receita está errada. Alguns trechos capturados estão incompletos; não invente quantidades ausentes. O exercício pode ser feito no papel e avalia compreensão do método, não acesso a determinada cozinha ou ingredientes.'
]),
u([21],'Foodwise · Chapter 19C · PDF 245–254',[
'Rhythm means a dependable relationship, not a perfect household',
'Cook’s account of shared meals concerns repeated occasions in which people can meet. A rhythm differs from a rigid rule: it gives an activity a recognizable place in life while allowing adaptation to circumstances. Her family examples connect timing with conversation, memory and a sense of belonging. Within her spiritual vocabulary she interprets this continuity through the etheric life of the family.',
'Imagine a household whose members work different hours. Requiring every meal together could produce conflict; a predictable weekly meal might better express the principle of dependable meeting. Ask who prepares, who is heard and who is excluded by the arrangement. These details explain how a rhythm becomes a lived relationship. They also prevent an idealized family picture from becoming a moral judgment on other households. Cook’s wider claims about illness need separate assessment; the social value of a welcoming meal does not prove them.'
],[
'Ritmo significa relação confiável, não família perfeita',
'A refeição compartilhada, em Cook, oferece ocasiões repetidas de encontro. Ritmo difere de regra rígida: dá à atividade um lugar reconhecível na vida, permitindo adaptação. Seus exemplos familiares ligam horário, conversa, memória e pertencimento. Em seu vocabulário espiritual, essa continuidade é interpretada pela vida etérica da família.',
'Imagine pessoas que trabalham em horários diferentes. Exigir todas as refeições em conjunto poderia gerar conflito; um encontro semanal previsível talvez expressasse melhor o princípio. Pergunte quem prepara, quem é ouvido e quem fica excluído. Esses detalhes explicam como o ritmo se torna relação vivida e impedem que uma imagem familiar idealizada vire julgamento moral. As afirmações mais amplas de Cook sobre doença precisam de avaliação separada; o valor social de uma refeição acolhedora não as comprova.'
]),
u([22,23],'Foodwise · Chapter 20 and synthesis · PDF 255–257; return to Chapters 2 and 19',[
'Build a chain from understanding to a feasible action',
'Cook ends by asking whether our way of obtaining and preparing food supports our ability to turn intentions into action. Her spiritual explanation concerns the vitality of food and the relation between thinking and will. The practical challenge can be examined without assuming that explanation is established: what would change in a real meal if its participants took cultivation, preparation and shared responsibility seriously?',
'Choose one manageable decision and trace its consequences. For example, planning a seasonal shared dish connects a grower, an ingredient, a method, a budget and people’s needs. Explain one link at a time and identify a tradeoff. A portfolio is stronger when it shows why a choice fits these conditions than when it collects approving phrases from many chapters. Finish with a review question: what would you observe after trying the plan, and what result would make you revise it? This keeps the book’s call to responsibility connected to learning rather than a claim of having found the perfect diet.'
],[
'Construa uma sequência da compreensão à ação possível',
'Cook termina perguntando se nosso modo de obter e preparar alimentos sustenta a passagem da intenção à ação. Sua explicação espiritual envolve vitalidade alimentar e relação entre pensamento e vontade. O desafio prático pode ser examinado sem presumir essa explicação comprovada: o que mudaria numa refeição real se os participantes considerassem seriamente cultivo, preparo e responsabilidade compartilhada?',
'Escolha uma decisão viável e acompanhe suas consequências. Planejar um prato sazonal compartilhado, por exemplo, liga produtor, ingrediente, método, orçamento e necessidades pessoais. Explique cada ligação e reconheça uma dificuldade. Um portfólio é mais forte quando mostra por que a escolha cabe nas condições do que quando coleciona frases de aprovação. Termine perguntando o que observaria após experimentar o plano e qual resultado levaria à revisão. Assim, o chamado à responsabilidade permanece ligado à aprendizagem, sem alegar uma dieta perfeita.'
])
];
