const u=(routes,source,en,pt)=>({routes,source,en,pt});
const units=[
u({theosophy:[0,22],foundations:[1,18]},'Theosophy · Introduction and Chapters I–IV',[
'How the book’s four questions build on one another',
'The first chapter asks what a human being is; the second asks what persists through a life and, in Steiner’s account, across lives; the third describes the worlds in which that development is said to occur; the fourth asks how knowledge of them could be approached. The later chapters depend on distinctions introduced earlier. If soul means only emotion, for example, the soul-world account becomes unintelligible because desire, sensation and attachment also belong to the term.',
'Read the course as a chain of questions rather than a vocabulary list. For each new term, write the problem it is intended to answer and its relation to an earlier term. “Etheric” answers a question about living organization; “astral” adds a question about inward experience. A clear explanation can therefore show why a new distinction enters the argument. Understanding that chain is the first learning outcome; deciding whether its spiritual premises are established remains a further inquiry.'
],[
'Como as quatro perguntas do livro se encadeiam',
'O primeiro capítulo pergunta o que é o ser humano; o segundo, o que permanece na vida e, segundo Steiner, entre vidas; o terceiro descreve os mundos desse desenvolvimento; o quarto pergunta como conhecer tais mundos. Os capítulos posteriores dependem das distinções anteriores. Se alma significar apenas emoção, por exemplo, o mundo anímico fica incompreensível, pois desejo, sensação e apego também pertencem ao termo.',
'Leia o curso como encadeamento de perguntas, não lista de palavras. Para cada termo, registre o problema que pretende responder e sua relação com outro. “Etérico” responde à organização viva; “astral” acrescenta experiência interior. Uma explicação clara mostra por que surge cada distinção. Compreender essa sequência é o primeiro resultado da aprendizagem; avaliar suas premissas espirituais é uma investigação adicional.'
]),
u({foundations:[2]},'Theosophy · Introduction; The Philosophy of Freedom · Chapters 3–5',[
'An observation becomes knowledge through a relation',
'Suppose two leaves on a plant turn toward the window. Recording their position is an observation. Saying they changed because of light introduces an explanation. To examine it, one must consider the earlier position, the interval and other conditions, rather than merely repeat the observed result. Thinking contributes the proposed relation, and further observation can help determine whether that relation fits.',
'This distinction does not divide life into a pure sensory world and an unrelated world of ideas. It identifies different contributions within knowing. A concept helps us ask what to notice; what we notice can require us to revise the concept’s application. In spiritual-scientific texts, an additional claim may concern a mode of perception beyond ordinary senses. Identify that step explicitly so that a familiar example of ordinary inquiry is not mistaken for verification of the further claim.'
],[
'A observação se torna conhecimento por uma relação',
'Suponha duas folhas voltadas para a janela. Registrar a posição é observação. Dizer que mudaram por causa da luz introduz explicação. Para examiná-la, considere posição anterior, intervalo e outras condições, além de repetir o resultado. O pensamento contribui com a relação proposta; novas observações ajudam a verificar seu ajuste.',
'A distinção não separa um mundo sensorial puro de ideias sem relação com ele. Identifica contribuições diferentes no conhecer. Um conceito orienta o que observar; a observação pode exigir rever sua aplicação. Textos de ciência espiritual acrescentam por vezes uma percepção além dos sentidos comuns. Identifique esse passo para não tomar um exemplo familiar de investigação como verificação da afirmação adicional.'
]),
u({theosophy:[1,2],foundations:[3]},'Theosophy · Chapter I · body, soul and spirit',[
'One encounter, three relationships',
'Imagine hearing a melody played by another person. The bodily relationship includes the instrument, the sound and the conditions of hearing. The soul relationship includes the pleasure, irritation or memory that belongs to this listener’s experience. The spiritual relationship, in the opening argument, concerns an intelligible relation that can be understood beyond private liking: for example, how a repeated phrase is varied. The melody is not divided into three unrelated events; one encounter is approached through three questions.',
'Two listeners may disagree about whether they enjoy the melody while understanding the same relation between its phrases. That contrast helps explain why Steiner distinguishes personal experience from a claim to truth. It does not mean that every thought is true or that feeling is an obstacle to knowledge. The bodily instrument, inward participation and search for intelligible order operate together. Soul also includes sensation and willing, so it cannot be replaced by the narrower word emotion.'
],[
'Um encontro, três relações',
'Imagine ouvir uma melodia tocada por outra pessoa. A relação corporal inclui instrumento, som e condições da audição. A relação anímica inclui prazer, irritação ou lembrança próprios de quem ouve. A relação espiritual, no argumento inicial, envolve algo inteligível além do gosto pessoal: por exemplo, como uma frase musical se repete com variação. A melodia não se divide em três eventos separados; um encontro é abordado por três perguntas.',
'Duas pessoas podem discordar sobre gostar da música e compreender a mesma relação entre frases. Isso esclarece a distinção entre experiência pessoal e pretensão de verdade. Não significa que todo pensamento seja verdadeiro ou que sentir impeça conhecer. Instrumento corporal, participação interior e busca de ordem inteligível atuam juntos. Alma também inclui sensação e vontade, não podendo ser substituída pela palavra mais estreita emoção.'
]),
u({foundations:[4]},'Theosophy · Chapter I; foundation comparison of human activities',[
'Thinking, feeling and willing within the same action',
'A neighbour asks for help moving a table. Thinking can understand the task and consider how to move it; feeling can register sympathy, reluctance or concern; willing enters as you take up and carry through an action. These activities interact. Understanding a danger may alter a feeling; concern may direct attention toward a detail; acting may reveal something the first plan missed.',
'This is a distinction among activities, while body, soul and spirit names broader relationships in Steiner’s account. There is no simple conversion in which thinking equals spirit, feeling equals soul and willing equals body. Thinking is itself experienced inwardly and carried out under bodily conditions; willing can be guided by an understood purpose. Try describing all three activities in one action before comparing them with other threefold accounts. The shared number three is not evidence that the accounts classify the same thing.'
],[
'Pensar, sentir e querer na mesma ação',
'Um vizinho pede ajuda para mover uma mesa. Pensar compreende a tarefa e considera o modo de realizá-la; sentir registra simpatia, relutância ou preocupação; querer participa ao iniciar e sustentar a ação. As atividades interagem. Compreender um perigo pode mudar o sentimento; preocupar-se dirige atenção a um detalhe; agir revela algo que o plano não previa.',
'Essa distinção trata de atividades, enquanto corpo, alma e espírito nomeiam relações mais amplas. Não há conversão simples em que pensar seja espírito, sentir seja alma e querer seja corpo. Pensar é vivido interiormente sob condições corporais; querer pode orientar-se por finalidade compreendida. Descreva as três atividades numa ação antes de compará-las a outras tríades. O número três, sozinho, não demonstra que as descrições classifiquem a mesma coisa.'
]),
u({theosophy:[3],foundations:[5]},'Theosophy · Chapter I · physical and life organization',[
'Why a living form is more than an inventory of materials',
'An inventory identifies the materials present at a moment. A living-form description follows an organization through change: a plant takes up materials, produces new leaves and maintains a recognizable pattern while its contents change. Steiner introduces the etheric or life body to explain this continuity of formative activity. It is not another visible substance poured into the physical body, and it is not simply a second name for the observed growth.',
'Compare a pile of plant material with the growing plant from which it came. Similar materials do not amount to the same organized activity. This makes the explanatory question clear. Steiner’s answer adds a supersensible organization; the observed contrast does not by itself select that answer over every other explanation. His later distinction of sensation adds another question: a plant’s development and an animal’s inward pleasure or pain are not the same kind of description. The progression is material embodiment, living organization, then sentient experience.'
],[
'Por que a forma viva ultrapassa um inventário de materiais',
'Um inventário identifica materiais presentes num momento. A descrição da forma viva acompanha organização através da mudança: a planta recebe materiais, produz folhas e mantém um padrão reconhecível enquanto seu conteúdo muda. Steiner introduz o corpo etérico ou vital para explicar a continuidade formativa. Não é outra substância visível acrescentada ao corpo nem apenas novo nome para o crescimento observado.',
'Compare restos vegetais e a planta em crescimento de onde vieram. Materiais semelhantes não equivalem à mesma atividade organizada. Isso esclarece a pergunta. A resposta de Steiner acrescenta organização suprassensível; o contraste observado não a seleciona sozinho entre todas as explicações. A sensação acrescenta outra pergunta: desenvolvimento vegetal e prazer ou dor interior não são descrições do mesmo tipo. A progressão é existência material, organização viva e experiência sensível.'
]),
u({theosophy:[5],foundations:[6,10]},'Theosophy · Chapter I · the I and spiritual transformation',[
'Having an experience and taking a position toward it',
'Hunger is an experience; noticing that hunger is affecting a decision adds a reflective relationship to it. In Steiner’s fourfold account, the astral member concerns sentience and desire, while the I names the individual centre that can increasingly work upon its own life. The distinction does not mean that the I is absent whenever a person feels strongly. It concerns how inward experience can become material for conscious self-direction.',
'The later terms spirit self, life spirit and spirit man describe a proposed transformation of astral, etheric and physical organization through the I. They are not three additional personalities. Nor should every ordinary improvement be announced as attainment of one of these spiritual states. An example such as learning to pause before responding illustrates the relation between a tendency and work upon it. The book extends that relation into a much larger account of spiritual development, which must be read on its own terms.'
],[
'Ter uma experiência e posicionar-se diante dela',
'Fome é experiência; perceber que ela influencia uma decisão acrescenta relação reflexiva. Na descrição quádrupla, o membro astral envolve sensibilidade e desejo; o Eu nomeia o centro individual capaz de trabalhar crescentemente sobre a própria vida. Isso não significa ausência do Eu quando alguém sente intensamente. Trata de como a experiência interior se torna matéria de orientação consciente.',
'Manas, Budhi e Atma — também chamados Si espiritual, Espírito de vida e Homem-espírito — descrevem transformação proposta das organizações astral, etérica e física pelo Eu. Não são três personalidades extras. Tampouco cada melhora cotidiana significa atingir um desses estados. Aprender a pausar antes de responder exemplifica a relação entre tendência e trabalho sobre ela. O livro amplia essa relação numa concepção espiritual que precisa ser lida em seus próprios termos.'
]),
u({foundations:[7]},'Foundation course · threefold bodily organization',[
'A functional emphasis is not an isolated compartment',
'The nerve-sense, rhythmic and metabolic-limb accounts distinguish kinds of activity within the bodily whole. Sense perception and relatively still attention characterize one pole; movement and transformative activity characterize another; rhythmic processes mediate. The head, chest and limbs provide useful spatial orientations, but the functions do not stop at borders between body regions.',
'Consider walking while listening to another person. Movement, breathing, perception and attention occur together. Naming one activity does not remove the others or locate the whole experience in one organ. This matters when later chapters compare a plant’s root, leaf and flowering regions with human activities. First understand the functional relationship being proposed; do not turn an illustrative correspondence into a map of separate containers. This threefold account also answers a different question from body, soul and spirit.'
],[
'Ênfase funcional não significa compartimento isolado',
'As organizações neurossensorial, rítmica e metabólico-motora distinguem atividades no conjunto corporal. Percepção e atenção relativamente imóvel caracterizam um polo; movimento e transformação, outro; processos rítmicos fazem mediação. Cabeça, tórax e membros orientam espacialmente, mas as funções não terminam nas fronteiras entre regiões.',
'Pense em caminhar ouvindo alguém. Movimento, respiração, percepção e atenção ocorrem juntos. Nomear uma atividade não elimina as outras nem localiza a experiência inteira num órgão. Isso importa nas comparações posteriores entre raiz, folha e floração e atividades humanas. Compreenda a relação funcional proposta, sem transformar correspondência ilustrativa em mapa de recipientes separados. Essa tríade também responde a uma pergunta diferente de corpo, alma e espírito.'
]),
u({theosophy:[6],foundations:[8]},'Theosophy · Chapter I · ninefold and sevenfold accounts',[
'Why changing the grouping changes the count',
'The ninefold presentation distinguishes physical body, etheric body, soul body, sentient soul, intellectual soul, consciousness soul, spirit self, life spirit and spirit man. The list follows distinctions the chapter has introduced, rather than naming nine spatial layers. To obtain the related sevenfold presentation, soul body and sentient soul are considered together, and consciousness soul and spirit self are considered together. Two pairings reduce nine entries to seven.',
'The fourfold account asks a broader organizing question about physical, etheric, astral and I. It cannot be reconstructed by arbitrarily deleting five terms from the ninefold list. Write the purpose of each classification before comparing its entries: what is being distinguished, joined or described as transformed? An ordinary analogy is one activity described by its materials, its functions or its stages. Different counts can be meaningful, but the relationship between them must be explained rather than assumed from familiar words.'
],[
'Por que mudar o agrupamento muda a contagem',
'A apresentação nônupla distingue corpo físico, corpo etérico, corpo anímico, alma da sensação, alma do intelecto, alma da consciência, Si espiritual, Espírito de vida e Homem-espírito. A lista acompanha distinções do capítulo, não nove camadas espaciais. Na apresentação sétupla relacionada, corpo anímico e alma da sensação são considerados juntos, assim como alma da consciência e Si espiritual. Duas uniões reduzem nove entradas a sete.',
'A descrição quádrupla pergunta de modo mais amplo por físico, etérico, astral e Eu. Não resulta de apagar arbitrariamente cinco termos da lista. Escreva a finalidade de cada classificação: o que distingue, reúne ou descreve como transformado? Uma analogia comum é descrever uma atividade por materiais, funções ou etapas. Contagens diferentes podem ter sentido, mas sua relação precisa ser explicada, não presumida pelas palavras familiares.'
]),
u({theosophy:[4],foundations:[9]},'Theosophy · Chapter I · differentiations of soul',[
'From immediate response to a judgment that can be examined',
'The sentient soul concerns the inward reception of sensation and desire. The intellectual or mind soul brings experience into thought and relationship. The consciousness soul emphasizes a relation to truth that is not determined merely by personal sympathy or advantage. These are distinctions within inner life, not three kinds of people and not a ranking of someone’s worth.',
'Suppose a colleague corrects a date you have written. The immediate sting belongs to your experienced response. Considering what the colleague meant and comparing the two dates engages reflective activity. Checking the calendar and accepting the result even when it is unwelcome illustrates the movement toward a judgment that is not settled by liking. All these moments may overlap. The example helps explain the distinctions; it does not assign a soul category to the person or imply that feeling must disappear before truth becomes accessible.'
],[
'Da resposta imediata ao juízo examinável',
'A alma da sensação envolve recepção interior de sensação e desejo. A alma do intelecto relaciona a experiência pelo pensamento. A alma da consciência enfatiza verdade não determinada apenas por simpatia ou vantagem pessoal. São distinções na vida interior, não três tipos de pessoas nem classificação de valor humano.',
'Suponha que alguém corrija uma data escrita por você. O incômodo imediato pertence à resposta vivida. Considerar a intenção da pessoa e comparar datas mobiliza reflexão. Conferir o calendário e aceitar o resultado indesejado exemplifica um juízo não decidido pelo gosto. Esses momentos podem sobrepor-se. O exemplo esclarece distinções; não classifica a alma de ninguém nem exige eliminar sentimentos para alcançar a verdade.'
]),
u({theosophy:[7,13],foundations:[11]},'Theosophy · Chapters II and III · memory and capacity',[
'Remembering a lesson differs from being able to use it',
'You may remember the afternoon when someone taught you to ride a bicycle. You may also retain the ability to ride without recalling that afternoon. The remembered episode and the acquired capacity are different results of experience. A later action can show what became ability even when the original learning event is no longer present in awareness.',
'Steiner uses this distinction to approach a larger account of how experience becomes lasting spiritual capacity. The ordinary example gives the distinction an intelligible starting point; the proposed continuation between lives is an additional claim. Keep the steps visible: event, inward experience, work upon the experience and a changed capacity. In a study notebook, do not only list what you read. Show something you can now explain or do differently, and identify the process that helped. This makes the relationship between experience and transformation concrete.'
],[
'Lembrar uma lição difere de saber utilizá-la',
'Você pode lembrar a tarde em que aprendeu a andar de bicicleta e conservar a habilidade sem recordar aquela tarde. Episódio lembrado e capacidade adquirida são resultados diferentes da experiência. Uma ação posterior mostra a habilidade mesmo quando o acontecimento inicial não está presente à consciência.',
'Steiner usa a distinção para explicar como experiência se tornaria capacidade espiritual duradoura. O exemplo comum oferece ponto de partida compreensível; a continuação entre vidas é afirmação adicional. Preserve as etapas: acontecimento, experiência interior, trabalho sobre ela e capacidade modificada. No caderno, não liste apenas leituras. Mostre algo que agora explica ou faz diferentemente e o processo que ajudou. Isso concretiza a relação entre experiência e transformação.'
]),
u({theosophy:[8,14],foundations:[13]},'Theosophy · Chapters II and III · repeated lives and individuality',[
'What the reincarnation argument needs to establish',
'The book distinguishes bodily inheritance, the course of personal experience and spiritual individuality. Similarity to family members can account for some features without, in Steiner’s argument, exhausting the individual’s whole direction and capacities. He proposes a continuing spiritual biography, with each life taking up and transforming results of earlier lives. The claim concerns continuity through transformation, not the repetition of an unchanged social personality.',
'An unusual talent or a strong inclination does not by itself demonstrate that biography. To reconstruct the reasoning, separate the observation from the premises about a spiritual individuality and its persistence. The account of preparation for another life then asks how capacities and purposes are related to new circumstances. It does not authorize a learner to infer someone’s supposed past from wealth, disability, suffering or success. The explanatory model must be understood without converting uncertainty about another person into an invented karmic story.'
],[
'O que o argumento da reencarnação precisa estabelecer',
'O livro distingue herança corporal, experiência pessoal e individualidade espiritual. Semelhanças familiares explicam aspectos sem, no argumento de Steiner, esgotar direção e capacidades individuais. Ele propõe biografia espiritual contínua, na qual cada vida recebe e transforma resultados anteriores. A afirmação envolve continuidade através da transformação, não repetição de uma personalidade social imutável.',
'Talento incomum ou inclinação forte não demonstra sozinho essa biografia. Separe a observação das premissas sobre individualidade espiritual e persistência. A preparação para outra vida pergunta como capacidades e propósitos se relacionam com novas circunstâncias. Não autoriza inferir um passado de riqueza, deficiência, sofrimento ou sucesso. Compreenda o modelo sem transformar desconhecimento sobre alguém em história cármica inventada.'
]),
u({theosophy:[9],foundations:[14]},'Theosophy · Chapter II · action and destiny',[
'Consequences connect actions without making every future choice fixed',
'An action changes a situation. A promise can create an expectation; breaking it can change another person’s trust; that changed relationship becomes a condition for a later encounter. This ordinary chain helps distinguish consequence from an isolated event. Karma extends the relation between action and destiny beyond one life in Steiner’s account, while reincarnation concerns the continuing individuality. The concepts are related but answer different questions.',
'Fatalism would mean that the response to a situation is already fixed regardless of understanding or action. A consequence can instead create a task to which different responses remain possible. Repairing a broken promise may require acknowledgment, practical restitution and changed conduct; merely wishing the consequence away is not the same as responding freely. The example explains a relationship within one life. It does not establish the cross-life extension or justify saying that a person caused or deserved a hardship whose history we do not know.'
],[
'Consequências ligam ações sem fixar toda escolha futura',
'Uma ação modifica a situação. Prometer cria expectativa; descumprir pode alterar confiança; a relação modificada torna-se condição de outro encontro. Essa sequência distingue consequência e evento isolado. Carma amplia a relação entre ação e destino para além de uma vida; reencarnação trata da individualidade contínua. São conceitos relacionados que respondem a perguntas diferentes.',
'Fatalismo significaria resposta já fixada, independentemente de compreensão ou ação. Uma consequência pode criar uma tarefa com respostas possíveis. Reparar uma promessa exige talvez reconhecimento, reparação prática e conduta diferente; desejar que a consequência desapareça não equivale a responder livremente. O exemplo esclarece uma relação numa vida. Não comprova sua ampliação entre vidas nem permite afirmar que alguém causou ou mereceu uma dificuldade de história desconhecida.'
]),
u({theosophy:[10,11],foundations:[15]},'Theosophy · Chapter III · soul world and purification',[
'Sympathy and antipathy describe relationships, not moral labels',
'In the soul-world account, sympathy draws toward another experience or being, while antipathy separates or holds a boundary. Steiner describes regions through different relations between these tendencies. Sympathy is therefore not simply the everyday word for kindness, and antipathy is not merely hostility. The question is how strongly experience remains centred on its own desire and how it relates to what is beyond that desire.',
'Purification concerns desires whose satisfaction depended on bodily conditions that are no longer available in the account after death. Imagine the structure of a habit that still asks for its familiar object when the situation has changed. The example makes dependence intelligible, but the book’s post-mortem account is more than an everyday habit exercise. Explain the attachment, the missing means of satisfaction and the proposed release. This also distinguishes purification of desire from karma’s wider relation between deeds and destiny.'
],[
'Simpatia e antipatia descrevem relações, não rótulos morais',
'No mundo anímico, simpatia aproxima de outra experiência ou ser; antipatia separa ou mantém limite. Steiner descreve regiões por relações diferentes entre essas tendências. Simpatia não é simplesmente bondade cotidiana; antipatia não é apenas hostilidade. A pergunta é quanto a experiência permanece centrada no próprio desejo e como se relaciona com o que está além dele.',
'Purificação trata de desejos cuja satisfação dependia de condições corporais indisponíveis após a morte, nessa descrição. Imagine a estrutura de um hábito que continua pedindo seu objeto quando a situação mudou. Isso torna a dependência compreensível, mas o relato pós-morte ultrapassa o exercício cotidiano. Explique apego, ausência dos meios de satisfação e liberação proposta. Distinga também purificação do desejo e relação mais ampla entre atos e destino no carma.'
]),
u({theosophy:[12],foundations:[16]},'Theosophy · Chapter III · spiritland',[
'An archetype is presented as formative activity',
'The word archetype can suggest a fixed model sitting somewhere before an object is made. Steiner’s spiritland account instead describes living, formative relationships from which the sensible world is understood to arise. His use of regions and landscape-like language organizes the account, but it is not meant as a map of another physical country with ordinary distances.',
'A building plan is a limited analogy. It helps distinguish an intelligible organization from the finished materials, yet a paper plan is passive while the spiritual archetypes are described as active. State both the similarity and this important difference. The successive regions broaden the kind of formative relationship considered. Read each by asking what it organizes and how that differs from the previous region, rather than memorizing a place-name. This prepares the later account of how experience is transformed into capacities for another life.'
],[
'O arquétipo é apresentado como atividade formativa',
'Arquétipo pode sugerir modelo fixo existente antes de um objeto. O mundo espiritual de Steiner descreve, ao contrário, relações formativas vivas das quais o mundo sensível procederia. Regiões e linguagem de paisagem organizam o relato, mas não pretendem mapear outro país físico com distâncias comuns.',
'A planta de um edifício é analogia limitada. Distingue organização inteligível e materiais prontos, mas o desenho é passivo, enquanto os arquétipos são descritos como ativos. Explicite semelhança e diferença. As regiões sucessivas ampliam o tipo de relação formativa considerado. Pergunte o que cada região organiza e como difere da anterior, em vez de memorizar nomes. Isso prepara a explicação posterior da transformação de experiência em capacidades para outra vida.'
]),
u({theosophy:[15,16]},'Theosophy · Chapter III · nature and spiritual beings',[
'Several descriptions of nature are not several disconnected natures',
'Steiner relates mineral, plant, animal and human existence to physical, soul and spiritual worlds. The point is not that an object leaves one world whenever we describe it in another way. A visible form, the inward experience attributed to a being and the formative spiritual relationships proposed behind it belong to different questions about one interconnected existence.',
'The later discussion of collective and elemental beings extends that account to activities larger or smaller than an individual human biography. Keep the subject of each claim explicit. A shared purpose in a village can be described through people’s actions; the claim of a spiritual being associated with a collective adds another kind of explanation. The ordinary social description neither proves nor fully paraphrases that claim. A concept map should use verbs—expresses, participates, forms, experiences—so the learner can explain relationships instead of merely arranging spiritual names into boxes.'
],[
'Várias descrições da natureza não significam naturezas desconectadas',
'Steiner relaciona existência mineral, vegetal, animal e humana aos mundos físico, anímico e espiritual. Um objeto não abandona um mundo quando é descrito por outro aspecto. Forma visível, experiência interior atribuída e relações espirituais formativas respondem a perguntas diferentes sobre existência interligada.',
'Os seres coletivos e elementais ampliam essa descrição para atividades maiores ou menores que uma biografia humana. Mantenha explícito o sujeito de cada afirmação. Uma finalidade comunitária pode ser descrita por ações humanas; afirmar um ser espiritual associado acrescenta outra explicação. A descrição social comum não prova nem traduz inteiramente essa afirmação. Use verbos no mapa conceitual — expressa, participa, forma, vivencia — para explicar relações, além de distribuir nomes espirituais em caixas.'
]),
u({theosophy:[17]},'Theosophy · Chapter III · thought forms and aura',[
'Colour words can describe different kinds of experience',
'“Red paint,” “a warm voice” and “red in an aura description” do not automatically name the same kind of thing. The first refers to a visible material appearance; the second uses a sensory quality to characterize an experience; the third belongs to Steiner’s claimed supersensible perception. He uses familiar colour language to communicate a quality while distinguishing it from ordinary physical seeing.',
'A careful explanation identifies which sense is intended before drawing conclusions. A painted diagram can help organize the relationships in the text, but it is not a photograph of an aura or a test of character. The account also describes changing relations within inner life, so a fixed colour label cannot stand for a whole person. Explain the state or activity the passage associates with its colour, how it relates to other qualities and what mode of perception the author claims for that description.'
],[
'Palavras de cor podem descrever experiências diferentes',
'“Tinta vermelha”, “voz calorosa” e “vermelho numa descrição da aura” não nomeiam automaticamente o mesmo tipo de coisa. A primeira é aparência material visível; a segunda usa qualidade sensorial para caracterizar experiência; a terceira pertence à percepção suprassensível alegada. Steiner usa cores familiares para comunicar qualidades, distinguindo-as da visão física.',
'Identifique o sentido antes de concluir. Um diagrama pintado organiza relações do texto, mas não é fotografia da aura ou teste de caráter. O relato também trata de relações interiores mutáveis; um rótulo cromático fixo não representa a pessoa inteira. Explique a atividade ou estado associado à cor, sua relação com outras qualidades e o modo de percepção que o autor reivindica.'
]),
u({theosophy:[18,19,20],foundations:[17]},'Theosophy · Chapter IV · the path of knowledge',[
'Receptivity and judgment can be practised together',
'Receptivity means making enough room to understand a claim before reducing it to a familiar reaction. Judgment means examining how its reasons support it. These are successive and cooperating tasks, not a choice between unquestioning acceptance and instant dismissal. Steiner’s path chapter asks for disciplined thought, feeling and conduct because the person who investigates is also the instrument of the proposed investigation.',
'Take an unfamiliar explanation. First restate it so that its author would recognize the intended relationships. Next reconstruct the steps and identify what each depends on. Then ask whether the premises and transitions are supported. If irritation appears, notice it without making it the argument; if enthusiasm appears, do not let that replace examination either. A change in a premise should lead to a change in the conclusion where the reasoning requires it. This ordinary practice clarifies the discipline being requested without promising supersensible results.'
],[
'Receptividade e julgamento podem ser exercidos juntos',
'Receptividade abre espaço para compreender uma afirmação antes de reduzi-la à reação habitual. Julgamento examina como as razões a sustentam. São tarefas sucessivas e cooperantes, não escolha entre aceitação cega e rejeição imediata. O capítulo pede disciplina de pensamento, sentimento e conduta porque quem investiga é também instrumento da investigação proposta.',
'Diante de uma explicação incomum, reformule-a preservando as relações pretendidas. Reconstrua depois as etapas e suas dependências. Examine então premissas e passagens. Se surgir irritação, perceba-a sem transformá-la em argumento; se surgir entusiasmo, não o use no lugar da análise. Uma premissa modificada deve alterar a conclusão quando o raciocínio exigir. Essa prática comum esclarece a disciplina solicitada, sem prometer resultados suprassensíveis.'
]),
u({theosophy:[21],foundations:[12]},'Theosophy · Chapter IV; The Philosophy of Freedom · ethical individuality',[
'A free action needs a reason and a way to become real',
'Having alternatives is not yet the whole question of freedom. A person may choose under fear, habit or borrowed authority without understanding the reason that moves them. The philosophical account asks whether the individual can grasp the motive and make it their own through insight. The practical question then asks how that insight becomes an action in a particular situation.',
'Imagine wanting to help a neighbour. Sympathy alone does not specify what help is needed; a general rule does not tell you every detail; technical skill alone does not decide the purpose. You must understand the situation, form a concrete possibility and consider its effects on the other person. A novel action can still be impulsive, while a familiar action can be deliberately understood. The criterion is not unusualness. Explain motive, practical realization and responsibility together, preserving the other person’s freedom as well as your own.'
],[
'Uma ação livre precisa de motivo e de realização concreta',
'Ter alternativas não esgota a liberdade. Pode-se escolher por medo, hábito ou autoridade emprestada sem compreender o motivo. A descrição filosófica pergunta se o indivíduo apreende o motivo e o assume por compreensão. A pergunta prática é como essa compreensão se torna ação numa situação concreta.',
'Imagine querer ajudar um vizinho. Simpatia não define a necessidade; regra geral não resolve todos os detalhes; habilidade técnica não decide a finalidade. É preciso compreender a situação, criar uma possibilidade concreta e considerar efeitos sobre o outro. Uma ação nova pode ser impulsiva; uma habitual pode ser compreendida deliberadamente. O critério não é originalidade. Explique motivo, realização e responsabilidade juntos, preservando também a liberdade alheia.'
])
];
export const humanDepth=Object.fromEntries(['theosophy','foundations'].map(course=>[course,units.filter(u=>u.routes[course]).map(({routes,...unit})=>({...unit,ids:routes[course]}))]));
