const u=(ids,source,en,pt)=>({ids,source,en,pt});
export const nutritionDepth=[
u([0,13],'Nutrition · Introduction; Chapters 2, 4, 5 and 9',[
'How to read a collection without inventing one seamless theory',
'A thematic collection places passages beside one another because they address a shared subject. It does not mean they were originally parts of one continuous argument. Steiner speaks to different audiences here, while the editor selects, introduces and arranges his words. For each claim, identify who is speaking, which question the passage addresses and what its terms mean in that setting. This makes comparisons possible without erasing differences.',
'Try comparing the mineral account in Chapter 2 with the statement about salt in Chapter 5. First give each account fairly in its own terms. Next identify the exact point of tension: are the passages discussing material identity, a proposed spiritual process, or both? A possible reconciliation is an interpretation that needs support, not a fact supplied by placing the pages together. The same discipline applies to the two nutrient tables. The final synthesis should show relationships and unresolved questions, rather than forcing every sentence into one chart.'
],[
'Como ler uma coletânea sem inventar uma teoria sem diferenças',
'Uma coletânea temática aproxima passagens porque tratam de um assunto comum. Isso não significa que fossem partes de um argumento contínuo. Steiner fala a públicos diferentes; o editor seleciona, apresenta e organiza suas palavras. Em cada afirmação, identifique quem fala, qual pergunta responde e como usa os termos naquele contexto. Isso permite comparar sem apagar diferenças.',
'Compare os minerais no Capítulo 2 com o sal no Capítulo 5. Primeiro explique cada passagem em seus próprios termos. Depois localize a tensão: discutem identidade material, processo espiritual proposto ou ambos? Uma possível conciliação é interpretação que precisa de apoio, não um fato produzido pela aproximação das páginas. O mesmo cuidado vale para as duas tabelas de nutrientes. A síntese deve mostrar relações e perguntas abertas, sem forçar todas as frases a caber numa única tabela.'
]),
u([1,12],'Nutrition · Chapters 1 and 12',[
'The difference between receiving support and developing a capacity',
'The argument begins with a person who wants to act, think or learn. Bodily conditions matter because intentions need an instrument through which to become effective. Steiner then distinguishes a condition that makes an activity temporarily easier from the person’s own developed ability to perform it. In his spiritual account, transforming food is part of that active relationship between individuality and body.',
'Imagine someone who follows a worked solution and someone who can reconstruct why its steps follow. Both may produce the same answer, but their capacities differ. This original example clarifies the educational distinction; it does not prove Steiner’s account of what a food does to thinking. To explain the chapter fully, state the intended activity, the support being supplied and the independent work still required. A change of menu cannot, within the argument, replace the work of understanding or deciding. Nor does the argument justify ranking people’s spiritual development by what they eat.'
],[
'A diferença entre receber apoio e desenvolver uma capacidade',
'O argumento começa com uma pessoa que deseja agir, pensar ou aprender. As condições corporais importam porque a intenção precisa de um instrumento para realizar-se. Steiner distingue uma condição que facilita temporariamente a atividade da capacidade desenvolvida pela própria pessoa. Em sua concepção espiritual, transformar alimento participa dessa relação ativa entre individualidade e corpo.',
'Imagine alguém que segue uma solução pronta e alguém que reconstrói por que as etapas se encadeiam. Ambos podem chegar à mesma resposta, mas suas capacidades diferem. O exemplo esclarece a distinção educativa; não prova a explicação dos efeitos alimentares sobre o pensamento. Nomeie a atividade pretendida, o apoio recebido e o trabalho independente ainda necessário. Uma mudança de cardápio não substitui, nesse argumento, compreender ou decidir. Tampouco autoriza classificar o desenvolvimento espiritual de alguém pela alimentação.'
]),
u([2],'Nutrition · Chapter 2 · PDF 20–30',[
'Transformation is a claim about organization, not merely temperature',
'A substance can change form while retaining a chemical description, and a living organism can use received materials within its own organization. Steiner goes further: he claims that mineral substance passes through warmth ether and receives formative relations from the cosmos. “Warmth ether” therefore cannot be translated simply as food getting warm. Removing that extra claim would make the chapter sound more familiar but would change what it says.',
'The reversed plant image serves this larger account. Outside, root and blossom stand in one relation to earth and surroundings; inside the human being, Steiner proposes a different orientation of their activity. To explain the image, name both arrangements and what is being reversed. Then ask what the image helps you picture and what it leaves unestablished. A diagram can make a proposed relation intelligible, but its clarity does not demonstrate that the relation occurs. Read milk and honey in the same way: identify the claimed formative role before evaluating it.'
],[
'Transformação trata de organização, não apenas de temperatura',
'Uma substância pode mudar de forma mantendo sua descrição química, e um organismo pode utilizar materiais recebidos em sua própria organização. Steiner vai além: afirma que a substância mineral passa pelo éter de calor e recebe relações formativas do cosmos. “Éter de calor” não pode ser traduzido simplesmente como aquecimento do alimento. Eliminar essa afirmação tornaria o capítulo mais familiar, mas mudaria seu conteúdo.',
'A imagem da planta invertida serve a essa explicação. Fora do corpo, raiz e flor relacionam-se de certo modo com terra e ambiente; no ser humano, Steiner propõe outra orientação de sua atividade. Nomeie os dois arranjos e o que se inverte. Pergunte então o que a imagem ajuda a visualizar e o que não estabelece. A clareza de um diagrama torna uma relação compreensível, sem demonstrar sua existência. Leia leite e mel da mesma maneira: identifique a função formativa atribuída antes de avaliá-la.'
]),
u([3],'Nutrition · Chapter 3 · PDF 31–37',[
'Why the chapter pairs spiritual aspiration with earthly responsibility',
'Steiner’s audience is concerned with spiritual development, so his food descriptions address a particular problem: how to become more sensitive without losing the ability to take part in ordinary life. The image of ballast makes sense in that setting. Ballast gives a vessel stability; milk is assigned a comparable grounding role within the lecture’s spiritual picture. The analogy explains the intended balance, not a measurable ingredient called grounding.',
'A similar distinction appears in the discussion of sugar and ego-character. Bodily individuality and selfish moral conduct are not the same meaning of ego. The author proposes that a person can become less self-centred in intention while remaining a distinct, capable individual. Without that distinction the passage can sound like permission to cultivate selfishness. Reconstruct the two levels before reading the substance portraits. Coffee, tea and chocolate then belong to the lecture’s account of differing supports and experiences, not a reliable classification of people by their preferred drink.'
],[
'Por que o capítulo reúne aspiração espiritual e responsabilidade terrestre',
'O público interessa-se por desenvolvimento espiritual; por isso, as descrições alimentares respondem a um problema: ampliar a sensibilidade sem perder participação na vida cotidiana. A imagem do lastro faz sentido nesse contexto. O lastro estabiliza uma embarcação; ao leite atribui-se função semelhante de sustentação na concepção espiritual da palestra. A analogia explica o equilíbrio pretendido, não um ingrediente mensurável chamado enraizamento.',
'Distinção semelhante aparece no açúcar e no caráter do ego. Individualidade corporal e conduta moral egoísta não são o mesmo sentido de ego. O autor propõe diminuir o autocentramento das intenções sem deixar de ser indivíduo distinto e capaz. Sem isso, o trecho pode parecer uma autorização ao egoísmo. Reconstrua os dois níveis antes de ler os retratos das substâncias. Café, chá e chocolate pertencem então à descrição de apoios e experiências, não a uma classificação confiável das pessoas por suas bebidas.'
]),
u([4,9],'Nutrition · Chapters 4 and 9',[
'Two tables answer two different questions',
'In Chapter 4 the organizing question is what counteracts decomposition: protein and putrefaction, fat and rancidity, carbohydrate and fermentation. The proposed counteracting members are etheric, astral and I respectively. In Chapter 9 the question is a member’s principal field of activity: physical with protein, etheric with fats, astral with carbohydrates, I with salts. A row copied without its question loses the relationship it was meant to express.',
'Write the complete sentence before drawing an arrow. “The etheric body counteracts protein putrefaction in Chapter 4” says something different from “the etheric body has fats as its main field in Chapter 9.” Naming the different questions explains why the tables cannot be substituted for one another; it does not prove that both accounts are correct or resolve every tension. The learner’s task is to retain the verb, the context and the attributed claim. Neither table is a physiological nutrient requirement or a tool for diagnosing a person.'
],[
'Duas tabelas respondem a perguntas diferentes',
'No Capítulo 4, a pergunta organizadora é o que contraria a decomposição: proteína e putrefação, gordura e rancidez, carboidrato e fermentação. Os membros contrapostos são, respectivamente, etérico, astral e Eu. No Capítulo 9, a pergunta trata do campo principal de atividade: físico e proteína, etérico e gorduras, astral e carboidratos, Eu e sais. Copiar uma linha sem sua pergunta faz perder a relação que ela expressava.',
'Escreva a frase completa antes de desenhar a seta. “O corpo etérico contraria a putrefação da proteína no Capítulo 4” difere de “as gorduras são seu campo principal no Capítulo 9”. Identificar as perguntas explica por que as tabelas não são substituíveis; não prova a correção de ambas nem resolve toda tensão. Preserve verbo, contexto e autoria da afirmação. Nenhuma tabela determina necessidades nutricionais fisiológicas ou serve para diagnosticar pessoas.'
]),
u([5],'Nutrition · Chapter 5 · PDF 50–56',[
'Follow the proposed chain from cultivation to human activity',
'The lecture’s chain has several links: how soil is treated, how a plant develops, what kind of food results, and what the eater can do with it. Steiner’s manure argument depends on the claim that passage through an animal organism contributes something a chemical description alone misses. A good exposition must name that extra claim, rather than quietly substituting a general preference for gardening or fresh food.',
'Use the watchmaker analogy precisely. Dismantling and rebuilding a watch pictures organized transformation; it does not imply that the organism consciously inspects every molecule like a mechanic. The analogy identifies a question about rebuilding, while the causal explanation still needs its own account. Similarly, noticing a child’s food preference can begin an inquiry but does not determine its cause. Separate the observation from the diagnosis the lecture adds. These distinctions let you understand the agricultural connection deeply while keeping specific medical claims open to independent assessment.'
],[
'Acompanhe a sequência proposta do cultivo à atividade humana',
'A palestra liga tratamento do solo, desenvolvimento vegetal, alimento resultante e atividade de quem o consome. O argumento do esterco depende da afirmação de que passar por um organismo animal acrescenta algo que a descrição química não capta. Uma exposição precisa nomear essa afirmação adicional, sem substituí-la por preferência genérica por jardinagem ou alimentos frescos.',
'Use com precisão a analogia do relojoeiro. Desmontar e reconstruir o relógio representa transformação organizada; não significa que o organismo examine conscientemente cada molécula como um mecânico. A analogia identifica a pergunta sobre reconstrução, mas a explicação causal ainda precisa ser apresentada. Do mesmo modo, perceber uma preferência alimentar infantil inicia uma investigação, sem determinar sua causa. Separe observação e diagnóstico acrescentado pela palestra. Assim, compreende-se a ligação agrícola sem dispensar avaliação independente das afirmações médicas.'
]),
u([6],'Nutrition · Chapter 6 · PDF 57–66',[
'Keep the digestive sequence and its interpretation in view together',
'A sequence explains why order matters. The mouth begins a transformation; the stomach and intestines provide later conditions; secretions enter at particular points. In the lecture, these stages prepare a second account in which inner organs participate in activities described as perception or thinking. The shift of vocabulary is important: an organ’s response and a person’s conscious thought are not being presented as identical experiences.',
'Draw two aligned lines. On the first put the bodily stages named in the reading. On the second put the spiritual or soul activity Steiner associates with each. Where he uses the onion-and-tears comparison, explain the relation he is trying to illuminate rather than treating similarity as a causal demonstration. The result should let another learner say both what happens next in the lecture and why the author thinks the stage matters. For present-day physiological detail, compare the contemporary digestion source rather than silently correcting the historical passage while attributing the correction to Steiner.'
],[
'Mantenha a sequência digestiva e sua interpretação em vista',
'Uma sequência explica por que a ordem importa. A boca inicia a transformação; estômago e intestinos oferecem condições posteriores; secreções entram em momentos específicos. Essas etapas preparam outra descrição, na qual órgãos internos participam de atividades chamadas percepção ou pensamento. A mudança de vocabulário importa: resposta orgânica e pensamento consciente não são apresentados como experiências idênticas.',
'Desenhe duas linhas alinhadas. Na primeira coloque as etapas corporais da leitura; na segunda, a atividade espiritual ou anímica associada. Na comparação entre cebola e lágrimas, explique a relação que Steiner procura iluminar, sem tomar semelhança por demonstração causal. Outra pessoa deve conseguir explicar a sequência e por que cada etapa importa ao autor. Para fisiologia atual, compare a fonte contemporânea indicada, sem corrigir silenciosamente a passagem histórica e atribuir a correção a Steiner.'
]),
u([7],'Nutrition · Chapter 7 · PDF 67–82',[
'More effort is not automatically better',
'The chapter contains a useful complication of the idea that inner work strengthens. Grinding and heating perform work outside the body, and Steiner does not therefore reject all cooking. The issue is the relation between the food’s demands and the organism’s capacity. A principle about activity cannot be converted into a rule that the greatest possible difficulty is always desirable.',
'Use an original learning comparison: a task that is too easy may teach little, while one far beyond a learner’s preparation may prevent useful work. Appropriate support makes a different kind of participation possible. This explains the form of the argument, not the medical effects of any diet. Then return to the actual foods and qualifications in the source. Keep the later animal-feeding hypothesis separate from the editor’s BSE comparison: the proposed mechanism, the editorial interpretation and the contemporary explanation are three distinct accounts.'
],[
'Mais esforço não é automaticamente melhor',
'O capítulo complica a ideia de que o trabalho interno fortalece. Moagem e aquecimento realizam trabalho fora do corpo, e Steiner nem por isso rejeita todo cozimento. A questão é a relação entre exigência do alimento e capacidade do organismo. Um princípio sobre atividade não pode virar regra de que a maior dificuldade possível seja sempre desejável.',
'Compare com aprendizagem: uma tarefa fácil demais pode ensinar pouco, enquanto outra muito além da preparação pode impedir trabalho produtivo. O apoio adequado permite outra participação. Isso explica a forma do argumento, não efeitos médicos de uma dieta. Retorne aos alimentos e às qualificações reais da fonte. Separe a hipótese posterior sobre alimentação animal da comparação editorial com BSE: mecanismo proposto, interpretação do editor e explicação contemporânea são três descrições distintas.'
]),
u([8],'Nutrition · Chapter 8 · PDF 83–86',[
'Supplying material and eliciting activity are different explanations',
'The strongest claim in this lecture is not merely that digestion changes food. Steiner says earthly food stimulates a formative process through which the human being is renewed from etheric surroundings. If we paraphrase that only as “the body uses nutrients,” we remove the very point that makes the claim distinctive. Understanding requires preserving its proposed source of renewal as well as its account of the stimulus.',
'A question can stimulate someone to think without supplying the finished thought. That original analogy clarifies the difference between a stimulus and the activity it elicits. It does not establish that food has the cosmic role claimed here. Similarly, the inner-armchair image distinguishes the support from the one supported; it is not an anatomical picture. Explain each image’s relationship first, then identify the extra premises needed to transfer that relationship to bodily renewal. Botanical distinctions among root, tuber and flower do not establish the claimed mental effects on their own.'
],[
'Fornecer material e suscitar atividade são explicações diferentes',
'A afirmação mais forte da palestra não é apenas que a digestão modifica o alimento. Steiner diz que a comida terrestre estimula um processo formativo pelo qual o ser humano se renova a partir do ambiente etérico. Traduzir isso apenas por “o corpo utiliza nutrientes” elimina justamente sua característica central. Preserve a origem proposta da renovação e a função atribuída ao estímulo.',
'Uma pergunta pode estimular alguém a pensar sem fornecer o pensamento pronto. Essa analogia esclarece a diferença entre estímulo e atividade suscitada; não estabelece o papel cósmico atribuído à alimentação. Do mesmo modo, a poltrona interior distingue apoio e pessoa apoiada, sem representar anatomia. Explique a relação de cada imagem e identifique as premissas adicionais necessárias para aplicá-la à renovação corporal. Distinguir botanicamente raiz, tubérculo e flor não comprova seus supostos efeitos mentais.'
]),
u([10,11],'Nutrition · Chapters 10 and 11',[
'A chain of consequences needs more than a striking first link',
'The alcohol and nicotine lectures both move from an immediate effect to a proposed disturbance of wider bodily relations. Alcohol is discussed through stimulation, discomfort and renewed stimulation; nicotine through a proposed relationship between circulation and breathing. In each case, understanding the argument means following how one claimed change is supposed to lead to the next, not merely memorizing a warning.',
'Take one chain and mark its steps as reported experience, numerical model, bodily mechanism or social conclusion. A four-to-one ratio, for example, describes the lecture’s model; it does not diagnose an individual. Likewise, a concern about substitution under prohibition is a policy question, not a demonstration of all the preceding physiology. This method allows a fair reading while locating where independent evidence is needed. Do not use the lecture’s proposed exceptions as self-treatment advice. The lesson’s contemporary health sources address the practical risks separately.'
],[
'Uma sequência de consequências exige mais que um primeiro elo marcante',
'As palestras sobre álcool e nicotina passam do efeito imediato à perturbação proposta de relações corporais mais amplas. O álcool aparece na sequência estímulo, desconforto e novo estímulo; a nicotina, na relação proposta entre circulação e respiração. Compreender exige acompanhar como uma mudança alegada levaria à seguinte, além de memorizar uma advertência.',
'Escolha uma sequência e classifique suas etapas como experiência relatada, modelo numérico, mecanismo corporal ou conclusão social. A proporção de quatro para um descreve o modelo da palestra; não diagnostica um indivíduo. A preocupação com substituições sob proibição é uma questão de política, não demonstração da fisiologia anterior. Esse método permite leitura justa e localiza a necessidade de evidência independente. As exceções propostas não orientam autotratamento; as fontes atuais da lição tratam separadamente dos riscos práticos.'
])
];
