const u=(ids,source,en,pt)=>({ids,source,en,pt});
export const phasesDepth=[
u([0,18],'Phases · Introduction and final synthesis',[
'A biography is more than a list of milestones',
'A chronology tells us what happened and when. A biography asks how events were received, what changed through them and what possibilities remained. Lievegoed’s leitmotiv is a proposed thread through these changes. It is not simply a profession or a repeated event. Someone’s concern with helping others understand might appear in teaching, repairing equipment, parenting or translating between colleagues.',
'To identify a possible thread, compare several episodes and explain the relationship instead of selecting only the episodes that fit. An interruption may change the form of a contribution or challenge the whole interpretation. Separate event, response and retrospective meaning in your notes. Two people can experience a similar event and respond differently; one person can understand an earlier event differently later. A final portfolio should therefore include a counterexample and an alternative reading. Coherence becomes a reasoned interpretation of a life, not a destiny discovered by making every event fit a pleasing story.'
],[
'Uma biografia é mais que uma lista de marcos',
'A cronologia informa o que aconteceu e quando. A biografia pergunta como os acontecimentos foram recebidos, o que mudou e que possibilidades permaneceram. O leitmotiv de Lievegoed é um fio proposto entre essas mudanças, não simplesmente profissão ou acontecimento repetido. O interesse em ajudar outros a compreender pode aparecer no ensino, no conserto de equipamentos, na criação dos filhos ou na mediação entre colegas.',
'Compare episódios e explique sua relação, sem selecionar apenas os que combinam. Uma interrupção pode transformar uma contribuição ou desafiar a interpretação inteira. Separe acontecimento, resposta e significado retrospectivo. Pessoas respondem diferentemente a eventos semelhantes; alguém pode reinterpretar seu passado mais tarde. Inclua, portanto, um contraexemplo e outra leitura no portfólio. A coerência torna-se interpretação fundamentada, não destino descoberto ao encaixar tudo numa história agradável.'
]),
u([1,3],'Phases · Chapter 1 and Chapter 2 overview',[
'How differentiation and integration produce development',
'Growth adds more of something; development changes the relationship among parts. A group may grow by adding members while keeping the same arrangement. It develops when responsibilities become differentiated and are then coordinated in a new way. Differentiation without integration can fragment the whole; integration without room for difference can suppress what has emerged. Lievegoed uses this pair to explain why development is more than accumulation.',
'Apply the distinction to a person learning to lead a project. Doing more tasks is growth in workload. Learning to delegate, listen and coordinate changes the organization of the activity. Bodily capacity, emotional experience and questions of purpose may change at different rates during this process. That is why the book draws several life lines instead of treating physical growth as a graph of the whole person. The example illustrates the conceptual distinction, not a universal timetable for development.'
],[
'Como diferenciação e integração produzem desenvolvimento',
'Crescer acrescenta quantidade; desenvolver-se modifica relações entre partes. Um grupo cresce ao receber integrantes mantendo a organização. Desenvolve-se quando diferencia responsabilidades e as coordena de outra maneira. Diferenciação sem integração fragmenta; integração sem espaço para diferenças pode sufocar o que surgiu. Esse par explica por que desenvolvimento ultrapassa acumulação.',
'Pense em alguém aprendendo a conduzir um projeto. Executar mais tarefas aumenta a carga. Aprender a delegar, ouvir e coordenar modifica a organização da atividade. Capacidade corporal, experiência emocional e questões de propósito podem mudar em ritmos diferentes. Por isso o livro desenha várias linhas de vida, em vez de tomar crescimento físico como gráfico da pessoa inteira. O exemplo esclarece a distinção conceitual, não estabelece um calendário universal.'
]),
u([2],'Phases · Chapter 1 · PDF 10–26',[
'Use a phase to generate questions, then check the fit',
'A developmental map directs attention toward a possible pattern. It becomes misleading when the pattern is used as the evidence for itself: “this must be a crisis because the person has reached this age.” Lievegoed qualifies his phase ages, so a careful reader begins with what is actually changing and only then asks whether the map illuminates it.',
'Compare two people of the same age, one beginning a new occupation and one caring for a family member. Their outward roles do not tell us which values they are reconsidering or which capacities they are developing. Ask about the transition, the available choices and the meaning each gives it. Then identify both a fit and a mismatch with the proposed phase. The value-centre of a period means that it has its own concerns and significance; it need not be justified solely as preparation for the next stage.'
],[
'Use a fase para formular perguntas e depois verifique o ajuste',
'Um mapa do desenvolvimento chama atenção para um padrão possível. Torna-se enganoso quando usa o padrão como prova de si mesmo: “é uma crise porque a pessoa chegou a essa idade”. Lievegoed qualifica as idades; comece, portanto, pelas mudanças concretas e só depois pergunte se o mapa as esclarece.',
'Compare pessoas da mesma idade: uma inicia uma ocupação; outra cuida de um familiar. Os papéis externos não revelam quais valores reconsideram ou capacidades desenvolvem. Pergunte pela transição, escolhas disponíveis e significado atribuído. Identifique então uma correspondência e uma diferença em relação à fase proposta. O centro de valores de um período significa que ele tem preocupações e importância próprias, sem precisar justificar-se apenas como preparação para a etapa seguinte.'
]),
u([4,5],'Phases · Chapter 2 · adolescence and early adulthood',[
'Experience becomes formative when a person works through it',
'The book’s movement from ideals toward experience is not a demand to abandon ideals. An ideal gives direction; an encounter with real conditions reveals what its realization requires. A young person who wants to help may discover that listening, learning a skill and keeping a promise matter as much as enthusiasm. The ideal is becoming more differentiated through participation.',
'The crucial step is reflection on the encounter. Simply accumulating jobs, journeys or relationships does not guarantee understanding. Ask what the person expected, what happened and how their next judgment changed. A concrete responsibility gives exploration consequences for others, while a protected opportunity to try leaves room for learning. Lievegoed’s conventional examples of adulthood should not become prerequisites for maturity: the relationship between intention, experience and responsibility can develop through many forms of life.'
],[
'A experiência forma quando a pessoa trabalha com ela',
'Passar dos ideais à experiência não significa abandoná-los. O ideal orienta; encontrar condições reais revela o que sua realização exige. Uma pessoa jovem que deseja ajudar pode descobrir a importância de ouvir, aprender uma habilidade e cumprir uma promessa. O ideal se diferencia pela participação.',
'A etapa decisiva é refletir sobre o encontro. Acumular empregos, viagens ou relacionamentos não garante compreensão. Pergunte o que a pessoa esperava, o que aconteceu e como mudou o próximo julgamento. A responsabilidade dá consequências sociais à exploração; uma oportunidade protegida de tentar preserva espaço de aprendizagem. Os exemplos convencionais de vida adulta de Lievegoed não são requisitos de maturidade: intenção, experiência e responsabilidade podem relacionar-se em muitas formas de vida.'
]),
u([6],'Phases · Chapter 2 · organizational phase',[
'A structure should continue to serve its purpose',
'Organization turns repeated effort into something dependable. A schedule, an agreed division of work or a method for keeping promises reduces the need to begin again each day. In Lievegoed’s account, this can express a growing capacity to carry a purpose through changing moods. Structure is therefore an achievement before it becomes a possible limitation.',
'The limitation appears when the arrangement becomes more important than the purpose it served. Imagine a team retaining a procedure that no longer helps its members because it once worked well. The developmental question is not whether all routine is bad, but whether a person can reassess a successful routine. Explain what the structure makes possible, what it now obstructs and what revision would preserve its useful work. This makes the contrast between competence and rigidity concrete without assigning it to everyone of a particular age.'
],[
'Uma estrutura deve continuar servindo à sua finalidade',
'Organizar transforma esforço repetido em algo confiável. Horário, divisão de trabalho ou método para cumprir promessas evita recomeçar diariamente. Em Lievegoed, isso expressa a capacidade de sustentar uma finalidade através de humores variáveis. A estrutura é uma conquista antes de se tornar possível limitação.',
'A limitação surge quando a organização importa mais que sua finalidade. Imagine uma equipe mantendo um procedimento inútil apenas porque funcionou antes. A pergunta não é se toda rotina é ruim, mas se alguém consegue reavaliar uma rotina bem-sucedida. Explique o que a estrutura possibilita, o que impede e qual revisão preservaria sua contribuição. Assim, competência e rigidez tornam-se diferenças concretas, sem atribuí-las a todos numa determinada idade.'
]),
u([7,8],'Phases · Chapter 2 · changing values and midlife direction',[
'A problem of meaning differs from a problem of efficiency',
'Efficiency asks how to reach an accepted aim with the resources available. A crisis of values asks whether that aim still deserves to organize a life. Increasing the target may solve the first kind of problem while avoiding the second. This is why Lievegoed’s successful business example matters: outward achievement can coexist with a question that more achievement of the same kind does not answer.',
'Use a fictional example of someone who has completed a long project and feels uncertain about the next one. Before recommending a dramatic change, distinguish fatigue, external constraints, disappointed expectations and a reconsidered purpose. The book’s interpretation is one possible account, not a diagnosis. A new direction can be tested through a modest commitment: whom would this serve, what capacity would it use, and what would the person learn by trying? An outer opportunity matters when it meets an inward question, rather than functioning as an automatic cure.'
],[
'Problema de sentido difere de problema de eficiência',
'Eficiência pergunta como alcançar uma meta aceita com os recursos disponíveis. Crise de valores pergunta se essa meta ainda merece organizar a vida. Aumentar o objetivo pode resolver o primeiro problema e evitar o segundo. Por isso importa o empresário bem-sucedido de Lievegoed: realização externa pode coexistir com uma pergunta que mais realização do mesmo tipo não responde.',
'Imagine alguém que concluiu um projeto longo e não sabe o que fazer depois. Antes de recomendar mudança radical, distinga cansaço, limites externos, expectativas frustradas e propósito reconsiderado. A interpretação do livro é uma possibilidade, não diagnóstico. Uma direção pode ser testada por compromisso modesto: a quem serviria, que capacidade utilizaria e o que seria aprendido? A oportunidade externa importa ao encontrar uma pergunta interior, sem funcionar como cura automática.'
]),
u([9,10],'Phases · Chapter 2 · later adulthood',[
'Experience becomes a contribution through its use',
'Years of activity can produce knowledge, but the passage of time alone does not make that knowledge useful to another person. Mentoring requires selecting what matters, explaining why it matters and leaving the learner room to judge. Lievegoed’s contrast between protecting status and giving experience a future concerns this change of relationship to one’s own achievements.',
'Imagine an experienced craftsperson preparing a successor. Taking over every difficult task preserves immediate quality but prevents the successor from learning. Giving a task, explaining its purpose and discussing the result can turn personal skill into another person’s growing capacity. Letting go is active work here, not indifference. Later contribution can also take quieter forms, including receiving help and sustaining relationships. The book’s examples of exceptional creativity illustrate possibilities; they do not establish a standard by which to judge someone whose circumstances or capacities differ.'
],[
'A experiência se torna contribuição pelo modo de utilizá-la',
'Anos de atividade podem produzir conhecimento, mas o tempo sozinho não o torna útil a outra pessoa. Orientar exige selecionar o importante, explicar sua importância e deixar espaço para julgamento. A diferença entre proteger posição e dar futuro à experiência trata dessa mudança na relação com as próprias conquistas.',
'Imagine uma pessoa experiente preparando um sucessor. Assumir toda tarefa difícil preserva qualidade imediata, mas impede aprendizagem. Confiar uma tarefa, explicar sua finalidade e conversar sobre o resultado transforma habilidade pessoal em capacidade alheia. Desapegar-se é trabalho ativo, não indiferença. Contribuições posteriores podem ser discretas, inclusive receber ajuda e sustentar relações. A criatividade excepcional citada no livro ilustra possibilidades, sem estabelecer padrão para julgar quem vive condições ou capacidades diferentes.'
]),
u([11],'Phases · Chapter 3 · PDF 62–75',[
'Recognizing projection changes the question you ask',
'Projection means that an image or expectation contributed by oneself is experienced as though it were simply a property of the other person. In a relationship, someone may first seem to embody every hoped-for quality and later every disappointment. Lievegoed asks whether the actual individual can become visible through these changing images. That requires more than replacing a flattering label with an unflattering one.',
'Take a disagreement about a shared task. Separate what was said or done, the meaning each person attributed to it and what each expected beforehand. This can reveal an assumption without deciding that all conflict is imagined or that responsibility is equal in every situation. Meeting the other person includes respecting boundaries and concrete conduct. The book’s gendered categories belong to its historical framework; the useful reading task is to examine how expectations affect understanding without making gender determine an individual’s inner life.'
],[
'Reconhecer a projeção muda a pergunta',
'Projeção ocorre quando uma imagem ou expectativa própria é vivida como simples característica do outro. Num relacionamento, alguém pode primeiro parecer reunir todas as qualidades desejadas e depois todas as decepções. Lievegoed pergunta se o indivíduo real pode tornar-se visível através dessas imagens mutáveis. Isso exige mais que trocar um rótulo elogioso por outro negativo.',
'Num desacordo sobre uma tarefa, separe o que foi dito ou feito, o significado atribuído e as expectativas anteriores. Isso revela pressupostos sem concluir que todo conflito seja imaginário ou que a responsabilidade seja sempre igual. Encontrar o outro inclui respeitar limites e condutas concretas. As categorias de gênero pertencem ao contexto histórico do livro; examine como expectativas afetam a compreensão sem fazer do gênero uma definição da vida interior individual.'
]),
u([12],'Phases · Chapter 4 · PDF 76–81',[
'Orientation, ability, temperament and direction answer different questions',
'Aptitude asks what someone can do. Temperament concerns the manner in which they respond. Orientation describes the characteristic quality they bring to an activity. Leitmotiv asks what recurring direction becomes visible across a life. One person may be skilled at administration, respond energetically, bring a caring orientation to work and repeatedly seek to create places of belonging. These descriptions can coexist because they are not competing answers to one question.',
'The six orientations also need one another. Inquiry can discover a problem, thought can clarify it, organization can coordinate a response, care can notice who is affected, innovation can find another approach and conservation can retain what works. This original project example explains how a strength becomes one-sided when detached from the whole. Ask which contribution is missing, rather than assigning everyone a permanent box. The same person may bring different orientations into activity as circumstances and responsibilities change.'
],[
'Orientação, capacidade, temperamento e direção respondem a perguntas distintas',
'Aptidão pergunta o que alguém consegue fazer. Temperamento trata do modo de reagir. Orientação descreve a qualidade característica levada à atividade. Leitmotiv pergunta pela direção recorrente na biografia. Uma pessoa pode administrar bem, reagir energicamente, trabalhar com cuidado e buscar repetidamente criar pertencimento. As descrições coexistem porque respondem a perguntas diferentes.',
'As seis orientações também precisam umas das outras. Investigar descobre um problema; pensar o esclarece; organizar coordena a resposta; cuidar percebe os afetados; inovar encontra outra abordagem; conservar retém o que funciona. O exemplo explica como uma força se torna unilateral quando separada do conjunto. Pergunte qual contribuição falta, em vez de classificar pessoas permanentemente. A mesma pessoa pode mobilizar orientações diferentes com mudanças de contexto e responsabilidade.'
]),
u([13],'Phases · Chapter 5 · PDF 82–90',[
'Development at work requires both opportunity and participation',
'An organization can offer training without changing a person’s actual opportunity to use what is learned. It can also assign responsibility without providing preparation or support. Lievegoed’s educational concern lies in the relationship among learning, experience and increasing responsibility. A developmental role makes these parts speak to one another, instead of treating a worker only as the holder of a current job description.',
'Compare a specialist path and a managerial path. Greater contribution need not always mean supervising more people; it may mean deeper expertise, better teaching or wider judgment within a craft. A useful personnel conversation asks what the work needs, what the person is developing and where these meet. It also acknowledges limits such as available positions and resources. The book’s age patterns can prompt questions, but using age alone to assign or deny opportunities would replace attention to the person with the very abstraction the biographical approach should question.'
],[
'Desenvolver-se no trabalho exige oportunidade e participação',
'Uma organização pode oferecer formação sem permitir usar o aprendido. Também pode atribuir responsabilidade sem preparo ou apoio. A preocupação educativa de Lievegoed está na relação entre aprendizagem, experiência e responsabilidade crescente. Uma função favorece desenvolvimento quando conecta essas partes, em vez de reduzir a pessoa à descrição de seu emprego atual.',
'Compare caminhos de especialização e gestão. Contribuir mais não significa sempre supervisionar mais pessoas; pode significar aprofundar conhecimento, ensinar melhor ou ampliar julgamento num ofício. Uma conversa útil pergunta o que o trabalho exige, o que a pessoa desenvolve e onde ambos se encontram. Reconhece também limites de vagas e recursos. Padrões etários podem sugerir perguntas, mas usar idade sozinha para conceder ou negar oportunidades substituiria atenção individual por abstração.'
]),
u([14,15],'Phases · Chapter 6 · images of the human being and psychotherapy',[
'An explanatory model changes what counts as a question',
'A difficulty can be approached through bodily mechanisms, inherited disposition, learned patterns or questions of meaning and choice. Lievegoed’s images of the human being bring these emphases into view. A method may be useful for a particular question without explaining the whole person. The philosophical mistake he targets is turning one useful perspective into an exclusive account that makes other questions disappear.',
'Use a fictional person who repeatedly avoids a demanding task. One account asks about conditions and learned responses; another asks about the aim the person fears or values; another asks about bodily limitations. These questions need not have identical answers. Comparing Freud, Adler, Jung, Frankl or Assagioli in this chapter means understanding the explanatory emphasis Lievegoed attributes to each. It does not mean selecting a therapy for that fictional person. Separate the book’s philosophical comparison from evidence about treatment effectiveness and from the needs of any actual individual.'
],[
'O modelo explicativo muda o que se torna pergunta',
'Uma dificuldade pode ser abordada por mecanismos corporais, disposições herdadas, padrões aprendidos ou questões de sentido e escolha. As imagens do ser humano evidenciam essas ênfases. Um método pode servir a uma pergunta sem explicar a pessoa inteira. O erro filosófico criticado é transformar uma perspectiva útil em descrição exclusiva, fazendo desaparecer outras perguntas.',
'Imagine alguém que evita repetidamente uma tarefa difícil. Uma descrição investiga condições e respostas aprendidas; outra, a finalidade temida ou valorizada; outra, limitações corporais. As respostas não precisam coincidir. Comparar Freud, Adler, Jung, Frankl e Assagioli aqui é compreender a ênfase atribuída por Lievegoed, não escolher terapia para essa pessoa fictícia. Separe comparação filosófica, evidência de eficácia terapêutica e necessidades de um indivíduo real.'
]),
u([16],'Phases · Chapter 6 · helping relationships',[
'Help should leave the person more able to participate',
'A helping relationship has an asymmetry: one person is seeking support and the other may have knowledge, authority or control over the setting. Good intentions do not remove that difference. Lievegoed’s concerns about pressure and forced disclosure ask whether the recipient retains a meaningful choice about participation. Silence can be a boundary, not a symptom to be overcome.',
'Consider a group exercise that asks participants to discuss a private event. A genuine choice includes an ordinary alternative, time to decide and freedom from punishment or interpretation for declining. Calling an activity voluntary while treating refusal as evidence of resistance cancels that choice. Explain how the arrangement supports agency, continuity and appropriate limits of responsibility. The lesson develops judgment about the conditions of help; it does not authorize students to interpret another person’s history or act as therapists.'
],[
'A ajuda deve ampliar a possibilidade de participação',
'A relação de ajuda é assimétrica: alguém busca apoio; outra pessoa pode ter conhecimento, autoridade ou controle do ambiente. Boas intenções não eliminam essa diferença. As preocupações com pressão e exposição forçada perguntam se permanece uma escolha real de participação. O silêncio pode ser limite, não sintoma a superar.',
'Imagine um exercício coletivo sobre acontecimentos privados. Uma escolha real inclui alternativa comum, tempo para decidir e ausência de punição ou interpretação por recusar. Chamar a atividade de voluntária enquanto a recusa é tratada como resistência anula a escolha. Explique como a organização sustenta autonomia, continuidade e limites de responsabilidade. A lição desenvolve julgamento sobre condições de ajuda; não autoriza interpretar a história alheia nem atuar como terapeuta.'
]),
u([17],'Phases · Chapter 7 · PDF 130–141',[
'Practice gives an intention a form that can be reviewed',
'An intention such as “become more attentive” is too broad to show what someone will actually do. A practice gives it a limited form: a chosen object of attention, a manageable occasion and a way to notice distraction and return. In Lievegoed’s account, ordinary observation provides grounding for further self-development. Intensity of experience is not the same as steadiness of practice.',
'The unfinished-letter image makes a related point about freedom. A person enters a situation already containing words, commitments and consequences, yet the continuation is not wholly predetermined. One must read what is there before deciding how to continue. Apply this to a small commitment: what is given, what can be changed and what responsibility accompanies the choice? The spiritual capacities named in the chapter belong to the author’s larger path; an ordinary attention exercise illustrates preparation, not proof that those capacities have been attained.'
],[
'A prática dá à intenção uma forma que pode ser revista',
'“Tornar-se mais atento” é amplo demais para mostrar uma ação concreta. A prática dá forma limitada à intenção: objeto escolhido, ocasião viável e modo de perceber a distração e retornar. A observação cotidiana oferece fundamento ao desenvolvimento posterior. Intensidade de experiência não equivale a constância de prática.',
'A carta inacabada apresenta questão semelhante sobre liberdade. A pessoa entra numa situação com palavras, compromissos e consequências anteriores, mas a continuação não está inteiramente determinada. É preciso ler o existente antes de decidir. Aplique isso a um compromisso pequeno: o que é dado, o que pode mudar e que responsabilidade acompanha a escolha? As capacidades espirituais pertencem ao caminho mais amplo do autor; o exercício comum exemplifica preparação, não comprova que tenham sido alcançadas.'
])
];
