import {introduction} from './introduction.mjs';
import {lessons as a} from './lessons.mjs';
import {lessons as b} from './lessons-chapter-2.mjs';
import {lessons as c} from './lessons-chapter-3.mjs';
import {lessons as d} from './lessons-chapter-4.mjs';
import {foundations} from './concept-foundations.mjs';
const books=[...a,...b,...c,...d];
export const foundationCourse=[];
const ga9=chapter=>`https://rsarchive.org/Books/GA009/English/AP1971/GA009_c0${chapter}.html`;
function book(id,source,en,pt){const l=source===0?introduction:books.find(l=>l.id===source);foundationCourse.push({id,source:source===0?ga9(1):ga9(l.chapter),locator:source===0?'GA 9 · Introduction and Chapter I':`GA 9 · Chapter ${l.chapter} · ${l.pages}`,deeper:`lessons/${String(source).padStart(2,'0')}.html`,en:[en[0],en[1],l.en[2],l.en[4],l.en[5]],pt:[pt[0],pt[1],l.pt[2],l.pt[4],l.pt[5]]});}
function original(id,en,pt,source,locator,deeper){foundationCourse.push({id,en,pt,source,locator,deeper});}
book(1,0,['What are we studying?','Understand anthroposophy as a proposed path of knowledge, and distinguish a foundation course from a complete spiritual training.'],['O que estamos estudando?','Compreender a antroposofia como caminho de conhecimento proposto e distinguir um curso de fundamentos de uma formação espiritual completa.']);
original(2,
 ['Observation, interpretation and knowledge','Distinguish what you encounter from the explanation you form.',[
  'An observation describes what you notice. An interpretation connects what you notice with an explanation. Knowledge requires examining that connection. If a plant leans toward a window, its position is observable; an account of how light affects its growth introduces an explanatory relationship. You should be able to say what supports that relationship and what might require revision.',
  'Thinking is already involved when we distinguish, compare and connect. The aim is not to eliminate thinking in favour of supposedly pure observation, but to become conscious of what thinking contributes. “It happened after this” and “it happened because of this” are different statements.',
  'Steiner’s opening account in Theosophy distinguishes sensory encounter, personal response and understanding. We will develop those terms in the next lesson. For now, separate the event, its significance for you and your account of it. A single sentence may contain all three.',
  'Use this distinction throughout the course. A spiritual claim also needs to be understood accurately: what is asserted, how the author arrives at it, and what kind of access to it is claimed? Neither agreement nor dismissal replaces understanding the argument.'
 ],'Someone says, “The plant looks sad because I neglected it.” What needs separating?','The visible state of the plant, the observer’s emotional description, and the proposed explanation by neglect. Further observations are needed to assess the explanation.'],
 ['Observação, interpretação e conhecimento','Distinguir o que você encontra da explicação que formula.',[
  'Uma observação descreve o que você nota. Uma interpretação relaciona o observado a uma explicação. Conhecer exige examinar essa relação. Se uma planta se inclina em direção à janela, sua posição é observável; explicar como a luz afeta seu crescimento introduz uma relação explicativa. É preciso dizer o que sustenta essa relação e o que poderia exigir revisão.',
  'O pensar já participa quando distinguimos, comparamos e relacionamos. A proposta não é eliminar o pensar em favor de uma observação supostamente pura, mas perceber sua contribuição. “Aconteceu depois disso” e “aconteceu por causa disso” são afirmações diferentes.',
  'A abertura de Teosofia distingue encontro sensorial, resposta pessoal e compreensão. Desenvolveremos esses termos na próxima lição. Por enquanto, separe o acontecimento, seu significado para você e sua explicação. Uma frase pode conter os três.',
  'Use essa distinção durante o curso. Uma afirmação espiritual também precisa ser compreendida com precisão: o que se afirma, como o autor chega à afirmação e que acesso a ela é proposto? Concordar ou rejeitar não substitui compreender o argumento.'
 ],'Alguém diz: “A planta está triste porque a negligenciei.” O que precisa ser separado?','O estado visível da planta, a descrição emocional de quem observa e a explicação proposta pela negligência. Outras observações são necessárias para avaliar a explicação.'],ga9(1),'GA 9 · I · opening distinctions','practical-thinking/index.html');
for(const [id,section,deeper] of [[3,0,'lessons/01.html'],[4,1,'lessons/02.html'],[8,3,'lessons/06.html']]){
 const v=foundations;original(id,
 [v.en.sections[section].title.slice(3),section===3?'Compare organizing questions before comparing lists.':'Explain the distinction using one ordinary encounter.',v.en.sections[section].paragraphs,v.en.check,v.en.answer],
 [v.pt.sections[section].title.slice(3),section===3?'Comparar as perguntas organizadoras antes das listas.':'Explicar a distinção usando um encontro cotidiano.',v.pt.sections[section].paragraphs,v.pt.check,v.pt.answer],ga9(1),'GA 9 · I; GA 13 · II',deeper);
}
original(5,
 ['Matter and living organization','Understand the physical and etheric members before studying sensation.',foundations.en.sections[2].paragraphs.slice(0,3),'Why distinguish physical existence from living organization?','The distinction asks both what a body is materially and how it develops and maintains a living form. Etheric names Steiner’s proposed formative organization, rather than another material substance.'],
 ['Matéria e organização viva','Compreender os membros físico e etérico antes de estudar a sensação.',foundations.pt.sections[2].paragraphs.slice(0,3),'Por que distinguir existência física e organização viva?','A distinção pergunta tanto pela materialidade do corpo quanto pelo desenvolvimento e manutenção de uma forma viva. Etérico nomeia a organização formativa proposta por Steiner, não outra substância material.'],
 'https://rsarchive.org/Books/GA013/English/RSP1969/GA013_c02.html','GA 13 · II · physical and etheric members','lessons/03.html');
original(6,
 ['Inward experience and the I','Complete the fourfold account by distinguishing sensation from individual selfhood.',foundations.en.sections[2].paragraphs.slice(3),'Why does the fourfold account distinguish the astral member from the I?','The astral member concerns inward experience, including sensation and desire. The I concerns spiritual individuality and its relation to that experience. Having a sensation and taking an individual position toward it are different questions.'],
 ['Experiência interior e Eu','Completar a descrição quádrupla distinguindo sensação e individualidade.',foundations.pt.sections[2].paragraphs.slice(3),'Por que a descrição quádrupla distingue o membro astral e o Eu?','O membro astral diz respeito à experiência interior, incluindo sensação e desejo. O Eu diz respeito à individualidade espiritual e sua relação com a experiência. Ter uma sensação e assumir uma posição individual diante dela são perguntas diferentes.'],
 'https://rsarchive.org/Books/GA013/English/RSP1969/GA013_c02.html','GA 13 · II · astral member and I','lessons/05.html');
original(7,
 ['The threefold bodily organization','Distinguish a functional account of bodily life from body, soul and spirit.',[
  'We have studied three relationships to the world and four members of the human being. A further account asks about the organization of bodily activity. Steiner distinguishes nerve-sense, rhythmic and metabolic activity; movement belongs with the metabolic-limb aspect in this terminology.',
  'He relates these respectively to thinking, feeling and willing. This is a proposed correspondence between bodily and soul activity, not a renaming of body, soul and spirit. It concerns cooperating functions, not three separate people or a simple division into head, chest and everything below.',
  'When studying a diagram, distinguish its categories from its explanatory arrows. The names of the systems identify what is being compared; the arrows express Steiner’s claims about their relationships. Neither a diagram nor an everyday experience of breathing establishes the whole account.',
  'Read this as Steiner’s spiritual-physiological interpretation, not as a substitute for contemporary physiology. The source lecture also advances specific claims about nerves; these require separate scientific assessment and are not prerequisites for learning the conceptual distinction here.'
 ],'Does “threefold” always mean body, soul and spirit?','No. In this lesson it refers to bodily functions. Always name the three terms and the question the account addresses before comparing it with another threefold account.'],
 ['A organização corporal tríplice','Distinguir uma descrição funcional do corpo de corpo, alma e espírito.',[
  'Estudamos três relações com o mundo e quatro membros do ser humano. Outra descrição pergunta pela organização da atividade corporal. Steiner distingue atividades neurossensorial, rítmica e metabólica; o movimento pertence ao aspecto metabólico-motor nessa terminologia.',
  'Ele as relaciona respectivamente a pensar, sentir e querer. Trata-se de uma correspondência proposta entre atividade corporal e anímica, não de novos nomes para corpo, alma e espírito. São funções cooperantes, não três pessoas nem uma divisão simples entre cabeça, tórax e tudo o que está abaixo.',
  'Ao estudar um diagrama, distinga suas categorias de suas setas explicativas. Os nomes identificam o que se compara; as setas expressam afirmações de Steiner sobre as relações. Nem um diagrama nem a experiência cotidiana da respiração demonstram toda a concepção.',
  'Leia essa concepção como interpretação espiritual e fisiológica de Steiner, não como substituta da fisiologia contemporânea. A palestra também apresenta afirmações específicas sobre nervos; elas exigem avaliação científica separada e não são pré-requisitos para compreender a distinção conceitual aqui.'
 ],'“Tríplice” sempre significa corpo, alma e espírito?','Não. Nesta lição, refere-se a funções corporais. Nomeie os três termos e a pergunta da descrição antes de compará-la com outra descrição tríplice.'],
 'https://rsarchive.org/Lectures/GA301/English/AP2001/19200421d01.html','GA 301 · Basel · 21 April 1920 · bodily organization','reference/human-constitution.html');
book(9,4,['How inner life becomes differentiated','Follow the movement from sensation to reflection and conscious judgment.'],['Como a vida interior se diferencia','Acompanhar a passagem da sensação à reflexão e ao juízo consciente.']);
book(10,5,['Individuality and spiritual development','Distinguish the I, consciousness soul and spirit-self.'],['Individualidade e desenvolvimento espiritual','Distinguir Eu, alma da consciência e si-mesmo espiritual.']);
book(11,7,['Memory, capacity and biography','Understand what an experience can leave behind.'],['Memória, capacidade e biografia','Compreender o que uma experiência pode deixar.']);
book(12,21,['Freedom and responsible action','Ask how a motive becomes your own considered reason for acting.'],['Liberdade e ação responsável','Perguntar como um motivo se torna sua própria razão ponderada para agir.']);
book(13,8,['Reincarnation: the proposed continuity of individuality','Reconstruct the proposal without treating analogy as proof.'],['Reencarnação: a continuidade proposta da individualidade','Reconstruir a proposta sem tratar analogia como prova.']);
book(14,9,['Karma: action, consequence and destiny','Distinguish responsibility from a fixed or punitive account of fate.'],['Carma: ação, consequência e destino','Distinguir responsabilidade de uma concepção fixa ou punitiva de destino.']);
book(15,10,['What Steiner means by the soul world','Distinguish a claimed realm of soul reality from an everyday mood.'],['O que Steiner entende por mundo anímico','Distinguir um domínio proposto de realidade anímica de um estado de humor.']);
book(16,12,['What Steiner means by the spiritual world','Understand the meaning of archetype before studying detailed cosmology.'],['O que Steiner entende por mundo espiritual','Compreender arquétipo antes de estudar cosmologia detalhada.']);
original(17,
 ['The path of knowledge','Distinguish studying spiritual concepts from the capacities Steiner describes.',[
  'Understanding a spiritual account and claiming to perceive its subject are different achievements. Reading this course develops conceptual understanding. Steiner’s path of knowledge concerns a further transformation of capacities, accompanied by work on attention, judgment and conduct.',
  'Imagination, Inspiration and Intuition name forms of spiritual cognition in this context. Imagination concerns image-like spiritual perception; Inspiration concerns apprehending spiritual relationships and meaning beyond the images; Intuition concerns participation in the being known. They do not simply mean inventiveness, enthusiasm and a hunch.',
  'These brief definitions orient the next book study; they are not instructions for producing the experiences. Nor should every use of intuition elsewhere be assigned this meaning automatically. Read the term in the argument of the particular work.',
  'An introductory practice can be modest: describe an object carefully, notice an assumption, and reconsider it. Such work develops habits relevant to study. Assess the practice by the quality of attention and judgment it supports, without treating a feeling of certainty as certification of spiritual knowledge.'
 ],'Does a vivid mental image establish Imagination in the technical sense?','No. Vividness alone does not establish the claimed spiritual cognition. Distinguish ordinary image-making, conceptual understanding and the specific capacity described in the source.'],
 ['O caminho do conhecimento','Distinguir o estudo de conceitos espirituais das capacidades descritas por Steiner.',[
  'Compreender uma concepção espiritual e afirmar que se percebe seu objeto são realizações diferentes. Este curso desenvolve compreensão conceitual. O caminho de conhecimento de Steiner envolve outra transformação de capacidades, acompanhada pelo trabalho sobre atenção, juízo e conduta.',
  'Imaginação, Inspiração e Intuição nomeiam formas de cognição espiritual nesse contexto. Imaginação diz respeito à percepção espiritual em imagens; Inspiração, à apreensão de relações e significados espirituais além das imagens; Intuição, à participação no ser conhecido. Não significam simplesmente inventividade, entusiasmo e palpite.',
  'Essas definições breves orientam o estudo seguinte; não são instruções para produzir experiências. Também não se deve atribuir automaticamente esse significado a todo uso de intuição em outras obras. Leia o termo no argumento de cada obra.',
  'Uma prática introdutória pode ser modesta: descrever um objeto com atenção, perceber uma suposição e reconsiderá-la. Esse trabalho desenvolve hábitos pertinentes ao estudo. Avalie a prática pela atenção e pelo juízo que favorece, sem tratar um sentimento de certeza como certificação de conhecimento espiritual.'
 ],'Uma imagem mental vívida demonstra Imaginação no sentido técnico?','Não. A vivacidade, sozinha, não demonstra a cognição espiritual proposta. Distinga criação comum de imagens, compreensão conceitual e a capacidade específica descrita na fonte.'],
 'https://rsarchive.org/Books/GA012/English/SOL/GA012_c04.html','GA 12 · Inspiration and Intuition; compare preceding Imagination chapter','higher-worlds/index.html');
original(18,
 ['Bring the relationships together','Explain the foundation and choose a purposeful next study.',[
  'Return to one ordinary encounter: you meet a friend who asks for help. Describe bodily perception, personal response and the understanding you seek. Then distinguish thinking, feeling and willing within the encounter. Explain why these are two different threefold descriptions.',
  'Now reconstruct the fourfold account in its own terms: physical existence, living organization, inward experience and individual selfhood. Explain which question each member addresses. Do not assign a soul activity to a bodily member merely because two diagrams use similar colours or numbers.',
  'Connect biography with memory and capacity. Then distinguish these familiar observations from the further account of reincarnation and karma. Finally explain why learning about spiritual worlds is different from claiming spiritual perception.',
  'Choose your next study according to your question. Theosophy develops the whole spiritual account; The Philosophy of Freedom develops knowing and free action; Higher Worlds develops the path of knowledge. Practical Thinking can accompany any of them. The subject courses explore particular applications and traditions; they are choices, not compulsory steps toward a certificate of spiritual attainment.'
 ],'Can you explain one relationship, identify its source and name a question that remains?','A strong synthesis gives the terms their proper meanings, explains how they relate, identifies the source and separates illustration from justification. Choose the next book because it addresses your remaining question, rather than because every course must be completed.'],
 ['Reúna as relações','Explicar os fundamentos e escolher um próximo estudo com propósito.',[
  'Retome um encontro cotidiano: uma amiga pede ajuda. Descreva percepção corporal, resposta pessoal e a compreensão que busca. Depois distinga pensar, sentir e querer no encontro. Explique por que são duas descrições tríplices diferentes.',
  'Reconstrua a descrição quádrupla em seus próprios termos: existência física, organização viva, experiência interior e individualidade. Explique a pergunta de cada membro. Não atribua uma atividade anímica a um membro corporal apenas porque dois diagramas usam cores ou números semelhantes.',
  'Relacione biografia, memória e capacidade. Depois distinga essas observações familiares da concepção adicional de reencarnação e carma. Por fim, explique por que estudar mundos espirituais é diferente de afirmar percepção espiritual.',
  'Escolha o próximo estudo conforme sua pergunta. Teosofia desenvolve a concepção espiritual ampla; A Filosofia da Liberdade, conhecimento e ação livre; O Conhecimento dos Mundos Superiores, o caminho de conhecimento. O Pensar Prático pode acompanhar todos eles. Os cursos temáticos exploram aplicações e tradições particulares; são escolhas, não etapas obrigatórias para um certificado de realização espiritual.'
 ],'Você consegue explicar uma relação, identificar sua fonte e nomear uma pergunta restante?','Uma boa síntese define corretamente os termos, explica suas relações, identifica a fonte e separa ilustração de justificação. Escolha o próximo livro por sua pergunta, não porque todos os cursos precisem ser concluídos.'],ga9(1),'Course synthesis · revisit the sources of Lessons 1–17','index.html#courses');
foundationCourse.sort((a,b)=>a.id-b.id);
const orientation=foundationCourse[0];
orientation.en[2]=[
 introduction.en[2][0],
 'Rudolf Steiner (1861–1925) worked on Goethe’s scientific writings and on philosophy before developing the anthroposophical movement. His work includes authored books and many lectures addressed to particular audiences. Anthroposophy also became the basis of practical initiatives in education, the arts and other fields. Its institutional history and its ideas are related, but they are not the same subject.',
 introduction.en[2][1],introduction.en[2][4],introduction.en[2][5],introduction.en[2][6],
 'Keep three voices distinct as you read: Steiner’s own text, later writers interpreting or applying it, and this course’s explanations. A page by Hermann Koepke or Gilbert Childs is not automatically a statement by Steiner. The optional book courses identify these sources; the foundation gives you the concepts needed to approach them.'
];
orientation.pt[2]=[
 introduction.pt[2][0],
 'Rudolf Steiner (1861–1925) trabalhou com os escritos científicos de Goethe e com filosofia antes de desenvolver o movimento antroposófico. Sua obra inclui livros escritos e muitas palestras dirigidas a públicos específicos. A antroposofia também fundamentou iniciativas práticas na educação, nas artes e em outros campos. Sua história institucional e suas ideias se relacionam, mas não são o mesmo assunto.',
 introduction.pt[2][1],introduction.pt[2][4],introduction.pt[2][5],introduction.pt[2][6],
 'Distinga três vozes ao ler: o texto do próprio Steiner, autores posteriores que o interpretam ou aplicam e as explicações deste curso. Uma página de Hermann Koepke ou Gilbert Childs não é automaticamente uma afirmação de Steiner. Os cursos opcionais identificam essas fontes; os fundamentos apresentam os conceitos para abordá-las.'
];
orientation.historySource='https://rsarchive.org/Steiner/Timeline.html';
// Checks must be answerable at this point, without concepts from later lessons.
for(const lang of ['en','pt']){
 const pt=lang==='pt';
 const set=(id,q,a)=>{const l=foundationCourse.find(x=>x.id===id);l[lang][3]=q;l[lang][4]=a;};
 set(3,pt?'Por que prazer e compreensão não são equivalentes?':'Why are enjoyment and understanding not equivalent?',pt?'Prazer é uma resposta pessoal; compreender busca uma relação cuja validade não depende desse prazer. Ambos participam do encontro, com condições corporais.':'Enjoyment is a personal response; understanding seeks a relationship whose validity does not depend on that enjoyment. Both participate in the encounter, with bodily conditions.');
 set(4,pt?'Como pensar, sentir e querer participam de devolver algo emprestado?':'How do thinking, feeling and willing participate in returning a borrowed object?',pt?'Compreender a situação envolve pensar; gratidão ou relutância envolve sentir; decidir e realizar a devolução envolve querer. São atividades relacionadas.':'Understanding the situation involves thinking; gratitude or reluctance involves feeling; deciding and carrying out the return involves willing. These activities cooperate.');
}
