// Original teaching material. Page ranges refer to the 1971 English edition of GA 9.
import {applyChapterOneRevision} from './theosophy-chapter-one-revision.mjs';
export const lessons = [];
const add = (id, chapter, pages, notes, en, pt) => {const lesson={id,chapter,pages,notes,en,pt};applyChapterOneRevision([lesson]);lessons.push(lesson);};
// Each language: title, learning goal, explanation paragraphs, exercise, question, suggested answer.
add(1, 1, '1–5', '',
['Encountering the world', 'Distinguish body, soul, and spirit using an everyday encounter.', [
'Begin with three connected aspects of one encounter. Body: the organs through which you meet the surrounding world. Soul: your inward experience, including sensations, feelings, desires, and intentions. Spirit: that through which, in Steiner’s account, you can recognize truth beyond your personal response. These are not three people inside you.',
'Why call that last aspect “spirit”? Steiner understands knowing as a connection with reality beyond our private experience. A truth does not become true because we enjoy it or because everyone agrees. We can also be mistaken: having a confident thought is not the same as recognizing truth.',
'This is an entrance to his meaning, not the complete definition. Later in the book, spirit includes a lasting spiritual individuality and a connection with a real spiritual world. He also connects it with recognizing moral goodness beyond personal preference. Clear thinking is a starting point for understanding this larger account; an everyday example does not prove all of it.',
'For this first lesson, you only need to explain the difference between your personal response and what you seek to understand about the world. Keep the fuller meaning of spirit in view without trying to learn all the later classifications now.'
], 'Return to the stars example. Write two sentences: “My feeling could change if…” and “The relationship I understood would not change merely because…”. Then name the bodily organs involved. You do not need knowledge of astronomy beyond the example.', 'Your friend says, “Spirit just means having a clever opinion about the stars.” What needs correcting?', 'An opinion can be mistaken, however clever it sounds. The example concerns recognizing a relationship that does not depend on personal preference. For Steiner, this illustrates spiritual activity, while spirit has a wider meaning involving spiritual reality and individuality. Also, the soul includes sensations and desires, not only emotions.'],
['Nosso encontro com o mundo', 'Distinguir corpo, alma e espírito a partir de um encontro cotidiano.', [
'Comece com três aspectos ligados de um mesmo encontro. Corpo: os órgãos pelos quais você encontra o mundo ao redor. Alma: sua experiência interior, incluindo sensações, sentimentos, desejos e intenções. Espírito: aquilo pelo qual, na concepção de Steiner, você pode reconhecer uma verdade além da resposta pessoal. Não são três pessoas dentro de você.',
'Por que chamar esse último aspecto de “espírito”? Steiner entende o conhecer como uma ligação com uma realidade além da experiência privada. Uma verdade não se torna verdadeira porque gostamos dela ou porque todos concordam. Também podemos nos enganar: ter um pensamento confiante não equivale a reconhecer a verdade.',
'Essa é uma entrada para seu significado, não a definição completa. Mais adiante no livro, espírito inclui uma individualidade espiritual duradoura e uma ligação com um mundo espiritual real. Steiner também o relaciona ao reconhecimento do bem moral além da preferência pessoal. Pensar com clareza é um ponto de partida para compreender essa concepção mais ampla; um exemplo cotidiano não comprova tudo isso.',
'Nesta primeira lição, basta conseguir explicar a diferença entre sua resposta pessoal e aquilo que busca compreender sobre o mundo. Mantenha em vista o sentido mais amplo de espírito sem tentar aprender agora todas as classificações posteriores.'
], 'Volte ao exemplo das estrelas. Escreva duas frases: “Meu sentimento poderia mudar se…” e “A relação que compreendi não mudaria apenas porque…”. Depois nomeie os órgãos corporais envolvidos. Você não precisa de conhecimentos de astronomia além do exemplo.', 'Uma amiga diz: “Espírito significa apenas ter uma opinião inteligente sobre as estrelas”. O que precisa ser corrigido?', 'Uma opinião pode estar errada, por mais inteligente que pareça. O exemplo envolve reconhecer uma relação que não depende da preferência pessoal. Para Steiner, isso ilustra atividade espiritual, enquanto espírito tem um significado mais amplo, envolvendo realidade e individualidade espirituais. Além disso, a alma inclui sensações e desejos, não apenas emoções.']);
add(2, 1, '6–11', '',
['Embodiment and inner experience', 'Separate bodily processes from the experience of them.', [
'The body connects us to the material world, but a description of an event outside us is not yet a description of how we experience it. Hearing a sound and finding it comforting are connected without meaning the same thing. Steiner uses such distinctions to develop his account of human nature.',
'Soul is broader than emotion alone. It includes the inner life of sensations, desires, feelings, and impulses to act. Spirit is not simply another pleasant feeling: the book connects it with knowledge and an orientation beyond personal liking. Keep these uses of the words visible as you read.',
'A bell provides a useful example. Its vibration, your hearing of it, your irritation, and your inquiry into its pattern are distinguishable aspects of the encounter. The distinction is a reading tool, not a claim that these aspects operate independently. Historical descriptions of anatomy or human differences in this chapter should not be used to rank people’s worth or as present-day biological instruction.'
], 'Describe a fictional person hearing a bell. Separate the physical event, the sensation, the feeling, and the impulse to act. Explain why “soul” includes more than the feeling.', 'Does describing the vibration of a bell fully describe the listener’s irritation?', 'It describes a physical aspect of the encounter, but does not express the listener’s particular experience. Steiner uses this distinction to introduce soul life. Identifying a distinction is not yet an explanation of how body and soul relate.'],
['Corpo e experiência interior', 'Separar processos corporais da experiência que temos deles.', [
'O corpo nos liga ao mundo material, mas descrever um acontecimento externo ainda não é descrever como o vivenciamos. Ouvir um som e considerá-lo reconfortante estão relacionados, sem significar a mesma coisa. Steiner usa distinções assim para desenvolver sua concepção do ser humano.',
'Alma é mais ampla do que emoção. Inclui a vida interior das sensações, dos desejos, dos sentimentos e dos impulsos para agir. Espírito não é apenas mais um sentimento agradável: o livro o relaciona ao conhecimento e a uma orientação que ultrapassa o gosto pessoal. Mantenha esses sentidos das palavras em vista durante a leitura.',
'Um sino oferece um exemplo. Sua vibração, a audição, a irritação e a investigação de seu padrão são aspectos distinguíveis do encontro. Essa distinção ajuda a leitura; não afirma que tais aspectos funcionem isoladamente. Descrições históricas de anatomia ou de diferenças humanas neste capítulo não devem servir para classificar o valor das pessoas ou ensinar biologia atual.'
], 'Descreva uma pessoa fictícia ouvindo um sino. Separe acontecimento físico, sensação, sentimento e impulso para agir. Explique por que “alma” inclui mais do que o sentimento.', 'Descrever a vibração de um sino descreve completamente a irritação de quem o ouve?', 'A descrição aborda um aspecto físico do encontro, mas não expressa a experiência particular de quem ouve. Steiner usa essa distinção para introduzir a vida da alma. Identificar uma distinção ainda não explica como corpo e alma se relacionam.']);
add(3, 1, '11–20', '1–2',
['Life, sensation, and formative organization', 'Distinguish physical organization, life, and sensation in Steiner’s account.', [
'A living plant has material components, yet it also grows and maintains an organized form. Steiner introduces the ether or life body to account for the formative activity of living beings. This is a supersensible organization in his account, not a second visible plant tucked inside the first.',
'He then distinguishes life from sensation. Growing and responding to conditions are not, in his classification, equivalent to having an inner experience of pleasure or pain. The soul body prepares the connection with sensation; the sentient soul belongs to the inward experiencing side. Later groupings combine terms that are distinguished here.',
'“Ether” is a technical term in this book. Do not assume it means the historical ether of physics, an aura photograph, or a measurable fluid. Observing growth supplies the question Steiner addresses; it does not independently establish his proposed supersensible explanation. The addenda help keep physical observation and the claimed mode of spiritual perception distinct.'
], 'Make three columns: physical composition, living organization, inner sensation. Place a stone, a plant, and an animal in Steiner’s scheme, noting which distinctions are his claims.', 'Does a plant’s growth by itself prove the existence of the ether body?', 'No. Growth is an observable phenomenon; the ether body is Steiner’s account of its supersensible formative organization. The phenomenon and that explanation must not be treated as identical.'],
['Vida, sensação e organização formativa', 'Distinguir organização física, vida e sensação na concepção de Steiner.', [
'Uma planta viva tem componentes materiais, mas também cresce e mantém uma forma organizada. Steiner introduz o corpo etérico ou vital para explicar a atividade formativa dos seres vivos. Em sua concepção, trata-se de uma organização suprassensível, não de outra planta visível escondida na primeira.',
'Em seguida, distingue vida e sensação. Crescer e responder às condições não equivalem, em sua classificação, a ter uma experiência interior de prazer ou dor. O corpo anímico prepara a ligação com a sensação; a alma senciente pertence ao aspecto da vivência interior. Agrupamentos posteriores reúnem termos que aqui são diferenciados.',
'“Éter” é um termo técnico neste livro. Não presuma que seja o éter histórico da física, uma fotografia de aura ou um fluido mensurável. Observar o crescimento fornece a pergunta abordada por Steiner; não comprova de forma independente sua explicação suprassensível. Os adendos ajudam a separar observação física e a modalidade de percepção espiritual que ele afirma existir.'
], 'Faça três colunas: composição física, organização viva e sensação interior. Situe uma pedra, uma planta e um animal no esquema de Steiner, identificando quais distinções são afirmações do autor.', 'O crescimento de uma planta, por si só, comprova a existência do corpo etérico?', 'Não. O crescimento é um fenômeno observável; o corpo etérico é a explicação de Steiner para sua organização formativa suprassensível. O fenômeno e essa explicação não devem ser tratados como idênticos.']);
add(4, 1, '20–26', '4',
['Three aspects of soul', 'Explain the sentient, intellectual, and consciousness souls without ranking people.', [
'Steiner differentiates soul life according to how experience is taken up and worked through. The sentient soul is closely connected with sensation, attraction, and aversion. The intellectual or mind soul works experience into thought and relationships. The consciousness soul is directed toward truth that has validity beyond personal inclination.',
'Consider criticism of a piece of writing. Immediate hurt, an attempt to understand the criticism, and a judgment about whether it is justified help illustrate different movements of inner life. This is an original teaching example, not a diagnostic test or an exact map of separate mental compartments.',
'“Consciousness soul” here does not merely mean being awake. Nor should the sequence become a scale for declaring other people inferior. Read the addendum’s qualifications alongside the chapter, especially when considering what Steiner says about thinking and animals. Learn the distinctions before attempting to connect them with later classifications.'
], 'Use a fictional disagreement. Write an immediate reaction, a reflective interpretation, and a judgment that could remain valid even if unpleasant. Explain the limits of the example.', 'Is a thought automatically an expression of the consciousness soul just because someone is awake?', 'No. In this terminology, the consciousness soul concerns an orientation toward truth beyond personal preference. Wakefulness alone does not express that distinction, and the categories should not be used to label whole people.'],
['Três aspectos da alma', 'Explicar alma senciente, alma do intelecto e alma da consciência sem classificar pessoas.', [
'Steiner diferencia a vida anímica conforme a experiência é acolhida e elaborada. A alma senciente está ligada à sensação, à atração e à aversão. A alma do intelecto, também chamada alma intelectual, elabora experiências em pensamentos e relações. A alma da consciência se orienta para uma verdade válida além da inclinação pessoal.',
'Considere uma crítica a um texto. A mágoa imediata, a tentativa de entender a crítica e o julgamento sobre sua pertinência ajudam a ilustrar diferentes movimentos da vida interior. Este é um exemplo didático original, não um teste diagnóstico nem um mapa exato de compartimentos mentais separados.',
'“Alma da consciência” não significa apenas estar acordado. A sequência também não deve virar uma escala para declarar outras pessoas inferiores. Leia as qualificações do adendo junto ao capítulo, sobretudo ao considerar o que Steiner afirma sobre pensamento e animais. Aprenda as distinções antes de ligá-las às classificações posteriores.'
], 'Use um desacordo fictício. Escreva uma reação imediata, uma interpretação refletida e um julgamento que poderia continuar válido mesmo sendo desagradável. Explique os limites do exemplo.', 'Um pensamento expressa automaticamente a alma da consciência só porque a pessoa está acordada?', 'Não. Nessa terminologia, a alma da consciência envolve a orientação para uma verdade que ultrapassa a preferência pessoal. Estar acordado não expressa, por si só, essa distinção, e as categorias não devem rotular pessoas inteiras.']);
add(5, 1, '26–35', '5–6',
['The I and spiritual individuality', 'Distinguish the I, consciousness soul, and spirit self.', [
'The word “I” has a special position: when we use it about ourselves, it refers from within our own standpoint. Steiner uses this as an entrance to spiritual individuality. The ability to pronounce the word, however, is not the same as understanding the full concept developed in the chapter.',
'The I is not simply selfishness. It is the center through which, in this account, the person relates soul life to spirit and participates in transformation. The consciousness soul is described at the boundary of soul and spirit; spirit self names the spiritual content received and made one’s own. Closely connected does not mean interchangeable.',
'The book’s technical use of intuition concerns direct spiritual knowing. It should not be reduced to a hunch or a strong feeling of certainty. The addenda qualify the language surrounding individuality and knowing. To understand the passage, explain what role each term plays before deciding whether you accept the proposed spiritual account.'
], 'Write a short glossary entry for I, consciousness soul, spirit self, and intuition. Add one misleading everyday meaning to avoid for each.', 'Why is “I am sure because I feel it strongly” insufficient to explain Steiner’s technical use of intuition?', 'Strength of feeling alone is not the claimed direct spiritual knowing. His concept concerns a mode of knowledge, not simply confidence. Explaining that claim does not establish that a particular feeling fulfills it.'],
['O Eu e a individualidade espiritual', 'Distinguir Eu, alma da consciência e si-mesmo espiritual.', [
'A palavra “Eu” ocupa uma posição especial: quando a usamos a nosso respeito, ela se refere a nós a partir de nosso próprio ponto de vista. Steiner a utiliza como entrada para a individualidade espiritual. Pronunciar a palavra, porém, não equivale a compreender o conceito desenvolvido no capítulo.',
'O Eu não é simplesmente egoísmo. É o centro pelo qual, nessa concepção, a pessoa relaciona a vida anímica ao espírito e participa de sua transformação. A alma da consciência é descrita na fronteira entre alma e espírito; o si-mesmo espiritual designa o conteúdo espiritual recebido e tornado próprio. Estar intimamente relacionado não significa ser intercambiável.',
'O uso técnico de intuição no livro envolve conhecimento espiritual direto. Não deve ser reduzido a um palpite ou a uma forte sensação de certeza. Os adendos qualificam a linguagem sobre individualidade e conhecimento. Para compreender o trecho, explique a função de cada termo antes de decidir se aceita a concepção espiritual proposta.'
], 'Escreva definições breves de Eu, alma da consciência, si-mesmo espiritual e intuição. Acrescente um sentido cotidiano enganoso a evitar em cada caso.', 'Por que “tenho certeza porque sinto isso intensamente” não basta para explicar o uso técnico de intuição em Steiner?', 'A intensidade do sentimento, sozinha, não é o conhecimento espiritual direto que ele afirma existir. Seu conceito envolve uma modalidade de conhecimento, não apenas confiança. Explicar essa afirmação não demonstra que um sentimento particular a realize.']);
add(6, 1, '35–39', '3',
['One human being, several classifications', 'Explain why the ninefold and sevenfold lists differ.', [
'The chapter ends by regrouping distinctions already introduced. Its ninefold account names physical body, ether body, soul body, sentient soul, intellectual soul, consciousness soul, spirit self, life spirit, and spirit man. These are aspects of one human being, not nine independent objects.',
'An intermediate sevenfold presentation joins soul body with sentient soul, and consciousness soul with spirit self. This leaves physical body; ether body; sentient-soul-body; intellectual soul; spirit-filled consciousness soul; life spirit; spirit man. The change is a grouping decision, not the disappearance of two pieces.',
'A later sevenfold presentation emphasizes transformation: physical body, life body, astral body, I, spirit self, life spirit, spirit man. The last three are associated with the transformation of astral, life, and physical organization. Do not substitute this list for the earlier sevenfold grouping. Damaged OCR in the 1971 transcription was clarified through a parallel Shields translation; wording across editions differs.'
], 'Write the nine terms on slips of paper. Join only the two pairs described above to make seven groups. Then write the transformation list separately and mark how its organizing question differs.', 'Why do two sevenfold lists not necessarily have identical entries?', 'One combines adjacent distinctions in the ninefold account; the other foregrounds the I and transformation of bodily organizations. The number alone does not tell us the principle of classification.'],
['Um ser humano, diferentes classificações', 'Explicar por que as listas de nove e de sete membros diferem.', [
'O capítulo termina reagrupando distinções já introduzidas. A exposição de nove membros nomeia corpo físico, corpo etérico, corpo anímico, alma senciente, alma do intelecto, alma da consciência, si-mesmo espiritual, espírito vital e homem-espírito. São aspectos de um ser humano, não nove objetos independentes.',
'Uma apresentação intermediária de sete membros reúne corpo anímico e alma senciente, e também alma da consciência e si-mesmo espiritual. Restam corpo físico; corpo etérico; corpo-alma senciente; alma do intelecto; alma da consciência preenchida pelo espírito; espírito vital; homem-espírito. A mudança é de agrupamento, não o desaparecimento de duas partes.',
'Outra apresentação de sete membros enfatiza a transformação: corpo físico, corpo vital, corpo astral, Eu, si-mesmo espiritual, espírito vital e homem-espírito. Os três últimos se associam à transformação das organizações astral, vital e física. Não substitua o primeiro agrupamento de sete por essa lista. Danos na transcrição de 1971 foram esclarecidos com uma tradução paralela de Shields; as formulações variam entre edições.'
], 'Escreva os nove termos em papéis separados. Una apenas os dois pares indicados para formar sete grupos. Depois, escreva a lista da transformação à parte e identifique a diferença no critério de organização.', 'Por que duas listas de sete membros não precisam ter entradas idênticas?', 'Uma reúne distinções próximas da exposição de nove membros; a outra destaca o Eu e a transformação das organizações corporais. O número, sozinho, não revela o critério da classificação.']);
