// Original bilingual teaching. Quotations checked against the supplied PDF images.
// Page references are PDF capture pages, not printed book pagination.
import {nutritionPartTwo} from './nutrition-part-two.mjs';
export const nutritionTitle={en:'Nutrition: Food, Health and Spiritual Development',pt:'Nutrição: Alimentação, Saúde e Desenvolvimento Espiritual'};
export const nutritionSources={
 diet:['WHO: Healthy diet','https://www.who.int/news-room/fact-sheets/detail/healthy-diet'],
 digestion:['NIDDK: Your Digestive System & How It Works','https://www.niddk.nih.gov/health-information/digestive-diseases/digestive-system-how-it-works'],
 diabetes:['NIDDK: Symptoms & Causes of Diabetes','https://www.niddk.nih.gov/health-information/diabetes/overview/symptoms-causes'],
 bse:['CDC: Bovine Spongiform Encephalopathy','https://www.cdc.gov/mad-cow/php/animal-health/index.html'],
 hydro:['NINDS: Hydrocephalus','https://www.ninds.nih.gov/health-information/disorders/hydrocephalus'],
 alcohol:['WHO: Alcohol','https://www.who.int/news-room/fact-sheets/detail/alcohol'],
 withdrawal:['NIAAA: Understanding Alcohol Use Disorder','https://www.niaaa.nih.gov/publications/brochures-and-fact-sheets/understanding-alcohol-use-disorder'],
 tobacco:['WHO: Tobacco and nicotine','https://www.who.int/news-room/fact-sheets/detail/tobacco']
};
export const nutritionLessons=[
{id:0,chapter:null,span:'6–8; 115–117',quotePage:7,quote:'But more fundamentally Steiner here, as elsewhere, never wishes to impinge on the freedom of the individual.',speaker:'Christian von Arnim',lecture:'Introduction; Sources; Note on Rudolf Steiner’s Lectures',
 en:{title:'Before you begin: food, freedom and careful reading',goal:'Recognize the different voices in the book and learn how to study a claim without turning it into a rule.',
 theory:[
 'This book asks how eating relates to the whole human being: bodily life, feeling, thinking and spiritual development. It is a thematic collection compiled and edited by Christian von Arnim, rather than a continuous treatise written by Steiner. The introduction and short chapter introductions belong to the editor; the main extracts report Steiner’s lectures to different audiences between 1906 and 1924. The collection moves from a spiritual picture of nutrition to particular foods, digestion, stimulants and health.',
 'A central question is freedom. Does a habit support a person’s ability to act deliberately, or does the person increasingly depend on it? The editor identifies this concern in Steiner’s refusal to issue universal dietary orders. However, the extracts also contain strong recommendations and judgments. Careful study holds both features together: an intention to respect individual choice and particular assertions that still need examination.',
 'We will distinguish an observation, an analogy, an argument and a claim of supersensible perception. An observation describes something encountered; an analogy compares relationships; an argument connects reasons to a conclusion; supersensible perception is Steiner’s claimed access to realities beyond ordinary senses. These forms of statement do different work. Understanding his terminology is the first task; deciding how well a claim is supported is a further task.'
 ],quoteTranslation:null,close:'This is the editor describing Steiner’s purpose. “Freedom” names an educational aim; it does not make every physiological assertion in the collection correct. Keep the distinction between speaker and subject when quoting it.',
 example:'A reader hears that coffee supports connected thinking and decides that every student should drink it.',explanation:'The reader has converted a reported effect into a universal instruction. The book’s recurring question is what supports an individual’s activity. A course can examine that question through reading and reasoning without requiring a change of diet.',
 takeaways:['The collection contains editorial framing and lectures from different contexts.','An explanation of an effect and a command to consume a food are different statements.','Understanding, agreement and verification are separate achievements.'],
 activity:'Start a notebook with four headings: passage and page; meaning in my own words; kind of claim; question to investigate. Use the quotation above for your first entry. Record one food-related assumption you would like to examine by the end of the course.',
 checks:[['Who wrote the quoted sentence?','Christian von Arnim, in his introduction. It reports his interpretation of Steiner’s approach.'],['Does refusing to prescribe mean the book makes no recommendations?','No. Later chapters contain recommendations. Compare their wording, audience and qualifications with the stated commitment to freedom.'],['What would count as success in this course?','An accurate explanation supported by a passage, with a reasoned judgment about its scope. Personal agreement is not required.']],
 context:'This is a historical and philosophical reading course for adults. It provides no diet plan or treatment programme. Contemporary health notes appear beside claims that could otherwise be mistaken for medical guidance.'},
 pt:{title:'Antes de começar: alimentação, liberdade e leitura atenta',goal:'Reconheça as diferentes vozes do livro e aprenda a estudar uma afirmação sem transformá-la em regra.',
 theory:[
 'Este livro pergunta como a alimentação se relaciona com o ser humano inteiro: vida corporal, sentimento, pensamento e desenvolvimento espiritual. É uma coletânea temática organizada por Christian von Arnim, e não um tratado contínuo escrito por Steiner. A introdução e as apresentações breves dos capítulos são do organizador; os trechos principais registram palestras de Steiner para diferentes públicos entre 1906 e 1924. A sequência vai de uma visão espiritual da nutrição a alimentos específicos, digestão, estimulantes e saúde.',
 'Uma pergunta central é a liberdade. Um hábito favorece a capacidade de agir deliberadamente ou produz dependência crescente? O organizador reconhece essa preocupação na recusa de Steiner de impor regras alimentares universais. Entretanto, os trechos também contêm recomendações e julgamentos fortes. A leitura atenta considera as duas coisas: a intenção de respeitar a escolha individual e afirmações específicas que continuam precisando de exame.',
 'Distinguiremos observação, analogia, argumento e afirmação de percepção suprassensível. A observação descreve algo percebido; a analogia compara relações; o argumento liga razões a uma conclusão; a percepção suprassensível é o acesso que Steiner afirma ter a realidades além dos sentidos comuns. Esses enunciados cumprem funções diferentes. Compreender os termos é a primeira tarefa; avaliar o apoio de cada afirmação é uma tarefa adicional.'
 ],quoteTranslation:'Mas, de modo mais fundamental, aqui, como em outros lugares, Steiner nunca deseja interferir na liberdade do indivíduo.',close:'É o organizador descrevendo a intenção de Steiner. “Liberdade” designa um objetivo educativo; não torna corretas todas as afirmações fisiológicas da coletânea. Ao citar, distinga quem fala de quem está sendo descrito.',
 example:'Uma leitora ouve que o café favorece a sequência dos pensamentos e decide que todo estudante deve tomá-lo.',explanation:'A leitora transformou um efeito relatado em instrução universal. A pergunta recorrente do livro é o que favorece a atividade individual. Podemos examiná-la pela leitura e pelo raciocínio, sem exigir mudança alimentar.',
 takeaways:['A coletânea reúne comentários editoriais e palestras de contextos diferentes.','Explicar um efeito e mandar consumir um alimento são atos diferentes.','Compreensão, concordância e verificação são conquistas distintas.'],
 activity:'Abra um caderno com quatro títulos: trecho e página; significado com minhas palavras; tipo de afirmação; pergunta a investigar. Use a citação acima como primeira entrada. Registre uma suposição sobre alimentação que gostaria de examinar até o final do curso.',
 checks:[['Quem escreveu a frase citada?','Christian von Arnim, na introdução. Ela apresenta sua interpretação da abordagem de Steiner.'],['Recusar prescrições significa que o livro não recomenda nada?','Não. Há recomendações nos capítulos seguintes. Compare suas palavras, público e ressalvas com o compromisso declarado com a liberdade.'],['O que conta como êxito neste curso?','Uma explicação precisa, apoiada em um trecho, com avaliação fundamentada de seu alcance. Não é necessário concordar pessoalmente.']],
 context:'Este é um curso de leitura histórica e filosófica para adultos. Não oferece plano alimentar nem programa de tratamento. Notas atuais de saúde acompanham afirmações que poderiam ser confundidas com orientação médica.'}},
{id:1,chapter:1,span:'9–19',quotePage:10,quote:'What must we eat so that we are not merely the product of what we eat?',lecture:'Munich, 8 January 1909, GA 68; Berlin, 17 December 1908, GA 57',
 en:{title:'Nutrition in the Light of Spiritual Science',goal:'Explain why Steiner treats digestion as activity and connects nourishment with freedom.',
 theory:[
 'Steiner begins with the saying that a human being is what they eat, attributed here to Feuerbach. He changes the direction of the question. Instead of asking only which substances enter the body, he asks whether the body can become an instrument for intentions. The key move is from passive reception to active transformation: what does a person do with what is received?',
 'His explanation uses four members of the human being. The physical body is the bodily organization accessible to the senses. The etheric or life body names his principle of life and formative activity; the astral body names sentience, pleasure, pain and desire; the I names self-awareness and individual agency. These are interrelated members in his spiritual account, not four separate anatomical organs. He describes plant growth as building substances through outer light and human inner activity as breaking down what has been built.',
 'From this framework he interprets vegetable and animal foods as calling for different degrees of inner work. He associates a plant diet with inner flexibility, meat with certain outward capacities, milk with a mediating role, and stimulants with externally supported activity. These are the chapter’s proposed relationships. The educational thread is that making a task easier and developing one’s own capacity are not always the same thing. His generalizations about peoples and character do not establish the character of an individual eater.'
 ],quoteTranslation:null,close:'The wording turns the opening maxim into a problem of agency. “Not merely” leaves bodily dependence in view while asking whether intentional activity can exceed it.',
 example:'Two students use a prepared summary. One memorizes it; the other reconstructs the argument and checks it against the book.',explanation:'Both receive the same material, but their activity differs. This illustrates why Steiner attends to transformation. It does not demonstrate his claims about plant fats or the astral body.',
 takeaways:['Nutrition is presented as an active relationship, not only an intake of substances.','The four members supply the explanatory vocabulary of the chapter.','The aim of freedom concerns how assistance relates to a person’s own activity.'],activity:'Draw the four members as a list, with one function assigned to each in this chapter. Then paraphrase the opening food question without recommending a particular diet. Add the limit of the student-summary analogy.',
 checks:[['Why change Feuerbach’s question?','Steiner wants to ask how nourishment might support independent activity rather than exhaust the explanation of a person.'],['Is the astral body another word for the nervous system?','No. He treats the nervous system as a bodily expression of the astral body; the two terms are not identical.'],['Does the worked example prove a vegetarian diet produces freer thinking?','No. It illustrates active use of received material. The dietary claim needs its own evidence.']],context:'The chapter’s dietary portraits are historical spiritual interpretations. They are not tests of a person’s intelligence, moral worth or spiritual attainment.'},
 pt:{title:'A nutrição à luz da ciência espiritual',goal:'Explique por que Steiner trata a digestão como atividade e relaciona alimentação e liberdade.',
 theory:[
 'Steiner começa com a frase de que o ser humano é aquilo que come, atribuída aqui a Feuerbach. Ele muda a direção da pergunta. Em vez de perguntar apenas quais substâncias entram no corpo, pergunta se o corpo pode tornar-se instrumento das intenções. O movimento principal vai da recepção passiva à transformação ativa: o que a pessoa faz com aquilo que recebe?',
 'A explicação usa quatro membros do ser humano. O corpo físico é a organização corporal acessível aos sentidos. O corpo etérico ou vital designa seu princípio de vida e formação; o corpo astral designa sensibilidade, prazer, dor e desejo; o eu designa autoconsciência e ação individual. São membros relacionados na concepção espiritual de Steiner, e não quatro órgãos anatômicos separados. Ele descreve o crescimento vegetal como construção de substâncias pela luz exterior e a atividade interna humana como decomposição do que foi construído.',
 'Nesse quadro, interpreta alimentos vegetais e animais como exigindo graus diferentes de trabalho interior. Relaciona alimentação vegetal e flexibilidade interna, carne e certas capacidades exteriores, leite e mediação, estimulantes e atividade sustentada de fora. Essas são as relações propostas no capítulo. O fio educativo é que facilitar uma tarefa e desenvolver a própria capacidade nem sempre coincidem. Suas generalizações sobre povos e caráter não estabelecem o caráter de quem come determinado alimento.'
 ],quoteTranslation:'O que devemos comer para não sermos meramente o produto daquilo que comemos?',close:'A pergunta transforma a máxima inicial em um problema de autonomia. “Não meramente” mantém a dependência corporal em vista e pergunta se a atividade intencional pode ultrapassá-la.',example:'Dois estudantes usam um resumo pronto. Um o memoriza; o outro reconstrói o argumento e o confere no livro.',explanation:'Ambos recebem o mesmo material, mas suas atividades diferem. Isso ilustra a atenção de Steiner à transformação. Não demonstra suas afirmações sobre gorduras vegetais ou corpo astral.',
 takeaways:['A nutrição é apresentada como relação ativa, além da ingestão de substâncias.','Os quatro membros fornecem o vocabulário explicativo do capítulo.','A liberdade envolve a relação entre ajuda recebida e atividade própria.'],activity:'Liste os quatro membros e uma função atribuída a cada um neste capítulo. Depois reformule a pergunta alimentar inicial sem recomendar uma dieta. Acrescente o limite da analogia do resumo.',checks:[['Por que mudar a pergunta de Feuerbach?','Steiner pergunta como a alimentação poderia apoiar a atividade independente, sem esgotar a explicação da pessoa.'],['Corpo astral significa sistema nervoso?','Não. O sistema nervoso é apresentado como expressão corporal do corpo astral; os termos não são idênticos.'],['O exemplo prova que a alimentação vegetariana produz pensamento mais livre?','Não. Ilustra o uso ativo de um material recebido. A afirmação alimentar exige evidência própria.']],context:'Os retratos alimentares do capítulo são interpretações espirituais históricas. Não avaliam a inteligência, o valor moral ou o desenvolvimento espiritual de uma pessoa.'}},
{id:2,chapter:2,span:'20–30',quotePage:21,quote:'Nothing that human beings take into themselves remains as it is; nothing remains earthly.',lecture:'Dornach, 10 November 1923, GA 230',references:['digestion','diabetes'],
 en:{title:'The Penetration of Substance with Spirit',goal:'Follow Steiner’s account of transformation and the inverted plant image.',
 theory:[
 'The chapter argues that processes inside a living human being cannot simply be pictured as processes in a laboratory vessel. Steiner gives this a specific spiritual meaning: mineral substance must pass through what he calls warmth ether, receive cosmic formative forces, and become bodily substance again. Warmth ether is a technical term in his cosmology. It is not simply a measured rise in temperature or the ordinary release of energy during metabolism.',
 'His plant image extends the argument. Outside the body, a root holds the plant to earth while flower and shoot open toward light. In human digestion, he says, this orientation reverses: the root tendency moves toward the head and the flower tendency toward the lower organism. The image lets the reader picture a change in relationship, not just a change in size. He then distinguishes human and animal digestion and introduces elemental beings of fear in his account of animal life.',
 'Milk and honey close the chapter. Milk is associated with formative activity proceeding from the child’s head; the bee colony is pictured as a head open to the world, and honey as supporting formative activity later in life. The phrase about a land of milk and honey becomes a spiritual reading of a familiar image. These correspondences are the proposed meaning of the lecture, not a menu for children or older adults.'
 ],quoteTranslation:null,close:'“Nothing” makes the claim comprehensive. The following sentences specify a spiritual and cosmic transformation, so reducing this sentence to ordinary chemical digestion would change its meaning.',example:'A seed planted in a garden and the same seed processed as food enter different relationships.',explanation:'A change of setting changes what happens to a substance. That familiar point helps approach the chapter; it does not establish a warmth-ether stage or cosmic forces.',takeaways:['Transformation is the chapter’s central principle.','The inverted plant connects root and flower with different human regions.','Milk and honey are interpreted through formative forces.'],activity:'Draw two labelled arrows: root → flower outside; head → lower organism in Steiner’s inverted image. Add his proposed warmth-ether sequence for minerals. Under each diagram write “Steiner’s account” and a question that would need independent investigation.',checks:[['Is warmth ether just another name for body heat?','No. It includes a claimed spiritual stage and receptivity to cosmic forces.'],['Why does the plant image reverse?','Steiner says the root’s earthbound tendency is released upward in human digestion while the flower tendency remains below.'],['What does the milk-and-honey example add?','It connects the formative needs of different ages with his interpretation of natural processes. It is not an established feeding protocol.']],context:'Modern digestion describes breakdown and absorption of nutrients. Diabetes involves problems with insulin production or action; the chapter’s account of untransformed substance and lost cosmic connection is not a medical explanation of diabetes.'},
 pt:{title:'A penetração da substância pelo espírito',goal:'Acompanhe a transformação proposta por Steiner e a imagem da planta invertida.',theory:[
 'O capítulo argumenta que os processos dentro de um ser humano vivo não podem ser simplesmente imaginados como processos em um recipiente de laboratório. Steiner dá a isso um sentido espiritual específico: a substância mineral deve passar pelo que chama de éter calórico, receber forças formativas cósmicas e tornar-se novamente substância corporal. Éter calórico é um termo técnico de sua cosmologia. Não é apenas aumento mensurável de temperatura nem liberação comum de energia no metabolismo.',
 'A imagem da planta amplia o argumento. Fora do corpo, a raiz prende a planta à terra enquanto flor e broto se abrem à luz. Na digestão humana, segundo Steiner, essa orientação se inverte: a tendência da raiz segue à cabeça e a da flor à região inferior. A imagem permite pensar uma mudança de relação, não apenas de tamanho. Ele distingue depois a digestão humana e animal e introduz seres elementares do medo em sua descrição da vida animal.',
 'Leite e mel encerram o capítulo. O leite é associado à formação que parte da cabeça da criança; a colônia de abelhas é descrita como uma cabeça aberta ao mundo, e o mel como apoio à formação em outra fase da vida. A expressão sobre uma terra de leite e mel recebe uma leitura espiritual. Essas correspondências são o sentido proposto pela palestra, não um cardápio para crianças ou idosos.'
 ],quoteTranslation:'Nada do que os seres humanos recebem em si permanece como é; nada permanece terrestre.',close:'“Nada” torna a afirmação abrangente. As frases seguintes especificam uma transformação espiritual e cósmica; reduzi-la à digestão química comum mudaria seu significado.',example:'Uma semente plantada no jardim e a mesma semente preparada como alimento entram em relações diferentes.',explanation:'A mudança de contexto muda o que acontece com a substância. Isso ajuda a abordar o capítulo, mas não estabelece uma etapa de éter calórico nem forças cósmicas.',takeaways:['A transformação é o princípio central do capítulo.','A planta invertida relaciona raiz e flor com regiões humanas diferentes.','Leite e mel são interpretados por forças formativas.'],activity:'Desenhe duas setas identificadas: raiz → flor no exterior; cabeça → região inferior na imagem invertida de Steiner. Acrescente a sequência do éter calórico para os minerais. Escreva “concepção de Steiner” e uma pergunta que exija investigação independente sob cada desenho.',checks:[['Éter calórico é outro nome para calor corporal?','Não. Inclui uma etapa espiritual e receptividade a forças cósmicas.'],['Por que a planta se inverte?','Steiner afirma que a tendência terrestre da raiz é liberada para cima na digestão humana, enquanto a tendência da flor permanece abaixo.'],['O que acrescenta o exemplo de leite e mel?','Relaciona necessidades formativas das idades com sua interpretação de processos naturais. Não é um protocolo alimentar estabelecido.']],context:'A digestão moderna descreve decomposição e absorção de nutrientes. O diabetes envolve problemas na produção ou ação da insulina; a explicação do capítulo sobre substância não transformada e perda de ligação cósmica não é uma explicação médica do diabetes.'}},
{id:3,chapter:3,span:'31–37',quotePage:33,quote:'The ultimate decision, however, must depend on the personal circumstances of the individual.',lecture:'The Hague, 21 March 1913, GA 145',references:['diet'],
 en:{title:'Nutrition from a Cosmic Perspective',goal:'Compare milk, plant and meat nourishment within the chapter’s spiritual framework.',theory:[
 'Here the audience is interested in esoteric development. Steiner compares three relationships: milk connects the individual with earthly humanity, plants connect the individual with the wider solar system, and meat binds the individual more strongly to earthly conditions. In this account, milk provides a kind of ballast: a spiritual seeker should remain capable of earthly work rather than become detached from human responsibilities.',
 'The chapter then differentiates substances. Protein is associated with spirits of form and fat with spirits of movement. Sugar is described as supporting an innocent bodily ego-character that counterbalances moral selflessness. The distinction matters: the author does not mean that selfish conduct becomes good through eating sugar. He proposes a bodily support for remaining an individual while developing selflessness in soul life.',
 'Coffee, tea and chocolate receive contrasting portraits. Coffee is linked with consistency, tea with wandering associations, and chocolate with ordinary comfortable life. These portraits are part of the lecture’s account of increasingly differentiated bodily experience. They should not become personality labels. Notice also the repeated qualifications: personal circumstances matter, and dependence on a stimulant is not the same as developing a capacity through one’s own effort.'
 ],quoteTranslation:null,close:'“However” limits the preceding recommendation about avoiding animal food. Read the qualification together with the advice; neither should disappear in a summary.',example:'A learner becomes so absorbed in private study that ordinary commitments receive little attention.',explanation:'This helps explain the metaphor of ballast: a spiritual aspiration still needs a relationship with everyday obligations. It supplies no evidence that dairy products create that relationship.',takeaways:['The chapter compares earthly connection, cosmic openness and earthly binding.','Bodily ego-character is distinguished from moral selfishness.','The audience and individual qualifications shape the recommendations.'],activity:'Make a three-row comparison for milk, plants and meat: proposed relationship, purpose in development, qualification. Then choose one beverage portrait and explain why it cannot establish a drinker’s character.',checks:[['Why does Steiner use the idea of ballast?','He wants spiritual development to remain connected with earthly human work.'],['Does the sugar argument endorse selfish behaviour?','No. It distinguishes bodily individuality from the moral cultivation of selflessness.'],['What does the quotation prevent us from doing?','Presenting the chapter’s advice as a universal rule independent of personal circumstances.']],context:'The cosmic correspondences are spiritual claims. They do not establish a need for dairy or added sugar for spiritual development. WHO’s dietary framework emphasizes adequacy, balance, moderation and diversity.'},
 pt:{title:'A nutrição de uma perspectiva cósmica',goal:'Compare leite, vegetais e carne no quadro espiritual do capítulo.',theory:[
 'Aqui o público se interessa pelo desenvolvimento esotérico. Steiner compara três relações: o leite liga o indivíduo à humanidade terrestre, os vegetais o ligam ao sistema solar mais amplo, e a carne o prende mais fortemente às condições terrestres. Nessa descrição, o leite oferece uma espécie de lastro: quem busca desenvolvimento espiritual deve continuar capaz de atuar na Terra, sem abandonar responsabilidades humanas.',
 'O capítulo diferencia depois as substâncias. A proteína é associada aos espíritos da forma e a gordura aos espíritos do movimento. O açúcar é descrito como apoio a um caráter corporal de eu, inocente, que contrabalança a abnegação moral. A distinção importa: o autor não afirma que comer açúcar torna boa uma conduta egoísta. Propõe um apoio corporal para permanecer indivíduo enquanto se desenvolve a abnegação na vida anímica.',
 'Café, chá e chocolate recebem retratos contrastantes. O café é ligado à continuidade, o chá às associações dispersas e o chocolate à vida cotidiana confortável. Esses retratos pertencem à descrição de uma experiência corporal progressivamente diferenciada. Não devem virar rótulos de personalidade. Observe também as ressalvas: circunstâncias pessoais importam, e depender de um estimulante não equivale a desenvolver uma capacidade pelo próprio esforço.'
 ],quoteTranslation:'A decisão final, entretanto, deve depender das circunstâncias pessoais do indivíduo.',close:'“Entretanto” limita a recomendação anterior de evitar alimentos animais. Leia a ressalva junto com o conselho; nenhum deles deve desaparecer do resumo.',example:'Uma pessoa se absorve tanto no estudo privado que deixa de cuidar dos compromissos cotidianos.',explanation:'Isso ajuda a compreender a metáfora do lastro: a aspiração espiritual continua precisando de relação com as obrigações diárias. Não comprova que laticínios criem essa relação.',takeaways:['O capítulo compara ligação terrestre, abertura cósmica e aprisionamento ao terrestre.','O caráter corporal de eu é distinguido do egoísmo moral.','O público e as ressalvas individuais moldam as recomendações.'],activity:'Compare leite, vegetais e carne em três linhas: relação proposta, finalidade no desenvolvimento e ressalva. Escolha depois um retrato de bebida e explique por que ele não estabelece o caráter de quem a toma.',checks:[['Por que Steiner usa a ideia de lastro?','Deseja que o desenvolvimento espiritual permaneça ligado ao trabalho humano terrestre.'],['O argumento sobre açúcar aprova o egoísmo?','Não. Distingue individualidade corporal e cultivo moral da abnegação.'],['O que a citação nos impede de fazer?','Apresentar o conselho como regra universal independente das circunstâncias pessoais.']],context:'As correspondências cósmicas são afirmações espirituais. Não estabelecem necessidade de laticínios ou açúcar adicionado para o desenvolvimento espiritual. A orientação alimentar da OMS destaca adequação, equilíbrio, moderação e diversidade.'}},
{id:4,chapter:4,span:'38–49',quotePage:44,quote:'the etheric body combats the rotting of proteins, the astral body combats fats going rancid, and the I combats the fermentation of sugar and starch.',lecture:'Dornach, 23 January 1923, GA 352',references:['digestion'],
 en:{title:'Nutrition and the Human Body',goal:'Reconstruct the chapter’s threefold account of resisting decomposition.',theory:[
 'Steiner asks what keeps a living organism from behaving like food left to spoil. He organizes the answer around three contrasts: proteins and rotting; fats and rancidity; starch or sugar and fermentation. The etheric body, astral body and I are presented as the respective counteracting agencies. This is his attempt to explain organized living activity through the four-member picture introduced in Chapter 1.',
 'The chapter also relates solid, fluid, gaseous and warmth conditions to physical body, etheric body, astral body and I. These are correspondences within the lecture, not interchangeable names. The same vocabulary is used to interpret overconsumption, alcohol and digestion. The overarching point is that a substance’s significance depends on what the organism can do with it, not only on the amount swallowed.',
 'His discussion ranges from changing protein recommendations to potatoes and materialism, and from hangovers to mineral springs. These examples carry different kinds of claims. The fact that medical recommendations can change illustrates revisability; it does not, by itself, verify a spiritual explanation. Likewise, the contrast between a living and a dead organism poses a real question without proving the particular invisible agencies proposed in the answer.'
 ],quoteTranslation:null,close:'Read the three clauses in their printed order. Each pairs a member with one process it is said to counteract. This is an excerpt from a longer sentence.',example:'A cut piece of food decays, while a living plant maintains and repairs its tissues.',explanation:'The contrast directs attention to organized processes in life. To infer the etheric body as their cause requires the additional premises of Steiner’s account; the contrast alone is not sufficient.',takeaways:['The chapter pairs three decomposition processes with three spiritual members.','Its theme is regulation and transformation, rather than quantity alone.','An explanatory question does not automatically prove the proposed answer.'],activity:'Create the three-row correspondence table from the quotation. Beside it, list the solid/fluid/gas/warmth sequence. Explain why those two tables answer different questions. Keep this work for comparison with Chapter 9.',checks:[['What does the etheric body counteract here?','The rotting of proteins, in Steiner’s account of the living organism.'],['Why are the two tables different?','One pairs members with processes they counteract; the other pairs members with conditions of matter.'],['Do revised protein recommendations prove this physiology?','No. They show that recommendations can be revised. The proposed mechanism still needs separate support.']],context:'Study the mineral-spring and poisoning passages as historical claims. Do not use egg white as an antidote or reproduce the suggested exposure to foul-smelling gases. Contemporary digestion is explained through coordinated organ, enzyme, hormone and nerve activity.'},
 pt:{title:'A nutrição e o corpo humano',goal:'Reconstrua a descrição de três processos de resistência à decomposição.',theory:[
 'Steiner pergunta o que impede um organismo vivo de se comportar como alimento deixado a estragar. Organiza a resposta em três contrastes: proteínas e putrefação; gorduras e rancificação; amido ou açúcar e fermentação. Corpo etérico, corpo astral e eu são apresentados como agentes que se opõem a esses processos, respectivamente. É sua tentativa de explicar a atividade viva organizada por meio dos quatro membros do Capítulo 1.',
 'O capítulo também relaciona sólido, líquido, gasoso e calor com corpo físico, corpo etérico, corpo astral e eu. São correspondências da palestra, não nomes intercambiáveis. O mesmo vocabulário interpreta excesso alimentar, álcool e digestão. O ponto geral é que o significado de uma substância depende daquilo que o organismo consegue fazer com ela, além da quantidade ingerida.',
 'A discussão vai de mudanças nas recomendações de proteína a batatas e materialismo, de ressacas a fontes minerais. Os exemplos contêm tipos diferentes de afirmação. A mudança de recomendações médicas ilustra a possibilidade de revisão; não verifica, por si, uma explicação espiritual. Da mesma forma, o contraste entre organismo vivo e morto levanta uma pergunta real sem provar os agentes invisíveis propostos como resposta.'
 ],quoteTranslation:'o corpo etérico combate a putrefação das proteínas, o corpo astral combate a rancificação das gorduras e o eu combate a fermentação do açúcar e do amido.',close:'Leia as três orações na ordem do texto. Cada uma relaciona um membro com o processo ao qual ele supostamente se opõe. A citação é um trecho de uma frase mais longa.',example:'Um pedaço cortado de alimento se decompõe, enquanto uma planta viva mantém e repara seus tecidos.',explanation:'O contraste chama atenção para processos organizados da vida. Inferir o corpo etérico como causa exige premissas adicionais da concepção de Steiner; o contraste sozinho não basta.',takeaways:['Três processos de decomposição são relacionados a três membros espirituais.','O tema é regulação e transformação, além de quantidade.','Uma pergunta explicativa não prova automaticamente a resposta proposta.'],activity:'Monte a tabela de três linhas da citação. Ao lado, liste sólido/líquido/gás/calor. Explique por que as tabelas respondem a perguntas diferentes. Guarde-as para comparar com o Capítulo 9.',checks:[['A que se opõe o corpo etérico aqui?','À putrefação das proteínas, na descrição de Steiner do organismo vivo.'],['Por que as duas tabelas diferem?','Uma relaciona membros e processos combatidos; a outra relaciona membros e condições da matéria.'],['Recomendações revistas de proteína provam essa fisiologia?','Não. Mostram que recomendações podem mudar. O mecanismo proposto precisa de apoio próprio.']],context:'Estude as passagens sobre fontes minerais e envenenamento como afirmações históricas. Não use clara de ovo como antídoto nem reproduza a exposição sugerida a gases de mau cheiro. A digestão atual é explicada pela coordenação de órgãos, enzimas, hormônios e nervos.'}},
{id:5,chapter:5,span:'50–56',quotePage:52,quote:'So you see, when one speaks of nutrition one has to consider how foodstuffs are being cultivated.',lecture:'Dornach, 2 August 1924, GA 354',references:['diet','diabetes'],
 en:{title:'Healthy Nutrition and the Quality of Food',goal:'Connect food quality, cultivation and attention to the individual.',theory:[
 'The watchmaker analogy opens a question about rebuilding. Someone who dismantles a watch can understand its arrangement before putting it together. Steiner uses this to picture the organism breaking down dietary protein and making its own. The analogy highlights transformation; it cannot substitute for a biochemical account of which materials are absorbed and reused.',
 'The argument then moves from the eater to the farm. Steiner describes the plant as living and insists that its soil must be treated accordingly. He contrasts farm manure, processed through an animal organism, with mineral fertilizer understood merely as a chemical mixture. In his account, the difference influences the quality of plant protein and eventually human vitality. This is the chapter’s strongest bridge to a future study of biodynamics: nutrition includes questions about how a crop is grown.',
 'A second strand concerns appetite. He criticizes a friend who weighs every portion and urges attention to children’s likes and dislikes. His larger concern is that abstract rules can displace attentive observation. However, the chapter moves from preferences to specific diagnoses—for example, claiming that sugar-seeking indicates a liver problem. Separate the worthwhile question “Have we listened to this child?” from the further claim that a preference identifies a disease. The latter does not follow simply from listening.'
 ],quoteTranslation:null,close:'The sentence widens the field of attention from the plate to cultivation. The surrounding discussion makes the more specific manure-and-protein claim, which should be recorded separately from this general connection.',example:'Two loaves have similar labels, but the grains came from different farms and were milled and baked differently.',explanation:'The label answers some questions; a history of cultivation and preparation answers others. Neither a label nor a farm story alone settles every question about nutritional quality.',takeaways:['The chapter joins the eater, the plant and cultivation.','The watchmaker comparison illustrates breaking down and rebuilding.','Attention to preferences must be distinguished from diagnosis by preference.'],activity:'Create a food biography for one familiar ingredient: crop, soil management if known, harvest, preparation, meal. Mark unknowns instead of guessing. Add two questions to carry into the biodynamics book: one about farming practice and one about evidence of food quality.',checks:[['What is the bridge to biodynamics?','The idea that food quality begins with cultivation, particularly Steiner’s contrast between manure and mineral fertilizer.'],['What does the watch analogy establish?','It clarifies his rebuilding idea. It does not establish the detailed chemistry claimed in the chapter.'],['Can craving sugar diagnose liver disease?','No. A preference alone is insufficient to diagnose disease; the chapter’s specific inference should not be used as a clinical rule.']],context:'The book’s claims that cravings diagnose liver disease or diabetes, or that carrots treat worms, are not diagnostic or treatment guidance. Its fixed historical protein quantities are not individual targets. Dietary needs depend on the person and context.'},
 pt:{title:'Nutrição saudável e qualidade dos alimentos',goal:'Relacione qualidade alimentar, cultivo e atenção ao indivíduo.',theory:[
 'A analogia do relojoeiro abre a questão da reconstrução. Quem desmonta um relógio pode compreender sua organização antes de remontá-lo. Steiner usa a imagem para descrever o organismo decompondo a proteína alimentar e produzindo a própria. A analogia destaca transformação; não substitui uma explicação bioquímica dos materiais absorvidos e reutilizados.',
 'O argumento passa de quem come para a propriedade agrícola. Steiner descreve a planta como viva e insiste que o solo deve ser tratado de acordo com isso. Contrasta o esterco da propriedade, processado por um organismo animal, com o fertilizante mineral entendido apenas como mistura química. Em sua descrição, a diferença influencia a qualidade da proteína vegetal e depois a vitalidade humana. É a ligação mais forte do capítulo com um estudo futuro de biodinâmica: a nutrição inclui perguntas sobre como o alimento é cultivado.',
 'Outra linha trata do apetite. Steiner critica um amigo que pesa cada porção e recomenda atenção às preferências e aversões infantis. Sua preocupação geral é que regras abstratas substituam a observação atenta. Entretanto, o capítulo passa das preferências a diagnósticos específicos, como afirmar que procurar açúcar indica um problema no fígado. Separe a pergunta útil “Escutamos esta criança?” da afirmação adicional de que uma preferência identifica doença. Esta não decorre simplesmente da escuta.'
 ],quoteTranslation:'Assim, vocês veem que, quando se fala de nutrição, é preciso considerar como os alimentos estão sendo cultivados.',close:'A frase amplia a atenção do prato para o cultivo. A discussão ao redor faz a afirmação mais específica sobre esterco e proteína, que deve ser registrada separadamente dessa ligação geral.',example:'Dois pães têm rótulos semelhantes, mas os grãos vieram de propriedades diferentes e foram moídos e assados de modos distintos.',explanation:'O rótulo responde a algumas perguntas; a história do cultivo e do preparo responde a outras. Nenhum deles, sozinho, resolve toda questão de qualidade nutricional.',takeaways:['O capítulo liga quem come, a planta e o cultivo.','A imagem do relojoeiro ilustra decomposição e reconstrução.','Observar preferências deve ser distinguido de diagnosticar por preferências.'],activity:'Faça a biografia alimentar de um ingrediente conhecido: cultivo, manejo do solo se conhecido, colheita, preparo e refeição. Marque o que não sabe. Acrescente duas perguntas para o livro de biodinâmica: uma sobre prática agrícola e outra sobre evidências da qualidade alimentar.',checks:[['Qual é a ligação com a biodinâmica?','A ideia de que a qualidade alimentar começa no cultivo, especialmente o contraste entre esterco e fertilizante mineral.'],['O que a analogia do relógio estabelece?','Esclarece a ideia de reconstrução. Não estabelece a química detalhada afirmada no capítulo.'],['Desejar açúcar diagnostica doença do fígado?','Não. Uma preferência é insuficiente para diagnosticar doença; a inferência específica não deve virar regra clínica.']],context:'As afirmações de que desejos diagnosticam doença hepática ou diabetes, ou de que cenouras tratam vermes, não orientam diagnóstico nem tratamento. Quantidades históricas fixas de proteína não são metas individuais. As necessidades dependem da pessoa e do contexto.'}},
{id:6,chapter:6,span:'57–66',quotePage:62,quote:'Remember, they are now different from the ones we ate. Our organism has changed them.',lecture:'Dornach, 16 September 1922, GA 347',references:['digestion'],
 en:{title:'The Processes of Digestion',goal:'Trace the digestive sequence and identify where the lecture moves into soul-spiritual interpretation.',theory:[
 'Steiner follows food from mouth to stomach and intestines. He names saliva and ptyalin, pepsin, pancreatic secretion and trypsin, then bile. The sequence is intended to show repeated transformation rather than a single act of swallowing. Chyme means the partly digested mixture moving from the stomach into the intestine. The names are useful landmarks even when the lecture’s detailed account differs from current physiology.',
 'The second layer concerns perception within the organs. Steiner attributes a kind of perception to the liver and thinking to the kidneys. He compares the production of bile with the way an onion brings tears to the eyes and relates internal processes to dream imagery. This is not a claim that a person consciously thinks with the kidneys in the same way they solve a problem. It is his extension of soul activity beyond ordinary head-centred awareness.',
 'The final movement connects substances with thinking and willing. Salts are related to thought; phosphorus is related to will. The question is how matter could become an instrument of activities that, on his account, are not explained by matter alone. His glass-of-water analogy also suggests direct distribution through the body’s fluids. To study the chapter well, keep its sequence, its analogies and its spiritual interpretation distinct.'
 ],quoteTranslation:null,close:'The pronoun “they” refers to the transformed food substances listed immediately before this sentence. Name that antecedent when paraphrasing; otherwise the sentence becomes a vague slogan.',example:'A learner draws one arrow from “food” to “body,” then redraws it with mouth, stomach, intestine and absorption.',explanation:'The expanded map makes processing visible. Adding the liver’s “perception” creates another explanatory layer, which needs a label rather than being silently inserted as ordinary anatomy.',takeaways:['The lecture studies digestion as a sequence of transformations.','Organ perception and thinking belong to its soul-spiritual interpretation.','An analogy can organize a question while oversimplifying a mechanism.'],activity:'Make two maps: the lecture’s organ sequence and the contemporary NIDDK sequence linked below. Circle two shared landmarks. Mark two differences, including protein breakdown or nutrient transport. Explain one difference in complete sentences.',checks:[['What is chyme?','The partly digested mixture passed from the stomach to the intestine.'],['What kind of claim is “the kidneys think”?','A claim within Steiner’s account of soul activity in the organs, not an ordinary description of conscious reasoning.'],['What is the limit of the glass-of-water comparison?','A body has specialized tissues, barriers and transport systems; nutrient distribution cannot be inferred from sugar dissolving in a glass.']],context:'Contemporary physiology describes proteins being broken down into amino acids and nutrients absorbed through the intestine into blood or lymph. It does not describe trypsin as producing preservative alcohol, or excess drinks as taking a direct shortcut from the gut to urine.'},
 pt:{title:'Os processos da digestão',goal:'Acompanhe a sequência digestiva e identifique a passagem à interpretação anímico-espiritual.',theory:[
 'Steiner acompanha o alimento da boca ao estômago e aos intestinos. Nomeia saliva e ptialina, pepsina, secreção pancreática e tripsina, depois bile. A sequência pretende mostrar transformação repetida, além do ato de engolir. Quimo é a mistura parcialmente digerida que passa do estômago ao intestino. Os nomes são referências úteis, mesmo quando os detalhes diferem da fisiologia atual.',
 'A segunda camada trata da percepção nos órgãos. Steiner atribui uma espécie de percepção ao fígado e pensamento aos rins. Compara a produção de bile com as lágrimas provocadas pela cebola e relaciona processos internos a imagens de sonhos. Não afirma que alguém pensa conscientemente com os rins do mesmo modo que resolve um problema. É sua extensão da atividade anímica além da consciência comum centrada na cabeça.',
 'O movimento final relaciona substâncias com pensar e querer. Sais são ligados ao pensamento; fósforo, à vontade. A pergunta é como a matéria pode tornar-se instrumento de atividades que, segundo ele, não são explicadas apenas pela matéria. A analogia do copo de água sugere também distribuição direta pelos líquidos do corpo. Para estudar bem, separe sequência, analogias e interpretação espiritual.'
 ],quoteTranslation:'Lembrem-se: agora elas são diferentes daquelas que comemos. Nosso organismo as transformou.',close:'O pronome “elas” retoma as substâncias alimentares transformadas listadas antes. Nomeie esse referente ao parafrasear; sem ele, a frase vira um lema vago.',example:'Uma estudante desenha uma seta de “alimento” a “corpo” e depois refaz o desenho com boca, estômago, intestino e absorção.',explanation:'O mapa ampliado torna visível o processamento. Acrescentar a “percepção” do fígado cria outra camada explicativa, que precisa ser identificada, em vez de entrar silenciosamente como anatomia comum.',takeaways:['A palestra estuda a digestão como sequência de transformações.','Percepção e pensamento dos órgãos pertencem à interpretação anímico-espiritual.','Uma analogia pode organizar uma pergunta e simplificar demais um mecanismo.'],activity:'Faça dois mapas: a sequência de órgãos da palestra e a sequência atual do NIDDK no link abaixo. Circule duas referências comuns. Marque duas diferenças, incluindo decomposição de proteínas ou transporte de nutrientes. Explique uma diferença com frases completas.',checks:[['O que é quimo?','A mistura parcialmente digerida que passa do estômago ao intestino.'],['Que tipo de afirmação é “os rins pensam”?','Uma afirmação da concepção de Steiner sobre atividade anímica nos órgãos, não uma descrição comum do raciocínio consciente.'],['Qual é o limite da comparação com o copo de água?','O corpo tem tecidos especializados, barreiras e transporte; não se deduz a distribuição de nutrientes do açúcar dissolvido num copo.']],context:'A fisiologia atual descreve proteínas decompostas em aminoácidos e nutrientes absorvidos pelo intestino para sangue ou linfa. Não descreve a tripsina como produtora de álcool conservante nem bebidas em excesso seguindo um atalho direto do intestino à urina.'}},
...nutritionPartTwo
];
